// Ders 18 verisi — LINE ve Telefon
const L18 = {
  tones:[],
  words:[
    {id:'w1',th:'โทรศัพท์',ro:'tho-ra-sap',tr:'telefon',tip:'Genel telefon kelimesi.',ctx:'Phuket taksi veya otel aramalarinda.',examples:[{th:'โทรศัพท์ผมแบตหมดครับ',ro:'tho-ra-sap pom baet mot khrap',tr:'Telefonumun sarji bitti.',bd:[{ro:'tho-ra-sap pom baet mot',tr:'telefon sarji bitti',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ขอใช้โทรศัพท์หน่อยครับ',ro:'khor chai tho-ra-sap noi khrap',tr:'Telefonu biraz kullanabilir miyim?',bd:[{ro:'khor chai tho-ra-sap noi',tr:'telefonu kullanabilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w2',th:'ข้อความ',ro:'khaw-khwaam',tr:'mesaj',tip:'SMS veya LINE mesaji icin.',ctx:'Konum ve bilgi yollarken.',examples:[{th:'ผมส่งข้อความในไลน์แล้วครับ',ro:'pom song khaw-khwaam nai line laeo khrap',tr:'LINEdan mesaj gonderdim.',bd:[{ro:'pom song khaw-khwaam nai line laeo',tr:'LINEdan mesaj gonderdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'อ่านข้อความนี้ให้หน่อยครับ',ro:'aan khaw-khwaam nii hai noi khrap',tr:'Bu mesaji okur musunuz?',bd:[{ro:'aan khaw-khwaam nii hai noi',tr:'bu mesaji okur musunuz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w3',th:'โทร',ro:'tho',tr:'arama',tip:'Fiil olarak aramak.',ctx:'Taksi, otel veya arkadas ararken.',examples:[{th:'ผมจะโทรหาเพื่อนครับ',ro:'pom ja tho haa phuean khrap',tr:'Arkadasimi arayacagim.',bd:[{ro:'pom ja tho haa phuean',tr:'arkadasimi arayacagim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'โทรกลับได้ไหมครับ',ro:'tho klap dai mai khrap',tr:'Geri arayabilir misiniz?',bd:[{ro:'tho klap dai mai',tr:'geri arayabilir misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w4',th:'เบอร์',ro:'ber',tr:'numara',tip:'Telefon numarasi.',ctx:'LINE eklerken veya rezervasyonda.',examples:[{th:'ขอเบอร์โทรหน่อยครับ',ro:'khor ber tho noi khrap',tr:'Telefon numarasini alabilir miyim?',bd:[{ro:'khor ber tho noi',tr:'telefon numarasini alabilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'เบอร์ผมคือศูนย์แปด...ครับ',ro:'ber pom khue sun paet khrap',tr:'Numaram 08... ',bd:[{ro:'ber pom khue sun paet',tr:'numaram 08...',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w5',th:'ไวไฟ',ro:'wai-fai',tr:'wifi',tip:'Taycada "wai-fai" denir.',ctx:'Kafe ve otel baglanti sorulari.',examples:[{th:'ร้านนี้มีไวไฟไหมครับ',ro:'raan-nii mii wai-fai mai khrap',tr:'Burada wifi var mi?',bd:[{ro:'raan-nii mii wai-fai mai',tr:'burada wifi var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'รหัสไวไฟคืออะไรครับ',ro:'ra-hat wai-fai khue a-rai khrap',tr:'Wifi sifresi nedir?',bd:[{ro:'ra-hat wai-fai khue a-rai',tr:'wifi sifresi nedir',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w6',th:'ชาร์จ',ro:'chaat',tr:'sarj',tip:'Sarj etmek fiili icin de kullanilir.',ctx:'Powerbank ve priz sorarken.',examples:[{th:'ขอชาร์จโทรศัพท์ได้ไหมครับ',ro:'khor chaat tho-ra-sap dai mai khrap',tr:'Telefonu sarj edebilir miyim?',bd:[{ro:'khor chaat tho-ra-sap dai mai',tr:'telefonu sarj edebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'แบตชาร์จเต็มแล้วครับ',ro:'baet chaat tem laeo khrap',tr:'Sarj tamamen doldu.',bd:[{ro:'baet chaat tem laeo',tr:'sarj tamamen doldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w7',th:'ซิม',ro:'sim',tr:'hat',tip:'SIM kart ve hat icin.',ctx:'Havalimani veya 7-Eleven hattinda.',examples:[{th:'ผมอยากซื้อซิมครับ',ro:'pom yaak sue sim khrap',tr:'SIM kart almak istiyorum.',bd:[{ro:'pom yaak sue sim',tr:'sim kart almak istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ซิมนี้ใช้ได้กี่วันครับ',ro:'sim nii chai dai kii wan khrap',tr:'Bu hat kac gun gecerli?',bd:[{ro:'sim nii chai dai kii wan',tr:'bu hat kac gun gecerli',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w8',th:'แอป',ro:'aep',tr:'uygulama',tip:'App kisaltmasi.',ctx:'LINE, Grab, Maps gibi.',examples:[{th:'ผมโหลดแอปไลน์แล้วครับ',ro:'pom lot aep line laeo khrap',tr:'LINE uygulamasini indirdim.',bd:[{ro:'pom lot aep line laeo',tr:'LINE uygulamasini indirdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'แอปนี้ใช้จองแท็กซี่ครับ',ro:'aep nii chai jong thaek-sii khrap',tr:'Bu uygulama taksi cagirmak icin.',bd:[{ro:'aep nii chai jong thaek-sii',tr:'bu uygulama taksi icin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w9',th:'ส่งรูป',ro:'song-ruup',tr:'fotograf gonder',tip:'LINEda en cok kullanilan fiil.',ctx:'Konum anlatirken fotograf atmak.',examples:[{th:'ผมส่งรูปให้แล้วครับ',ro:'pom song-ruup hai laeo khrap',tr:'Fotografi gonderdim.',bd:[{ro:'pom song-ruup hai laeo',tr:'fotografi gonderdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ช่วยส่งรูปเมนูให้ผมหน่อยครับ',ro:'chuay song-ruup menuu hai pom noi khrap',tr:'Menu fotografini gonderir misiniz?',bd:[{ro:'chuay song-ruup menuu hai pom noi',tr:'menu fotografini gonderir misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w10',th:'โลเคชัน',ro:'lo-khe-chan',tr:'konum',tip:'Konum paylasma ifadesi.',ctx:'Phukette bulusma noktasi atarken.',examples:[{th:'ส่งโลเคชันมาได้ไหมครับ',ro:'song lo-khe-chan maa dai mai khrap',tr:'Konumu atabilir misiniz?',bd:[{ro:'song lo-khe-chan maa dai mai',tr:'konumu atabilir misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ผมส่งโลเคชันในไลน์แล้วครับ',ro:'pom song lo-khe-chan nai line laeo khrap',tr:'Konumu LINEdan gonderdim.',bd:[{ro:'pom song lo-khe-chan nai line laeo',tr:'konumu LINEdan gonderdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
  ],
  grammar:[
    {title:'1. Telefon ve LINE Eylemleri',formula:'pom + [fiil] + laeo khrap',explain:'Gecmis veya tamamlanan dijital eylemlerde "laeo" cok kullanilir.',tips:['song = gondermek','tho = aramak','laeo = oldu/bitti','line = LINE uygulamasi','khrap = erkek kibar eki'],examples:[{th:'ผมส่งข้อความแล้วครับ',ro:'pom song khaw-khwaam laeo khrap',tr:'Mesaji gonderdim.',bd:[{ro:'pom song khaw-khwaam laeo',tr:'mesaji gonderdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ผมโทรแล้วครับ',ro:'pom tho laeo khrap',tr:'Aradim.',bd:[{ro:'pom tho laeo',tr:'aradim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ผมส่งรูปแล้วครับ',ro:'pom song-ruup laeo khrap',tr:'Fotografi gonderdim.',bd:[{ro:'pom song-ruup laeo',tr:'fotografi gonderdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ผมส่งโลเคชันแล้วครับ',ro:'pom song lo-khe-chan laeo khrap',tr:'Konumu attim.',bd:[{ro:'pom song lo-khe-chan laeo',tr:'konumu attim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {title:'2. Baglanti ve Teknik Sorular',formula:'mii ... mai khrap? | ... dai mai khrap?',explain:'Wifi, sarj ve hat islemlerinde soru kalibi cok net ve kisa olur.',tips:['mii ... mai = var mi','dai mai = olabilir mi','wai-fai = wifi','chaat = sarj','sim = hat'],examples:[{th:'มีไวไฟไหมครับ',ro:'mii wai-fai mai khrap',tr:'Wifi var mi?',bd:[{ro:'mii wai-fai mai',tr:'wifi var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ขอชาร์จโทรศัพท์ได้ไหมครับ',ro:'khor chaat tho-ra-sap dai mai khrap',tr:'Telefonu sarj edebilir miyim?',bd:[{ro:'khor chaat tho-ra-sap dai mai',tr:'telefonu sarj edebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ซิมนี้ใช้ได้ไหมครับ',ro:'sim nii chai dai mai khrap',tr:'Bu hati kullanabilir miyim?',bd:[{ro:'sim nii chai dai mai',tr:'bu hati kullanabilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ส่งโลเคชันมาได้ไหมครับ',ro:'song lo-khe-chan maa dai mai khrap',tr:'Konumu atabilir misiniz?',bd:[{ro:'song lo-khe-chan maa dai mai',tr:'konumu atabilir misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
  ],
  speaking:[
    {task:'Telefon isteme',th:'ขอใช้โทรศัพท์หน่อยครับ',ro:'khor chai tho-ra-sap noi khrap',tr:'Telefonu biraz kullanabilir miyim?',bd:[{ro:'khor chai tho-ra-sap noi',tr:'telefonu kullanabilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Mesaj gonderdigini soyle',th:'ผมส่งข้อความแล้วครับ',ro:'pom song khaw-khwaam laeo khrap',tr:'Mesaji gonderdim.',bd:[{ro:'pom song khaw-khwaam laeo',tr:'mesaji gonderdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Arama iste',th:'ช่วยโทรกลับได้ไหมครับ',ro:'chuay tho klap dai mai khrap',tr:'Geri arar misiniz?',bd:[{ro:'chuay tho klap dai mai',tr:'geri arar misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Numara sor',th:'ขอเบอร์โทรหน่อยครับ',ro:'khor ber tho noi khrap',tr:'Numaranizi alabilir miyim?',bd:[{ro:'khor ber tho noi',tr:'numaranizi alabilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Wifi sor',th:'มีไวไฟไหมครับ',ro:'mii wai-fai mai khrap',tr:'Wifi var mi?',bd:[{ro:'mii wai-fai mai',tr:'wifi var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Sarj etme izni iste',th:'ขอชาร์จโทรศัพท์ได้ไหมครับ',ro:'khor chaat tho-ra-sap dai mai khrap',tr:'Telefonu sarj edebilir miyim?',bd:[{ro:'khor chaat tho-ra-sap dai mai',tr:'telefonu sarj edebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Fotograf gonderdigini soyle',th:'ผมส่งรูปแล้วครับ',ro:'pom song-ruup laeo khrap',tr:'Fotografi gonderdim.',bd:[{ro:'pom song-ruup laeo',tr:'fotografi gonderdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Konum iste',th:'ส่งโลเคชันมาได้ไหมครับ',ro:'song lo-khe-chan maa dai mai khrap',tr:'Konumu atabilir misiniz?',bd:[{ro:'song lo-khe-chan maa dai mai',tr:'konumu atabilir misiniz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'📱 Havalimani SIM Hatti',
     lines:[
       {s:'Ali',th:'ผมอยากซื้อซิมครับ',ro:'pom yaak sue sim khrap',tr:'SIM kart almak istiyorum.',bd:[{ro:'pom yaak sue sim',tr:'sim kart almak istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ใช้กี่วันคะ',ro:'chai kii wan kha',tr:'Kac gun kullanacaksiniz?',bd:[{ro:'chai kii wan',tr:'kac gun kullanacaksiniz',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ห้าวันครับ มีเน็ตไม่อั้นไหม',ro:'haa wan khrap mii net mai an mai',tr:'Bes gun, limitsiz internet var mi?',bd:[{ro:'haa wan',tr:'bes gun',role:'Kelime'},{ro:'mii net mai an mai',tr:'limitsiz internet var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'มีค่ะ แพ็กนี้ใช้ได้เลย',ro:'mii kha phaek nii chai dai loey',tr:'Var, bu paket hemen kullanilir.',bd:[{ro:'phaek nii chai dai loey',tr:'bu paket hemen kullanilir',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'💬 LINE Bulusma',
     lines:[
       {s:'Ali',th:'ผมแอดไลน์คุณแล้วครับ',ro:'pom aed line khun laeo khrap',tr:'Sizi LINEdan ekledim.',bd:[{ro:'pom aed line khun laeo',tr:'LINEdan ekledim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'โอเคค่ะ ส่งโลเคชันมาเลย',ro:'o-kee kha song lo-khe-chan maa loey',tr:'Tamam, konumu gonderin.',bd:[{ro:'song lo-khe-chan maa loey',tr:'konumu hemen gonder',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ผมส่งโลเคชันแล้วครับ',ro:'pom song lo-khe-chan laeo khrap',tr:'Konumu gonderdim.',bd:[{ro:'pom song lo-khe-chan laeo',tr:'konumu gonderdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'เห็นแล้วค่ะ เจอกันหน้าคาเฟ่',ro:'hen laeo kha jer gan naa kha-fae',tr:'Gordum, kafenin onunde bulusalim.',bd:[{ro:'hen laeo',tr:'gordum',role:'V - Yuklem'},{ro:'jer gan naa kha-fae',tr:'kafe onunde bulusalim',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🔋 Kafede Sarj ve Wifi',
     lines:[
       {s:'Ali',th:'มีไวไฟไหมครับ',ro:'mii wai-fai mai khrap',tr:'Wifi var mi?',bd:[{ro:'mii wai-fai mai',tr:'wifi var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'มีค่ะ รหัสคือ Phuket2026',ro:'mii kha ra-hat khue phuket2026',tr:'Var, sifre Phuket2026.',bd:[{ro:'ra-hat khue phuket2026',tr:'sifre Phuket2026',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ขอชาร์จโทรศัพท์ได้ไหมครับ',ro:'khor chaat tho-ra-sap dai mai khrap',tr:'Telefonu sarj edebilir miyim?',bd:[{ro:'khor chaat tho-ra-sap dai mai',tr:'telefonu sarj edebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ได้ค่ะ ปลั๊กอยู่ข้างโต๊ะ',ro:'dai kha plak yuu khaang to',tr:'Olur, priz masanin yaninda.',bd:[{ro:'plak yuu khaang to',tr:'priz masanin yaninda',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'📷 Fotograf ve Arama',
     lines:[
       {s:'Ali',th:'ผมส่งรูปเมนูให้แล้วครับ',ro:'pom song-ruup menuu hai laeo khrap',tr:'Menu fotografini gonderdim.',bd:[{ro:'pom song-ruup menuu hai laeo',tr:'menu fotografini gonderdim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ได้รับแล้วค่ะ เดี๋ยวโทรกลับนะ',ro:'dai-rap laeo kha diao tho klap na',tr:'Aldim, birazdan geri arayayim.',bd:[{ro:'dai-rap laeo',tr:'aldim',role:'V - Yuklem'},{ro:'tho klap',tr:'geri ara',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'โอเคครับ ผมรอสาย',ro:'o-kee khrap pom ro saai',tr:'Tamam, aramayi bekliyorum.',bd:[{ro:'pom ro saai',tr:'aramayi bekliyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'โทรแล้วค่ะ ได้ยินไหมคะ',ro:'tho laeo kha dai-yin mai kha',tr:'Aradim, duyuyor musunuz?',bd:[{ro:'tho laeo',tr:'aradim',role:'V - Yuklem'},{ro:'dai-yin mai',tr:'duyuyor musun',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'มีไวไฟไหมครับ',q:'Ne soruluyor?',opts:['Wifi var mi','Hat var mi','Menu var mi'],c:0},
    {diff:'easy',th:'ผมส่งข้อความแล้วครับ',q:'Ne yapti?',opts:['Mesaj gonderdi','Arama yapti','Sarj etti'],c:0},
    {diff:'easy',th:'ขอเบอร์โทรหน่อยครับ',q:'Ne isteniyor?',opts:['Adres','Numara','Fiyat'],c:1},
    {diff:'medium',th:'ขอชาร์จโทรศัพท์ได้ไหมครับ',q:'Ne soruluyor?',opts:['Wifi sifresi','Sarj izni','SIM fiyat'],c:1},
    {diff:'medium',th:'ผมอยากซื้อซิมครับ',q:'Ne almak istiyor?',opts:['Powerbank','SIM kart','Kulaklik'],c:1},
    {diff:'medium',th:'ส่งโลเคชันมาได้ไหมครับ',q:'Ne isteniyor?',opts:['Fotograf','Konum','Menu'],c:1},
    {diff:'medium',th:'ผมแอดไลน์คุณแล้วครับ',q:'Ne yapti?',opts:['Line ekledi','Hatti kapatti','Mesaji sildi'],c:0},
    {diff:'hard',th:'รหัสไวไฟคืออะไรครับ',q:'Ne soruluyor?',opts:['Wifi sifresi nedir','Numaraniz nedir','Hangi uygulama'],c:0},
    {diff:'hard',th:'โทรกลับได้ไหมครับ',q:'Karsidan ne istiyor?',opts:['Geri arama','Fotograf gonderme','Adres degistirme'],c:0},
    {diff:'hard',th:'ผมส่งรูปให้แล้วครับ',q:'Ne tamamlandi?',opts:['Arama','Fotograf gonderme','Odeme'],c:1},
  ],
  quiz:[
    {q:'"tho-ra-sap" ne demek?',opts:['Telefon','Mesaj','Hat','Saat'],c:0},
    {q:'"khaw-khwaam" ne demek?',opts:['Arama','Mesaj','Uygulama','Konum'],c:1},
    {q:'"tho" ne demek?',opts:['Indirmek','Arama yapmak','Yuklemek','Kapatmak'],c:1},
    {q:'"ber" ne demek?',opts:['Numara','Sim','Wifi','Pil'],c:0},
    {q:'"wai-fai" ne demek?',opts:['Bluetooth','Wifi','4G','Sarj'],c:1},
    {q:'"chaat" ne demek?',opts:['Sil','Acar','Sarj','Bekle'],c:2},
    {q:'"sim" ne demek?',opts:['Hat/SIM','Kulaklik','Sifre','Kamera'],c:0},
    {q:'"aep" ne demek?',opts:['Uygulama','Arama','Mesaj','Rehber'],c:0},
    {q:'"song-ruup" ne demek?',opts:['Fotograf cek','Fotograf gonder','Fotograf sil','Fotograf yazdir'],c:1},
    {q:'"lo-khe-chan" ne demek?',opts:['Konum','Ses','Ekran','Numara'],c:0},
  ],
};

LESSONS[18] = L18;
