// Ders 14 verisi — tayca-v3
// =================== VERİ: DERS 14 — Sosyallesme ===================
const L14 = {
  tones:[],
  words:[
    {id:'w1',th:'เพื่อน',ro:'phuean',tr:'Arkadas',
     tip:'Yakın arkadas veya genel arkadas icin kullanilir.',
     ctx:'Phuket te sosyal ortamda temel kelime.',
     examples:[
      {th:'ผมมีเพื่อนไทยครับ',ro:'pom mii phuean thai khrap',tr:'Thai arkadaslarim var.',bd:[{ro:'pom mii phuean thai',tr:'thai arkadasim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'เพื่อนผมชอบเที่ยวครับ',ro:'phuean pom chop thiao khrap',tr:'Arkadasim gezmeyi sever.',bd:[{ro:'phuean pom chop thiao',tr:'arkadasim gezmeyi sever',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'ปาร์ตี้',ro:'paa-tee',tr:'Parti',
     tip:'Ingilizce party kelimesinden gelir.',
     ctx:'Plaj ve beach club etkinliklerinde sik duyulur.',
     examples:[
      {th:'คืนนี้มีปาร์ตี้ไหมครับ',ro:'khuen-nii mii paa-tee mai khrap',tr:'Bu gece parti var mi?',bd:[{ro:'khuen-nii mii paa-tee mai',tr:'bu gece parti var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ปาร์ตี้เริ่มกี่โมงครับ',ro:'paa-tee roem gii-moong khrap',tr:'Parti kacta basliyor?',bd:[{ro:'paa-tee roem gii-moong',tr:'parti kacta basliyor',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'เชิญ',ro:'choen',tr:'Davet',
     tip:'Kibarca davet etmek veya buyur etmek icin kullanilir.',
     ctx:'Mesajlasmada ve yuz yuze konusmada yaygin.',
     examples:[
      {th:'ผมขอเชิญคุณมาปาร์ตี้ครับ',ro:'pom khor choen khun maa paa-tee khrap',tr:'Sizi partiye davet ediyorum.',bd:[{ro:'pom khor choen khun maa paa-tee',tr:'sizi partiye davet ediyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ขอบคุณที่เชิญนะครับ',ro:'khop-khun thii choen na khrap',tr:'Davet icin tesekkurler.',bd:[{ro:'khop-khun thii choen',tr:'davet icin tesekkur',role:'V - Yuklem'},{ro:'na khrap',tr:'onay eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'เบียร์',ro:'bia',tr:'Biraya',
     tip:'Icki siparisi verirken en temel kelime.',
     ctx:'Arkadas bulusmalarinda sikca gecen ifade.',
     examples:[
      {th:'ไปดื่มเบียร์กันไหมครับ',ro:'pai duem bia gan mai khrap',tr:'Biraya gidelim mi?',bd:[{ro:'pai duem bia gan mai',tr:'biraya gidelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมดื่มเบียร์ไม่เก่งครับ',ro:'pom duem bia mai geng khrap',tr:'Bira konusunda cok iyi degilim.',bd:[{ro:'pom duem bia mai geng',tr:'birayi iyi icemiyorum',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'คุย',ro:'khui',tr:'Sohbet',
     tip:'Konusmak, sohbet etmek anlamina gelir.',
     ctx:'Tanisma sonrasi kisa sohbetlerde kullanilir.',
     examples:[
      {th:'คุยกันสนุกมากครับ',ro:'khui gan sa-nuk maak khrap',tr:'Sohbet cok keyifliydi.',bd:[{ro:'khui gan sa-nuk maak',tr:'sohbet cok keyifli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'เราคุยภาษาอังกฤษได้ไหมครับ',ro:'rao khui phaa-saa ang-grit dai mai khrap',tr:'Ingilizce konusabilir miyiz?',bd:[{ro:'rao khui phaa-saa ang-grit dai mai',tr:'ingilizce konusabilir miyiz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'รู้จัก',ro:'ruu-jak',tr:'Tanismak',
     tip:'Birini bilmek veya tanimak anlaminda kullanilir.',
     ctx:'Yeni biriyle ilk tanisma cumlelerinde gerekir.',
     examples:[
      {th:'ยินดีที่ได้รู้จักครับ',ro:'yin-dii thii dai ruu-jak khrap',tr:'Tanistigimiza memnun oldum.',bd:[{ro:'yin-dii thii dai ruu-jak',tr:'tanistigimiza memnun oldum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมอยากรู้จักเพื่อนคุณครับ',ro:'pom yaak ruu-jak phuean khun khrap',tr:'Arkadasinizla tanismak isterim.',bd:[{ro:'pom yaak ruu-jak phuean khun',tr:'arkadasinizla tanismak isterim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'เบอร์โทร',ro:'boe-tho',tr:'Numara',
     tip:'Telefon numarasi istemek icin kullanilir.',
     ctx:'Tanismadan sonra iletisim kurmak icin gerekli.',
     examples:[
      {th:'ขอเบอร์โทรได้ไหมครับ',ro:'khor boe-tho dai mai khrap',tr:'Numaranizi alabilir miyim?',bd:[{ro:'khor boe-tho dai mai',tr:'numara alabilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'นี่คือเบอร์โทรผมครับ',ro:'nii khue boe-tho pom khrap',tr:'Bu benim numaram.',bd:[{ro:'nii khue boe-tho pom',tr:'bu benim numaram',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'เจอกัน',ro:'joe-gan',tr:'Bulusmak',
     tip:'Bir yerde gorusmek anlamina gelir.',
     ctx:'Plan yaparken temel fiildir.',
     examples:[
      {th:'พรุ่งนี้เจอกันได้ไหมครับ',ro:'phrung-nii joe-gan dai mai khrap',tr:'Yarin bulusabilir miyiz?',bd:[{ro:'phrung-nii joe-gan dai mai',tr:'yarin bulusabilir miyiz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'เราเจอกันที่ป่าตองครับ',ro:'rao joe-gan thii paa-tong khrap',tr:'Patongda bulusalim.',bd:[{ro:'rao joe-gan thii paa-tong',tr:'patongda bulusalim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'สนุก',ro:'sa-nuk',tr:'Eglence',
     tip:'Eglenceli, keyifli anlamina gelir.',
     ctx:'Etkinlik sonrasinda yorum yaparken sik kullanilir.',
     examples:[
      {th:'เมื่อคืนสนุกมากครับ',ro:'muea-khuen sa-nuk maak khrap',tr:'Dun gece cok eglenceliydi.',bd:[{ro:'muea-khuen sa-nuk maak',tr:'dun gece cok eglenceliydi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'งานนี้ไม่สนุกเลยครับ',ro:'ngaan nii mai sa-nuk loey khrap',tr:'Bu etkinlik hic eglenceli degil.',bd:[{ro:'ngaan nii mai sa-nuk loey',tr:'hic eglenceli degil',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'ของขวัญ',ro:'khong-khwan',tr:'Hediye',
     tip:'Dogum gunu veya ziyaretlerde kullanilan kelime.',
     ctx:'Sosyal nezaket icin faydali ifade.',
     examples:[
      {th:'ผมมีของขวัญเล็กๆ ครับ',ro:'pom mii khong-khwan lek-lek khrap',tr:'Kucuk bir hediyem var.',bd:[{ro:'pom mii khong-khwan lek-lek',tr:'kucuk bir hediyem var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ขอบคุณสำหรับของขวัญครับ',ro:'khop-khun sam-rap khong-khwan khrap',tr:'Hediye icin tesekkurler.',bd:[{ro:'khop-khun sam-rap khong-khwan',tr:'hediye icin tesekkur',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. Davet ve Plan Yapma',
      formula:'PAI + [YER/ETKINLIK] + GAN MAI KHRAP = ... gidelim mi',
      explain:'Arkadaslarla bulusma ve plan yapmada en dogal kalip budur.',
      tips:['pai = gitmek','gan = birlikte','mai = soru eki','phrung-nii = yarin','khuen-nii = bu gece','joe-gan = bulusmak'],
      examples:[
        {th:'ไปปาร์ตี้กันไหมครับ',ro:'pai paa-tee gan mai khrap',tr:'Partiye gidelim mi?',bd:[{ro:'pai paa-tee gan mai',tr:'partiye gidelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไปดื่มเบียร์กันไหมครับ',ro:'pai duem bia gan mai khrap',tr:'Biraya gidelim mi?',bd:[{ro:'pai duem bia gan mai',tr:'biraya gidelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'พรุ่งนี้เจอกันที่กะตะได้ไหมครับ',ro:'phrung-nii joe-gan thii ga-ta dai mai khrap',tr:'Yarin Katada bulusalim mi?',bd:[{ro:'phrung-nii joe-gan thii ga-ta dai mai',tr:'yarin katada bulusalim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'คืนนี้ผมว่างครับ',ro:'khuen-nii pom waang khrap',tr:'Bu gece musaitim.',bd:[{ro:'khuen-nii pom waang',tr:'bu gece musaitim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. Tanisma ve Iletisim',
      formula:'YIN-DII THII DAI + [FIIL] = memnun oldum',
      explain:'Yeni birini tanirken kibar ve sicak iletisim icin kullanilir.',
      tips:['yin-dii = memnuniyet','ruu-jak = tanismak','khor = istemek','boe-tho = numara','line id = line hesabi','tit-tor = iletisim'],
      examples:[
        {th:'ยินดีที่ได้รู้จักครับ',ro:'yin-dii thii dai ruu-jak khrap',tr:'Tanistigimiza memnun oldum.',bd:[{ro:'yin-dii thii dai ruu-jak',tr:'tanistigimiza memnun oldum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ขอเบอร์โทรได้ไหมครับ',ro:'khor boe-tho dai mai khrap',tr:'Numaranizi alabilir miyim?',bd:[{ro:'khor boe-tho dai mai',tr:'numara alabilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'เราคุยกันทางไลน์ได้ไหมครับ',ro:'rao khui gan thaang line dai mai khrap',tr:'Line uzerinden konusabilir miyiz?',bd:[{ro:'rao khui gan thaang line dai mai',tr:'line uzerinden konusabilir miyiz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'นี่คือไลน์ของผมครับ',ro:'nii khue line khong pom khrap',tr:'Bu benim line hesabim.',bd:[{ro:'nii khue line khong pom',tr:'bu benim line hesabim',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Arkadas oldugunu soyle',th:'ผมมีเพื่อนที่ภูเก็ตครับ',ro:'pom mii phuean thii phu-ket khrap',tr:'Phuket te arkadaslarim var.',bd:[{ro:'pom mii phuean thii phu-ket',tr:'phukette arkadasim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Parti var mi sor',th:'คืนนี้มีปาร์ตี้ไหมครับ',ro:'khuen-nii mii paa-tee mai khrap',tr:'Bu gece parti var mi?',bd:[{ro:'khuen-nii mii paa-tee mai',tr:'bu gece parti var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Davet et',th:'ผมขอเชิญคุณมาครับ',ro:'pom khor choen khun maa khrap',tr:'Sizi davet ediyorum.',bd:[{ro:'pom khor choen khun maa',tr:'sizi davet ediyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Biraya cagir',th:'ไปดื่มเบียร์กันไหมครับ',ro:'pai duem bia gan mai khrap',tr:'Biraya gidelim mi?',bd:[{ro:'pai duem bia gan mai',tr:'biraya gidelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Tanisma cumlesi',th:'ยินดีที่ได้รู้จักครับ',ro:'yin-dii thii dai ruu-jak khrap',tr:'Tanistigimiza memnun oldum.',bd:[{ro:'yin-dii thii dai ruu-jak',tr:'tanistigimiza memnun oldum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Numara iste',th:'ขอเบอร์โทรได้ไหมครับ',ro:'khor boe-tho dai mai khrap',tr:'Numaranizi alabilir miyim?',bd:[{ro:'khor boe-tho dai mai',tr:'numara alabilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Bulusma teklif et',th:'พรุ่งนี้เจอกันได้ไหมครับ',ro:'phrung-nii joe-gan dai mai khrap',tr:'Yarin bulusabilir miyiz?',bd:[{ro:'phrung-nii joe-gan dai mai',tr:'yarin bulusabilir miyiz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Hediye ver',th:'ผมมีของขวัญให้ครับ',ro:'pom mii khong-khwan hai khrap',tr:'Size bir hediyem var.',bd:[{ro:'pom mii khong-khwan hai',tr:'hediyem var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🎉 Parti Daveti',
     lines:[
      {s:'Ali',th:'คืนนี้มีปาร์ตี้ที่ป่าตองไหมครับ',ro:'khuen-nii mii paa-tee thii paa-tong mai khrap',tr:'Bu gece Patongda parti var mi?',bd:[{ro:'khuen-nii mii paa-tee thii paa-tong mai',tr:'patongda parti var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'มีค่ะ คุณจะมาด้วยไหมคะ',ro:'mii kha khun ja maa duay mai kha',tr:'Var, siz de gelir misiniz?',bd:[{ro:'khun ja maa duay mai',tr:'siz de gelir misiniz',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ไปครับ ผมขอเชิญเพื่อนอีกคนได้ไหมครับ',ro:'pai khrap pom khor choen phuean iik khon dai mai khrap',tr:'Gelirim, bir arkadas daha davet edebilir miyim?',bd:[{ro:'pom khor choen phuean iik khon dai mai',tr:'bir arkadas daha davet edebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ได้เลยค่ะ ยิ่งเยอะยิ่งสนุก',ro:'dai loey kha ying yoe ying sa-nuk',tr:'Tabii, ne kadar cok kisi o kadar eglence.',bd:[{ro:'ying yoe ying sa-nuk',tr:'ne kadar cok o kadar eglence',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🍺 Biraya Cikma',
     lines:[
      {s:'Ali',th:'ไปดื่มเบียร์กันไหมครับ',ro:'pai duem bia gan mai khrap',tr:'Biraya gidelim mi?',bd:[{ro:'pai duem bia gan mai',tr:'biraya gidelim mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ได้ค่ะ แต่ผมดื่มนิดเดียวค่ะ',ro:'dai kha tae pom duem nit-diao kha',tr:'Olur ama az icerim.',bd:[{ro:'pom duem nit-diao',tr:'az icerim',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ไม่มีปัญหาครับ เราแค่คุยกัน',ro:'mai-mii pan-haa khrap rao khae khui gan',tr:'Sorun yok, sadece sohbet ederiz.',bd:[{ro:'mai-mii pan-haa',tr:'sorun yok',role:'Olumsuz'},{ro:'rao khae khui gan',tr:'sadece sohbet ederiz',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ดีเลยค่ะ เจอกันหนึ่งทุ่มนะคะ',ro:'dii loey kha joe-gan nueng-thum na kha',tr:'Harika, yedide bulusalim.',bd:[{ro:'joe-gan nueng-thum',tr:'yedide bulusalim',role:'Kelime'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
     ]},
    {title:'🤝 Yeni Tanisma',
     lines:[
      {s:'Ali',th:'สวัสดีครับ ผมชื่ออาลี ยินดีที่ได้รู้จักครับ',ro:'sa-wat-dii khrap pom chue ali yin-dii thii dai ruu-jak khrap',tr:'Merhaba ben Ali, tanistigimiza memnun oldum.',bd:[{ro:'pom chue ali',tr:'ben ali',role:'Kelime'},{ro:'yin-dii thii dai ruu-jak',tr:'tanistigimiza memnun oldum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ยินดีเช่นกันค่ะ คุณมาจากไหนคะ',ro:'yin-dii chen-gan kha khun maa jaak nai kha',tr:'Ben de memnun oldum, nerelisiniz?',bd:[{ro:'khun maa jaak nai',tr:'nerelisiniz',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ผมมาจากตุรกีครับ',ro:'pom maa jaak tur-kee khrap',tr:'Turkiyeden geldim.',bd:[{ro:'pom maa jaak tur-kee',tr:'turkiyeden geldim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ขอเบอร์โทรไว้ได้ไหมคะ',ro:'khor boe-tho wai dai mai kha',tr:'Numaranizi kaydedebilir miyim?',bd:[{ro:'khor boe-tho wai dai mai',tr:'numaranizi kaydedebilir miyim',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🎁 Kucuk Hediye',
     lines:[
      {s:'Ali',th:'นี่ครับ ของขวัญเล็กๆ สำหรับคุณ',ro:'nii khrap khong-khwan lek-lek sam-rap khun',tr:'Buyrun, sizin icin kucuk bir hediye.',bd:[{ro:'khong-khwan lek-lek sam-rap khun',tr:'sizin icin kucuk hediye',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ขอบคุณมากค่ะ น่ารักมาก',ro:'khop-khun maak kha naa-rak maak',tr:'Cok tesekkur ederim, cok nazik.',bd:[{ro:'khop-khun maak',tr:'cok tesekkur',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ยินดีครับ ไว้เจอกันอีกนะครับ',ro:'yin-dii khrap wai joe-gan iik na khrap',tr:'Rica ederim, tekrar gorusuruz.',bd:[{ro:'wai joe-gan iik',tr:'tekrar gorusuruz',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'แน่นอนค่ะ',ro:'nae-non kha',tr:'Kesinlikle.',bd:[{ro:'nae-non',tr:'kesinlikle',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'คืนนี้มีปาร์ตี้ไหมครับ',q:'Ne soruluyor?',opts:['Parti var mi','Kira ne kadar','Yagmur yagiyor mu'],c:0},
    {diff:'easy',th:'ไปดื่มเบียร์กันไหมครับ',q:'Ne teklif ediliyor?',opts:['Yemek yemek','Bulusmak','Biraya gitmek'],c:2},
    {diff:'easy',th:'ยินดีที่ได้รู้จักครับ',q:'Bu ifade ne?',opts:['Ozur dileme','Tanisma cumlesi','Siparis cumlesi'],c:1},
    {diff:'medium',th:'ขอเบอร์โทรได้ไหมครับ',q:'Ne isteniyor?',opts:['Adres','Telefon numarasi','Fiyat'],c:1},
    {diff:'medium',th:'พรุ่งนี้เจอกันได้ไหมครับ',q:'Ne soruluyor?',opts:['Bugun bulusma','Yarin bulusma','Parti saati'],c:1},
    {diff:'medium',th:'ผมขอเชิญคุณมาปาร์ตี้ครับ',q:'Konusmaci ne yapiyor?',opts:['Davet ediyor','Reddediyor','Sikayet ediyor'],c:0},
    {diff:'medium',th:'เมื่อคืนสนุกมากครับ',q:'Ne anlatiliyor?',opts:['Dun gece eglenceliydi','Dun gece sikiciydi','Dun gece yagmur vardi'],c:0},
    {diff:'hard',th:'เราคุยกันทางไลน์ได้ไหมครับ',q:'Ne talep ediliyor?',opts:['Yuz yuze gorusme','Line uzerinden sohbet','Telefon kapatma'],c:1},
    {diff:'hard',th:'นี่คือเบอร์โทรผมครับ',q:'Ne veriliyor?',opts:['Adres','Numara','Hediye'],c:1},
    {diff:'hard',th:'ขอบคุณสำหรับของขวัญครับ',q:'Ne icin tesekkur ediyor?',opts:['Davet','Yemek','Hediye'],c:2},
  ],
  quiz:[
    {q:'"phuean" ne demek?',opts:['Komsu','Arkadas','Akraba','Patron'],c:1},
    {q:'"paa-tee" ne demek?',opts:['Parti','Pazar','Plaj','Kafe'],c:0},
    {q:'"choen" ne demek?',opts:['Beklemek','Davet etmek','Reddetmek','Odemek'],c:1},
    {q:'"bia" ne demek?',opts:['Su','Kahve','Bira','Meyve suyu'],c:2},
    {q:'"ruu-jak" ne demek?',opts:['Tanismak','Kosmak','Yuzmek','Uyumak'],c:0},
    {q:'"boe-tho" ne demek?',opts:['Adres','Numara','Saat','Masa'],c:1},
    {q:'"joe-gan" ne demek?',opts:['Bulusmak','Ayrilmak','Davet etmek','Aramak'],c:0},
    {q:'"sa-nuk" ne demek?',opts:['Sikici','Eglence','Yorgun','Sessiz'],c:1},
    {q:'"khong-khwan" ne demek?',opts:['Hediye','Fatura','Bilet','Kart'],c:0},
    {q:'Erkek konusmaci hangi eki kullanir?',opts:['kha','khrap','ja','na'],c:1},
  ],
};

LESSONS[14] = L14;
