// Ders 6 verisi — tayca-v3
// =================== VERİ: DERS 6 — Yol Tarifi ===================
const L6 = {
  tones:[],
  words:[
    {id:'w1',th:'ที่ไหน',ro:'thii-nai',tr:'Nerede / Nereye',tr_en:'Where / Where to',
     tip:'"Thii" = yer, "nai" = hangi. Birleşince "nerede" sorusu.',tip_en:'"Thii" = place, "nai" = which. Together they form a "where" question.',
     ctx:'Her gün lazım. "X yuu thii-nai" = X nerede?',ctx_en:'Used every day. "X yuu thii-nai" = Where is X?',
     examples:[
       {th:'ห้องน้ำอยู่ที่ไหนครับ',ro:'hong-naam yuu thii-nai khrap',tr:'Tuvalet nerede?',tr_en:'Where is the bathroom?',bd:[{ro:'hong-naam',tr:'tuvalet',tr_en:'bathroom',role:'S - Ozne'},{ro:'yuu thii-nai',tr:'nerede',tr_en:'where is',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ร้านอาหารอยู่ที่ไหนครับ',ro:'raan-aa-haan yuu thii-nai khrap',tr:'Restoran nerede?',tr_en:'Where is the restaurant?',bd:[{ro:'raan-aa-haan',tr:'restoran',tr_en:'restaurant',role:'S - Ozne'},{ro:'yuu thii-nai',tr:'nerede',tr_en:'where is',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'สถานีรถไฟอยู่ที่ไหนครับ',ro:'sa-thaa-nii rot-fai yuu thii-nai khrap',tr:'Tren istasyonu nerede?',tr_en:'Where is the train station?',bd:[{ro:'sa-thaa-nii rot-fai',tr:'tren istasyonu',tr_en:'train station',role:'S - Ozne'},{ro:'yuu thii-nai',tr:'nerede',tr_en:'where is',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ที่นี่คือที่ไหนครับ',ro:'thii-nii khue thii-nai khrap',tr:'Burası neresi?',tr_en:'Where is this place?',bd:[{ro:'thii-nii khue',tr:'burası nedir',tr_en:'what is this place',role:'Soru/Olumsuz'},{ro:'thii-nai',tr:'neresi',tr_en:'where',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {id:'w2',th:'ตรงไป',ro:'trong-pai',tr:'Düz git / Düz ilerle',tr_en:'Go straight / Go forward',
     tip:'"Trong" = düz/doğru, "pai" = git. Yön tarifinin temeli.',tip_en:'"Trong" = straight/correct, "pai" = go. The foundation of giving directions.',
     ctx:'Yol tarifi verirken ilk söylenen kelime.',ctx_en:'The first thing said when giving directions.',
     examples:[
       {th:'ตรงไปครับ',ro:'trong-pai khrap',tr:'Düz gidin.',tr_en:'Go straight.',bd:[{ro:'trong-pai',tr:'düz git',tr_en:'go straight',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ตรงไปแล้วเลี้ยวซ้ายครับ',ro:'trong-pai laeo liaw-saai khrap',tr:'Düz gidip sola dönün.',tr_en:'Go straight then turn left.',bd:[{ro:'trong-pai laeo',tr:'düz gidince',tr_en:'after going straight',role:'V - Yuklem'},{ro:'liaw-saai',tr:'sola dön',tr_en:'turn left',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ตรงไปสักครู่ครับ',ro:'trong-pai sak-khru khrap',tr:'Biraz düz gidin.',tr_en:'Go straight for a bit.',bd:[{ro:'trong-pai sak-khru',tr:'biraz düz git',tr_en:'go straight a bit',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {id:'w3',th:'เลี้ยว',ro:'liaw',tr:'Dönmek',tr_en:'To turn',
     tip:'"Liaw sai" = sola dön, "liaw khwa" = sağa dön.',tip_en:'"Liaw sai" = turn left, "liaw khwa" = turn right.',
     ctx:'Yol tarifinin en önemli kelimesi.',ctx_en:'The most important word in giving directions.',
     examples:[
       {th:'เลี้ยวซ้ายครับ',ro:'liaw-saai khrap',tr:'Sola dönün.',tr_en:'Turn left.',bd:[{ro:'liaw-saai',tr:'sola dön',tr_en:'turn left',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'เลี้ยวขวาครับ',ro:'liaw-khwaa khrap',tr:'Sağa dönün.',tr_en:'Turn right.',bd:[{ro:'liaw-khwaa',tr:'sağa dön',tr_en:'turn right',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'เลี้ยวซ้ายที่สี่แยกครับ',ro:'liaw-saai thii sii-yaek khrap',tr:'Kavşakta sola dönün.',tr_en:'Turn left at the intersection.',bd:[{ro:'liaw-saai',tr:'sola dön',tr_en:'turn left',role:'V - Yuklem'},{ro:'thii sii-yaek',tr:'kavşakta',tr_en:'at the intersection',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'เลี้ยวขวาหลังไฟแดงครับ',ro:'liaw-khwaa lang fai-daeng khrap',tr:'Kırmızı ışıktan sonra sağa.',tr_en:'Turn right after the red light.',bd:[{ro:'liaw-khwaa',tr:'sağa dön',tr_en:'turn right',role:'V - Yuklem'},{ro:'lang fai-daeng',tr:'kırmızı ışıktan sonra',tr_en:'after the red light',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {id:'w4',th:'ใกล้',ro:'glai',tr:'Yakın',tr_en:'Near / Close',
     tip:'"Glai" = yakın. "Glai glai" = çok yakın. "Maii glai" = uzak.',tip_en:'"Glai" = near. "Glai glai" = very close. "Mai glai" = far.',
     ctx:'Mesafe sormak ve anlatmak için.',ctx_en:'For asking about and describing distance.',
     examples:[
       {th:'ใกล้ไหมครับ',ro:'glai mai khrap',tr:'Yakın mı?',tr_en:'Is it close?',bd:[{ro:'glai mai',tr:'yakın mı',tr_en:'is it close',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ใกล้มากครับ เดินได้',ro:'glai maak khrap dern dai',tr:'Çok yakın, yürüyebilirsiniz.',tr_en:'Very close, you can walk.',bd:[{ro:'glai maak',tr:'çok yakın',tr_en:'very close',role:'V - Yuklem'},{ro:'dern dai',tr:'yürüyebilir',tr_en:'can walk',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ไม่ไกลครับ',ro:'mai glai khrap',tr:'Uzak değil.',tr_en:'Not far.',bd:[{ro:'mai glai',tr:'uzak değil',tr_en:'not far',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ใกล้ห้างสรรพสินค้าครับ',ro:'glai haang-sap-pa-sin-khaa khrap',tr:'Alışveriş merkezine yakın.',tr_en:'Close to the shopping mall.',bd:[{ro:'glai',tr:'yakın',tr_en:'close to',role:'Kelime'},{ro:'haang-sap-pa-sin-khaa',tr:'alışveriş merkezi',tr_en:'shopping mall',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {id:'w5',th:'ไกล',ro:'glai',tr:'Uzak',tr_en:'Far',
     tip:'Dikkat: Yakın ve uzak aynı romanizasyon "glai" ama farklı tonlar!',tip_en:'Note: Near and far share the romanization "glai" but have different tones!',
     ctx:'Mesafe belirtirken kullanılır.',ctx_en:'Used when indicating distance.',
     examples:[
       {th:'ไกลไหมครับ',ro:'glai mai khrap',tr:'Uzak mı?',tr_en:'Is it far?',bd:[{ro:'glai mai',tr:'uzak mı',tr_en:'is it far',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ไกลมากครับ ต้องนั่งรถ',ro:'glai maak khrap tong nang rot',tr:'Çok uzak, araçla gitmeniz lazım.',tr_en:'Very far, you need to take a vehicle.',bd:[{ro:'glai maak',tr:'çok uzak',tr_en:'very far',role:'V - Yuklem'},{ro:'tong nang rot',tr:'araçla gitmek lazım',tr_en:'need to take a vehicle',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ไกลแค่ไหนครับ',ro:'glai khae-nai khrap',tr:'Ne kadar uzak?',tr_en:'How far is it?',bd:[{ro:'glai khae-nai',tr:'ne kadar uzak',tr_en:'how far',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {id:'w6',th:'ถนน',ro:'tha-non',tr:'Yol / Cadde',tr_en:'Road / Street',
     tip:'"Tha-non" = cadde/ana yol. "Soi" = dar sokak.',tip_en:'"Tha-non" = road/main street. "Soi" = narrow side street.',
     ctx:'Adres verirken en sık geçen kelime.',ctx_en:'The most common word when giving an address.',
     examples:[
       {th:'ถนนนี้ชื่ออะไรครับ',ro:'tha-non-nii chue a-rai khrap',tr:'Bu caddenin adı ne?',tr_en:'What is this street called?',bd:[{ro:'tha-non-nii',tr:'bu cadde',tr_en:'this street',role:'S - Ozne'},{ro:'chue a-rai',tr:'adı ne',tr_en:'what is it called',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'อยู่บนถนนใหญ่ครับ',ro:'yuu bon tha-non yai khrap',tr:'Ana caddede.',tr_en:'On the main road.',bd:[{ro:'yuu bon',tr:'üzerinde',tr_en:'on',role:'Kelime'},{ro:'tha-non yai',tr:'ana cadde',tr_en:'main road',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'เข้าซอยแรกครับ',ro:'khao soi raek khrap',tr:'İlk sokaktan girin.',tr_en:'Enter the first alley.',bd:[{ro:'khao soi raek',tr:'ilk sokaktan gir',tr_en:'enter the first alley',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {id:'w7',th:'แผนที่',ro:'phaen-thii',tr:'Harita',tr_en:'Map',
     tip:'"Phaen-thii" = harita. Google Maps her yerde geçerli.',tip_en:'"Phaen-thii" = map. Google Maps works everywhere.',
     ctx:'Telefonda harita gösterirken bu kelimeyi kullan.',ctx_en:'Use this word when showing a map on your phone.',
     examples:[
       {th:'ดูแผนที่ได้ไหมครับ',ro:'duu phaen-thii dai mai khrap',tr:'Haritaya bakabilir miyim?',tr_en:'Can I look at the map?',bd:[{ro:'duu phaen-thii',tr:'haritaya bak',tr_en:'look at the map',role:'V - Yuklem'},{ro:'dai mai',tr:'olur mu',tr_en:'is it OK',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ผมมีแผนที่ครับ',ro:'pom mii phaen-thii khrap',tr:'Haritam var.',tr_en:'I have a map.',bd:[{ro:'pom mii',tr:'bende var',tr_en:'I have',role:'V - Yuklem'},{ro:'phaen-thii',tr:'harita',tr_en:'map',role:'O - Nesne'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ชี้ให้ดูในแผนที่ได้ไหมครับ',ro:'chii hai duu nai phaen-thii dai mai khrap',tr:'Haritada gösterebilir misiniz?',tr_en:'Can you point it out on the map?',bd:[{ro:'chii hai duu nai phaen-thii',tr:'haritada göster',tr_en:'point it out on the map',role:'V - Yuklem'},{ro:'dai mai',tr:'olur mu',tr_en:'is it OK',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {id:'w8',th:'ข้างๆ',ro:'khaang-khaang',tr:'Yanında / Yanı başında',tr_en:'Next to / Right beside',
     tip:'"Khaang" = yan/taraf. Tekrar edilince "hemen yanında" anlamı güçlenir.',tip_en:'"Khaang" = side/direction. Repeated, it emphasizes "right next to".',
     ctx:'Konum tarif ederken referans noktası göstermek için.',ctx_en:'For pointing out a reference point when describing a location.',
     examples:[
       {th:'อยู่ข้างๆ ร้านสะดวกซื้อครับ',ro:'yuu khaang-khaang raan-sa-duak-sue khrap',tr:'Marketin yanında.',tr_en:'Next to the convenience store.',bd:[{ro:'yuu khaang-khaang',tr:'hemen yanında',tr_en:'right next to',role:'Kelime'},{ro:'raan-sa-duak-sue',tr:'market',tr_en:'convenience store',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'อยู่ข้างหน้าครับ',ro:'yuu khaang-naa khrap',tr:'Önünde.',tr_en:'In front.',bd:[{ro:'yuu khaang-naa',tr:'önünde',tr_en:'in front',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'อยู่ข้างหลังครับ',ro:'yuu khaang-lang khrap',tr:'Arkasında.',tr_en:'Behind.',bd:[{ro:'yuu khaang-lang',tr:'arkasında',tr_en:'behind',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'อยู่ข้างซ้ายครับ',ro:'yuu khaang-saai khrap',tr:'Sol tarafında.',tr_en:'On the left side.',bd:[{ro:'yuu khaang-saai',tr:'sol tarafta',tr_en:'on the left',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {id:'w9',th:'เดิน',ro:'dern',tr:'Yürümek',tr_en:'To walk',
     tip:'"Dern" = yürümek. "Dern pai" = yürüyerek git.',tip_en:'"Dern" = to walk. "Dern pai" = walk there.',
     ctx:'Yakın mesafelerde "yürüyerek gidebilir misiniz" için.',ctx_en:'For short distances: "can you walk there".',
     examples:[
       {th:'เดินได้ไหมครับ',ro:'dern dai mai khrap',tr:'Yürüyebilir miyim?',tr_en:'Can I walk there?',bd:[{ro:'dern dai mai',tr:'yürüyebilir miyim',tr_en:'can I walk',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'เดินสิบนาทีครับ',ro:'dern sip naa-thii khrap',tr:'Yürüyerek 10 dakika.',tr_en:'10 minutes on foot.',bd:[{ro:'dern sip naa-thii',tr:'yürüyerek 10 dakika',tr_en:'10 minutes walking',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'เดินตรงไปครับ',ro:'dern trong-pai khrap',tr:'Düz yürüyün.',tr_en:'Walk straight ahead.',bd:[{ro:'dern trong-pai',tr:'düz yürü',tr_en:'walk straight',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'ไกลเกินไปสำหรับการเดินครับ',ro:'glai koern-pai sam-rap gaan-dern khrap',tr:'Yürümek için çok uzak.',tr_en:'Too far to walk.',bd:[{ro:'glai koern-pai',tr:'çok uzak',tr_en:'too far',role:'V - Yuklem'},{ro:'sam-rap gaan-dern',tr:'yürümek için',tr_en:'for walking',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {id:'w10',th:'ตรงนี้',ro:'trong-nii',tr:'Tam burası / Şu yer',tr_en:'Right here / This exact spot',
     tip:'"Trong" = tam/doğru, "nii" = burada. Haritada işaret ederken.',tip_en:'"Trong" = exact/correct, "nii" = here. Used when pointing on a map.',
     ctx:'Konum paylaşırken veya konumu doğrulamak için.',ctx_en:'For sharing or confirming a location.',
     examples:[
       {th:'ตรงนี้เลยครับ',ro:'trong-nii loey khrap',tr:'Tam burası.',tr_en:'Right here.',bd:[{ro:'trong-nii loey',tr:'tam burası',tr_en:'right here',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'จอดตรงนี้ได้ไหมครับ',ro:'jot trong-nii dai mai khrap',tr:'Tam buraya park edebilir miyim?',tr_en:'Can I park right here?',bd:[{ro:'jot trong-nii',tr:'tam buraya park et',tr_en:'park right here',role:'V - Yuklem'},{ro:'dai mai',tr:'olur mu',tr_en:'is it OK',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {th:'รับผมตรงนี้ได้ไหมครับ',ro:'rap pom trong-nii dai mai khrap',tr:'Beni tam buradan alabilir misiniz?',tr_en:'Can you pick me up right here?',bd:[{ro:'rap pom',tr:'beni al',tr_en:'pick me up',role:'V - Yuklem'},{ro:'trong-nii',tr:'tam buradan',tr_en:'right here',role:'Kelime'},{ro:'dai mai',tr:'olur mu',tr_en:'is it OK',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. Yön İfadeleri: Sola / Sağa / Düz',title_en:'1. Direction Expressions: Left / Right / Straight',
      formula:'LIAW SAI = sola dön | LIAW KHWAA = sağa dön | TRONG PAI = düz git',
      explain:'Yol tarifinin 3 temel komutu. "Laeo" = ...dan sonra bağlacıyla zincirlenir.',explain_en:'The 3 basic direction commands. "Laeo" = then/after that, used to chain commands.',
      tips:['liaw saai = sola dön','liaw khwaa = sağa dön','trong pai = düz git','klab = geri dön','thii sii-yaek = kavşakta','thii traffik = trafik ışığında'],
      tips_en:['liaw saai = turn left','liaw khwaa = turn right','trong pai = go straight','klab = turn back','thii sii-yaek = at the intersection','thii traffik = at the traffic light'],
      examples:[
        {th:'ตรงไปแล้วเลี้ยวซ้ายครับ',ro:'trong-pai laeo liaw-saai khrap',tr:'Düz gidip sola dönün.',tr_en:'Go straight then turn left.',bd:[{ro:'trong-pai laeo',tr:'düz gidince',tr_en:'after going straight',role:'V - Yuklem'},{ro:'liaw-saai',tr:'sola dön',tr_en:'turn left',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
        {th:'เลี้ยวขวาที่สี่แยกครับ',ro:'liaw-khwaa thii sii-yaek khrap',tr:'Kavşakta sağa dönün.',tr_en:'Turn right at the intersection.',bd:[{ro:'liaw-khwaa',tr:'sağa dön',tr_en:'turn right',role:'V - Yuklem'},{ro:'thii sii-yaek',tr:'kavşakta',tr_en:'at the intersection',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
        {th:'ตรงไปสองร้อยเมตรครับ',ro:'trong-pai song-roi met khrap',tr:'200 metre düz gidin.',tr_en:'Go straight for 200 metres.',bd:[{ro:'trong-pai',tr:'düz git',tr_en:'go straight',role:'V - Yuklem'},{ro:'song-roi met',tr:'200 metre',tr_en:'200 metres',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
        {th:'เลี้ยวซ้ายแล้วก็เลี้ยวขวาครับ',ro:'liaw-saai laeo-ko liaw-khwaa khrap',tr:'Sola, sonra sağa dönün.',tr_en:'Turn left, then turn right.',bd:[{ro:'liaw-saai laeo-ko',tr:'soldan sonra',tr_en:'after turning left',role:'V - Yuklem'},{ro:'liaw-khwaa',tr:'sağa dön',tr_en:'turn right',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
      ]
    },
    {
      title:'2. Konum Tarifi: yuu + yer referansı',title_en:'2. Describing Location: yuu + place reference',
      formula:'[YER] + YUU + [REFERANS] + KHAANG = ... yanında/önünde',
      explain:'"Yuu" = var/bulunuyor. Konum tarif ederken referans noktası + yön ekiyle kullanılır.',explain_en:'"Yuu" = is located/exists. Used with a reference point + direction word when describing location.',
      tips:['khaang-naa = önünde','khaang-lang = arkasında','khaang-saai = solunda','khaang-khwaa = sağında','khaang-bon = üzerinde','khaang-laang = altında','tit-gap = bitişiğinde'],
      tips_en:['khaang-naa = in front of','khaang-lang = behind','khaang-saai = to the left of','khaang-khwaa = to the right of','khaang-bon = on top of','khaang-laang = underneath','tit-gap = adjacent to'],
      examples:[
        {th:'อยู่ข้างหน้าธนาคารครับ',ro:'yuu khaang-naa tha-naa-khaan khrap',tr:'Bankanın önünde.',tr_en:'In front of the bank.',bd:[{ro:'yuu khaang-naa',tr:'önünde',tr_en:'in front of',role:'Kelime'},{ro:'tha-naa-khaan',tr:'banka',tr_en:'bank',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
        {th:'อยู่ตรงข้ามเซเว่นครับ',ro:'yuu trong-kham Seven khrap',tr:'Seven-Eleven\'ın karşısında.',tr_en:'Across from 7-Eleven.',bd:[{ro:'yuu trong-kham',tr:'karşısında',tr_en:'across from',role:'Kelime'},{ro:'Seven',tr:'7-Eleven',tr_en:'7-Eleven',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
        {th:'อยู่ติดกับโรงแรมครับ',ro:'yuu tit-gap roong-raem khrap',tr:'Otele bitişik.',tr_en:'Adjacent to the hotel.',bd:[{ro:'yuu tit-gap',tr:'bitişiğinde',tr_en:'adjacent to',role:'Kelime'},{ro:'roong-raem',tr:'otel',tr_en:'hotel',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
        {th:'อยู่ชั้นสองครับ',ro:'yuu chan song khrap',tr:'İkinci katta.',tr_en:'On the second floor.',bd:[{ro:'yuu chan song',tr:'2. katta',tr_en:'on the 2nd floor',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Tuvalet sor',task_en:'Ask for the bathroom',th:'ห้องน้ำอยู่ที่ไหนครับ',ro:'hong-naam yuu thii-nai khrap',tr:'Tuvalet nerede?',tr_en:'Where is the bathroom?',bd:[{ro:'hong-naam yuu thii-nai',tr:'tuvalet nerede',tr_en:'where is the bathroom',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
    {task:'Sola dön',task_en:'Turn left',th:'เลี้ยวซ้ายครับ',ro:'liaw-saai khrap',tr:'Sola dönün.',tr_en:'Turn left.',bd:[{ro:'liaw-saai',tr:'sola dön',tr_en:'turn left',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
    {task:'Sağa dön',task_en:'Turn right',th:'เลี้ยวขวาครับ',ro:'liaw-khwaa khrap',tr:'Sağa dönün.',tr_en:'Turn right.',bd:[{ro:'liaw-khwaa',tr:'sağa dön',tr_en:'turn right',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
    {task:'Yakın mı sor',task_en:'Ask if it is close',th:'ใกล้ไหมครับ',ro:'glai mai khrap',tr:'Yakın mı?',tr_en:'Is it close?',bd:[{ro:'glai mai',tr:'yakın mı',tr_en:'is it close',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
    {task:'Yürüyerek kaç dakika',task_en:'Ask how many minutes on foot',th:'เดินกี่นาทีครับ',ro:'dern kii-naa-thii khrap',tr:'Yürüyerek kaç dakika?',tr_en:'How many minutes walking?',bd:[{ro:'dern kii-naa-thii',tr:'yürüyerek kaç dakika',tr_en:'how many minutes walking',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
    {task:'Haritada göster',task_en:'Show on the map',th:'ชี้ให้ดูในแผนที่ได้ไหมครับ',ro:'chii hai duu nai phaen-thii dai mai khrap',tr:'Haritada gösterebilir misiniz?',tr_en:'Can you point it out on the map?',bd:[{ro:'chii hai duu nai phaen-thii',tr:'haritada göster',tr_en:'point it out on the map',role:'V - Yuklem'},{ro:'dai mai',tr:'olur mu',tr_en:'is it OK',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
    {task:'Düz git sonra sola',task_en:'Go straight then turn left',th:'ตรงไปแล้วเลี้ยวซ้ายครับ',ro:'trong-pai laeo liaw-saai khrap',tr:'Düz gidip sola dönün.',tr_en:'Go straight then turn left.',bd:[{ro:'trong-pai laeo',tr:'düz gidince',tr_en:'after going straight',role:'V - Yuklem'},{ro:'liaw-saai',tr:'sola dön',tr_en:'turn left',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
    {task:'Tam burası de',task_en:'Say right here',th:'ตรงนี้เลยครับ',ro:'trong-nii loey khrap',tr:'Tam burası.',tr_en:'Right here.',bd:[{ro:'trong-nii loey',tr:'tam burası',tr_en:'right here',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🗺️ Otel Arıyor',
     lines:[
       {s:'Ali',th:'ขอโทษครับ โรงแรมนี้อยู่ที่ไหนครับ',ro:'khor-thot khrap roong-raem-nii yuu thii-nai khrap',tr:'Özür dilerim, bu otel nerede?',tr_en:'Excuse me, where is this hotel?',bd:[{ro:'khor-thot',tr:'özür',tr_en:'excuse me',role:'Kelime'},{ro:'roong-raem-nii yuu thii-nai',tr:'bu otel nerede',tr_en:'where is this hotel',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Nada',th:'ตรงไปแล้วเลี้ยวขวาที่สี่แยกค่ะ',ro:'trong-pai laeo liaw-khwaa thii sii-yaek kha',tr:'Düz gidin, kavşakta sağa dönün.',tr_en:'Go straight, then turn right at the intersection.',bd:[{ro:'trong-pai laeo',tr:'düz gidince',tr_en:'after going straight',role:'V - Yuklem'},{ro:'liaw-khwaa thii sii-yaek',tr:'kavşakta sağa',tr_en:'turn right at the intersection',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Ali',th:'ไกลไหมครับ',ro:'glai mai khrap',tr:'Uzak mı?',tr_en:'Is it far?',bd:[{ro:'glai mai',tr:'uzak mı',tr_en:'is it far',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Nada',th:'ไม่ไกลค่ะ เดินห้านาทีค่ะ',ro:'mai glai kha dern haa-naa-thii kha',tr:'Uzak değil, yürüyerek 5 dakika.',tr_en:'Not far, 5 minutes on foot.',bd:[{ro:'mai glai',tr:'uzak değil',tr_en:'not far',role:'Olumsuz'},{ro:'dern haa-naa-thii',tr:'yürüyerek 5 dk',tr_en:'5 minutes walking',role:'Kelime'},{ro:'kha',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {title:'📍 Konumumu Anlatıyorum',
     lines:[
       {s:'Nada',th:'คุณอยู่ที่ไหนคะ',ro:'khun yuu thii-nai kha',tr:'Neredesiniz?',tr_en:'Where are you?',bd:[{ro:'khun yuu thii-nai',tr:'neredesiniz',tr_en:'where are you',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Ali',th:'ผมอยู่หน้าเซเว่นครับ บนถนนใหญ่',ro:'pom yuu naa Seven khrap bon tha-non yai',tr:'Seven-Eleven önündeyim, ana caddede.',tr_en:'I\'m in front of 7-Eleven, on the main road.',bd:[{ro:'pom yuu naa Seven',tr:'Seven önündeyim',tr_en:'I\'m in front of 7-Eleven',role:'Kelime'},{ro:'bon tha-non yai',tr:'ana caddede',tr_en:'on the main road',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Nada',th:'โอเคค่ะ ฉันรู้แล้วค่ะ',ro:'o-kee kha chan ruu laeo kha',tr:'Tamam, biliyorum.',tr_en:'OK, I know where that is.',bd:[{ro:'o-kee',tr:'tamam',tr_en:'OK',role:'Kelime'},{ro:'chan ruu laeo',tr:'biliyorum',tr_en:'I know now',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Ali',th:'ขอบคุณมากครับ',ro:'khob-khun maak khrap',tr:'Çok teşekkürler.',tr_en:'Thank you very much.',bd:[{ro:'khob-khun maak',tr:'çok teşekkür',tr_en:'thank you very much',role:'Kelime'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {title:'🏖️ Plaja Tarif',
     lines:[
       {s:'Ali',th:'ไปหาดป่าตองยังไงครับ',ro:'pai haat paa-tong yang-ngai khrap',tr:'Patong plajına nasıl gidilir?',tr_en:'How do I get to Patong beach?',bd:[{ro:'pai haat paa-tong',tr:'Patong plajına git',tr_en:'go to Patong beach',role:'V - Yuklem'},{ro:'yang-ngai',tr:'nasıl',tr_en:'how',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Nada',th:'นั่งรถสองแถวได้ค่ะ หรือนั่งแท็กซี่',ro:'nang rot-song-thaeo dai kha rue nang taxi',tr:'Songthaew veya taksiyle gidebilirsiniz.',tr_en:'You can go by songthaew or taxi.',bd:[{ro:'nang rot-song-thaeo',tr:'songthaew bin',tr_en:'take a songthaew',role:'Kelime'},{ro:'rue nang taxi',tr:'veya taksiyle',tr_en:'or by taxi',role:'Kelime'},{ro:'kha',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Ali',th:'ราคาเท่าไรครับ',ro:'raa-khaa thao-rai khrap',tr:'Fiyat ne kadar?',tr_en:'How much does it cost?',bd:[{ro:'raa-khaa thao-rai',tr:'fiyat ne kadar',tr_en:'how much does it cost',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Nada',th:'แท็กซี่ประมาณสองร้อยบาทค่ะ',ro:'taxi pra-maan song-roi baht kha',tr:'Taksi yaklaşık 200 Baht.',tr_en:'Taxi is about 200 Baht.',bd:[{ro:'taxi pra-maan',tr:'taksi yaklaşık',tr_en:'taxi about',role:'Kelime'},{ro:'song-roi baht',tr:'200 Baht',tr_en:'200 Baht',role:'Kelime'},{ro:'kha',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
    {title:'🏪 Market Tarifi',
     lines:[
       {s:'Ali',th:'เซเว่นอยู่ที่ไหนครับ',ro:'Seven yuu thii-nai khrap',tr:'Seven-Eleven nerede?',tr_en:'Where is the 7-Eleven?',bd:[{ro:'Seven yuu thii-nai',tr:'Seven nerede',tr_en:'where is 7-Eleven',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Nada',th:'อยู่ข้างๆ นี้เลยค่ะ',ro:'yuu khaang-khaang nii loey kha',tr:'Hemen yanımızda.',tr_en:'Right next to us here.',bd:[{ro:'yuu khaang-khaang nii loey',tr:'hemen burada',tr_en:'right here next to us',role:'Kelime'},{ro:'kha',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Ali',th:'ขอบคุณครับ ใกล้มากเลย',ro:'khob-khun khrap glai maak loey',tr:'Teşekkürler, çok yakınmış.',tr_en:'Thank you, that\'s very close!',bd:[{ro:'khob-khun',tr:'teşekkür',tr_en:'thank you',role:'Kelime'},{ro:'glai maak loey',tr:'çok yakın',tr_en:'so close',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
       {s:'Nada',th:'ยินดีค่ะ',ro:'yin-dee kha',tr:'Rica ederim.',tr_en:'You\'re welcome.',bd:[{ro:'yin-dee',tr:'rica ederim',tr_en:'you\'re welcome',role:'Kelime'},{ro:'kha',tr:'kibar eki',tr_en:'polite particle',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'เลี้ยวซ้ายครับ',q:'Hangi yön?',q_en:'Which direction?',opts:['Sola','Sağa','Düz'],opts_en:['Left','Right','Straight'],c:0},
    {diff:'easy',th:'ตรงไปครับ',q:'Ne yapılacak?',q_en:'What to do?',opts:['Dur','Sola dön','Düz git'],opts_en:['Stop','Turn left','Go straight'],c:2},
    {diff:'easy',th:'ใกล้มากครับ',q:'Mesafe nasıl?',q_en:'How is the distance?',opts:['Çok uzak','Çok yakın','Orta'],opts_en:['Very far','Very close','Medium'],c:1},
    {diff:'medium',th:'เลี้ยวขวาที่สี่แยกครับ',q:'Nerede dönülecek?',q_en:'Where to turn?',opts:['Işıkta','Kavşakta','Sokakta'],opts_en:['At the light','At the intersection','On the street'],c:1},
    {diff:'medium',th:'เดินสิบนาทีครับ',q:'Kaç dakika?',q_en:'How many minutes?',opts:['5 dk','10 dk','15 dk'],opts_en:['5 min','10 min','15 min'],c:1},
    {diff:'medium',th:'อยู่ข้างหน้าธนาคารครับ',q:'Banka ile ilişkisi?',q_en:'Relationship to the bank?',opts:['Arkasında','Yanında','Önünde'],opts_en:['Behind it','Next to it','In front of it'],c:2},
    {diff:'medium',th:'ไกลเกินไปสำหรับการเดินครับ',q:'Ne öneriliyor?',q_en:'What is suggested?',opts:['Yürümek','Araç kullanmak','Beklenmek'],opts_en:['Walking','Using a vehicle','Waiting'],c:1},
    {diff:'hard',th:'ตรงไปแล้วเลี้ยวซ้ายครับ',q:'Doğru sıra?',q_en:'Correct order?',opts:['Sola dön, düz git','Düz git, sola dön','Düz git, sağa dön'],opts_en:['Turn left, go straight','Go straight, turn left','Go straight, turn right'],c:1},
    {diff:'hard',th:'อยู่ตรงข้ามเซเว่นครับ',q:'Konum?',q_en:'Location?',opts:['Seven yanında','Seven önünde','Seven karşısında'],opts_en:['Next to 7-Eleven','In front of 7-Eleven','Across from 7-Eleven'],c:2},
    {diff:'hard',th:'ชี้ให้ดูในแผนที่ได้ไหมครับ',q:'Ne isteniyor?',q_en:'What is being requested?',opts:['Fiyat','Haritada göstermek','Yürüme süresi'],opts_en:['Price','Pointing on the map','Walking time'],c:1},
  ],
  quiz:[
    {q:'"thii-nai" ne demek?',q_en:'What does "thii-nai" mean?',opts:['Burası','Nerede','Orası','Nereden'],opts_en:['Here','Where','There','From where'],c:1},
    {q:'"liaw saai" ne demek?',q_en:'What does "liaw saai" mean?',opts:['Düz git','Sağa dön','Sola dön','Geri dön'],opts_en:['Go straight','Turn right','Turn left','Turn back'],c:2},
    {q:'Sağa dönmek Tayca?',q_en:'How do you say "turn right" in Thai?',opts:['trong-pai','liaw-saai','liaw-khwaa','klab'],opts_en:['trong-pai','liaw-saai','liaw-khwaa','klab'],c:2},
    {q:'"glai" (yakın tonu) ne demek?',q_en:'What does "glai" (near tone) mean?',opts:['Uzak','Yakın','Yavaş','Hızlı'],opts_en:['Far','Near','Slow','Fast'],c:1},
    {q:'"dern" ne demek?',q_en:'What does "dern" mean?',opts:['Koşmak','Uçmak','Yürümek','Gitmek'],opts_en:['To run','To fly','To walk','To go'],c:2},
    {q:'"khaang-naa" ne demek?',q_en:'What does "khaang-naa" mean?',opts:['Arkasında','Yanında','Önünde','Altında'],opts_en:['Behind','Next to','In front of','Under'],c:2},
    {q:'Harita Tayca?',q_en:'How do you say "map" in Thai?',opts:['phaen-thii','phaen-din','rot-fai','sa-thaa-nii'],opts_en:['phaen-thii','phaen-din','rot-fai','sa-thaa-nii'],c:0},
    {q:'"trong-nii" ne demek?',q_en:'What does "trong-nii" mean?',opts:['Düz git','Tam burası','Karşısı','Buradan'],opts_en:['Go straight','Right here','Across from','From here'],c:1},
    {q:'"sii-yaek" ne demek?',q_en:'What does "sii-yaek" mean?',opts:['Sokak','Kavşak','Trafik ışığı','Köprü'],opts_en:['Street','Intersection','Traffic light','Bridge'],c:1},
    {q:'"tit-gap" ne demek?',q_en:'What does "tit-gap" mean?',opts:['Karşısında','Önünde','Bitişiğinde','Arkasında'],opts_en:['Across from','In front of','Adjacent to','Behind'],c:2},
  ],
};

LESSONS[6] = L6;
