// Ders 17 verisi — Tabela ve Menu Okuma
const L17 = {
  tones:[],
  words:[
    {id:'w1',th:'ทางเข้า',ro:'thang-khao',tr:'giris',tip:'AVM, hastane ve plaj girislerinde gorursun.',ctx:'Phuket Central giris kapilarinda.',examples:[{th:'ทางเข้าอยู่ทางซ้ายครับ',ro:'thang-khao yuu thang-saai khrap',tr:'Giris solda.',bd:[{ro:'thang-khao yuu thang-saai',tr:'giris solda',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ผมเข้าทางเข้าหลักครับ',ro:'pom khao thang-khao lak khrap',tr:'Ana giristen giriyorum.',bd:[{ro:'pom khao thang-khao lak',tr:'ana giristen giriyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w2',th:'ทางออก',ro:'thang-ok',tr:'cikis',tip:'Acil cikis ve normal cikis icin kullanilir.',ctx:'Gece pazarinda cikis yonu sorarken.',examples:[{th:'ทางออกอยู่ข้างหน้า',ro:'thang-ok yuu khaang-naa',tr:'Cikis on tarafta.',bd:[{ro:'thang-ok yuu khaang-naa',tr:'cikis onde',role:'V - Yuklem'}]},{th:'ผมหาทางออกไม่เจอครับ',ro:'pom haa thang-ok mai jer khrap',tr:'Cikisi bulamiyorum.',bd:[{ro:'pom haa thang-ok mai jer',tr:'cikisi bulamiyorum',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w3',th:'ห้าม',ro:'haam',tr:'yasak',tip:'Yasak tabelalarinin ana kelimesi.',ctx:'Sigara, park, giris yasagi.',examples:[{th:'ห้ามสูบบุหรี่ครับ',ro:'haam suup bu-rii khrap',tr:'Sigara icmek yasak.',bd:[{ro:'haam suup bu-rii',tr:'sigara yasak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ตรงนี้ห้ามถ่ายรูปครับ',ro:'trong-nii haam thai-ruup khrap',tr:'Burada fotograf yasak.',bd:[{ro:'trong-nii haam thai-ruup',tr:'burada fotograf yasak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w4',th:'เปิด',ro:'poet',tr:'acik',tip:'Dukkan/saat durumu anlatir.',ctx:'Kafe acik mi diye bakarken.',examples:[{th:'ร้านเปิดแล้วครับ',ro:'raan poet laeo khrap',tr:'Dukkan acik.',bd:[{ro:'raan poet laeo',tr:'dukkan acik',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'วันนี้เปิดถึงสี่ทุ่มครับ',ro:'wan-nii poet thueng sii-thum khrap',tr:'Bugun gece 10a kadar acik.',bd:[{ro:'wan-nii poet thueng sii-thum',tr:'bugun 10a kadar acik',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w5',th:'ปิด',ro:'pit',tr:'kapali',tip:'Kapanis veya gecici kapalilik.',ctx:'Yagmurda plaj dukkanlari kapanabilir.',examples:[{th:'ร้านนี้ปิดครับ',ro:'raan-nii pit khrap',tr:'Bu dukkan kapali.',bd:[{ro:'raan-nii pit',tr:'dukkan kapali',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ปิดปรับปรุงครับ',ro:'pit prap-prung khrap',tr:'Tadilat nedeniyle kapali.',bd:[{ro:'pit prap-prung',tr:'tadilat nedeniyle kapali',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w6',th:'ห้องน้ำ',ro:'hong-naam',tr:'tuvalet',tip:'Tabela ve mekan icinde en cok sorulan kelime.',ctx:'AVM ve restoranlarda.',examples:[{th:'ห้องน้ำอยู่ไหนครับ',ro:'hong-naam yuu nai khrap',tr:'Tuvalet nerede?',bd:[{ro:'hong-naam yuu nai',tr:'tuvalet nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ผมขอไปห้องน้ำก่อนครับ',ro:'pom khor bpai hong-naam kon khrap',tr:'Once tuvalete gideyim.',bd:[{ro:'pom khor bpai hong-naam kon',tr:'once tuvalete gideyim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w7',th:'ทางหนีไฟ',ro:'thang-nii-fai',tr:'cikis yolu',tip:'Acil cikis yolu tabelasi.',ctx:'Otel koridorlarinda yesil tabela.',examples:[{th:'ทางหนีไฟอยู่ข้างบันไดครับ',ro:'thang-nii-fai yuu khaang ban-dai khrap',tr:'Acil cikis merdiven yaninda.',bd:[{ro:'thang-nii-fai yuu khaang ban-dai',tr:'acil cikis merdiven yaninda',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'เวลาไฟดับใช้ทางหนีไฟครับ',ro:'wee-laa fai-dap chai thang-nii-fai khrap',tr:'Elektrik kesilince acil cikis yolunu kullanin.',bd:[{ro:'wee-laa fai-dap chai thang-nii-fai',tr:'kesilince acil cikis kullan',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w8',th:'อันตราย',ro:'an-ta-raai',tr:'tehlike',tip:'Tehlikeli bolgeler icin uyaridir.',ctx:'Kayalik plaj ve insaat bolgesi.',examples:[{th:'เขตนี้อันตรายครับ',ro:'khet-nii an-ta-raai khrap',tr:'Bu bolge tehlikeli.',bd:[{ro:'khet-nii an-ta-raai',tr:'bu bolge tehlikeli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ป้ายเขียนว่าอันตรายครับ',ro:'paai khian waa an-ta-raai khrap',tr:'Tabelada tehlike yaziyor.',bd:[{ro:'paai khian waa an-ta-raai',tr:'tabelada tehlike yaziyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w9',th:'รับเงินสดเท่านั้น',ro:'rap ngoen-sot thao-nan',tr:'sadece nakit',tip:'Kart gecmeyen yerlerde olur.',ctx:'Phuket gece pazari ve sokak yiyecegi.',examples:[{th:'ร้านนี้รับเงินสดเท่านั้นครับ',ro:'raan-nii rap ngoen-sot thao-nan khrap',tr:'Bu yer sadece nakit aliyor.',bd:[{ro:'raan-nii rap ngoen-sot thao-nan',tr:'sadece nakit aliyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ผมมีแต่บัตรครับ ทำไงดี',ro:'pom mii tae bat khrap tham-ngai dii',tr:'Sadece kartim var, ne yapayim?',bd:[{ro:'pom mii tae bat',tr:'sadece kartim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {id:'w10',th:'ลดราคา',ro:'lot-raa-khaa',tr:'indirim',tip:'Menu ve vitrinlerde cok gorulur.',ctx:'Patong alisveris bolgesinde.',examples:[{th:'วันนี้ลดราคายี่สิบเปอร์เซ็นต์ครับ',ro:'wan-nii lot-raa-khaa yii-sip per-sen khrap',tr:'Bugun yuzde 20 indirim var.',bd:[{ro:'wan-nii lot-raa-khaa yii-sip per-sen',tr:'bugun yuzde 20 indirim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'เมนูนี้ลดราคาครับ',ro:'menuu nii lot-raa-khaa khrap',tr:'Bu menu urunu indirimde.',bd:[{ro:'menuu nii lot-raa-khaa',tr:'menu urunu indirimde',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
  ],
  grammar:[
    {title:'1. Tabela Okuma Kaliplari',formula:'[YER] + poet/pit | haam + [FIIL]',explain:'Tabela dilinde fiil kisa olur. "haam" ile yasak, "poet/pit" ile acik-kapali belirtilir.',tips:['haam = yasak','poet = acik','pit = kapali','thang-khao = giris','thang-ok = cikis'],examples:[{th:'ทางนี้ห้ามเข้า',ro:'thang-nii haam khao',tr:'Bu yonden giris yasak.',bd:[{ro:'thang-nii haam khao',tr:'bu yonden giris yasak',role:'Olumsuz'}]},{th:'ร้านเปิดครับ',ro:'raan poet khrap',tr:'Dukkan acik.',bd:[{ro:'raan poet',tr:'dukkan acik',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ร้านปิดครับ',ro:'raan pit khrap',tr:'Dukkan kapali.',bd:[{ro:'raan pit',tr:'dukkan kapali',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ห้ามถ่ายรูปครับ',ro:'haam thai-ruup khrap',tr:'Fotograf cekmek yasak.',bd:[{ro:'haam thai-ruup',tr:'fotograf yasak',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
    {title:'2. Menu ve Odeme Ifadeleri',formula:'rap ngoen-sot thao-nan | lot-raa-khaa + [oran]',explain:'Phuket pazar ve sokak lezzetlerinde kart gecmeme ve indirim metinleri cok yaygindir.',tips:['rap ngoen-sot thao-nan = sadece nakit','lot-raa-khaa = indirim','per-sen = yuzde','menuu = menu','khaawp-khun khrap = tesekkur'],examples:[{th:'ร้านนี้รับเงินสดเท่านั้นครับ',ro:'raan-nii rap ngoen-sot thao-nan khrap',tr:'Bu yer sadece nakit aliyor.',bd:[{ro:'raan-nii rap ngoen-sot thao-nan',tr:'sadece nakit aliyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'มีลดราคาไหมครับ',ro:'mii lot-raa-khaa mai khrap',tr:'Indirim var mi?',bd:[{ro:'mii lot-raa-khaa mai',tr:'indirim var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ลดราคาสิบเปอร์เซ็นต์ครับ',ro:'lot-raa-khaa sip per-sen khrap',tr:'Yuzde 10 indirim var.',bd:[{ro:'lot-raa-khaa sip per-sen',tr:'yuzde 10 indirim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},{th:'ผมจ่ายเงินสดครับ',ro:'pom jaai ngoen-sot khrap',tr:'Nakit odeyecegim.',bd:[{ro:'pom jaai ngoen-sot',tr:'nakit odeyecegim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]}]},
  ],
  speaking:[
    {task:'Girisin yerini sor',th:'ทางเข้าอยู่ไหนครับ',ro:'thang-khao yuu nai khrap',tr:'Giris nerede?',bd:[{ro:'thang-khao yuu nai',tr:'giris nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Cikisi bulamadigini soyle',th:'ผมหาทางออกไม่เจอครับ',ro:'pom haa thang-ok mai jer khrap',tr:'Cikisi bulamiyorum.',bd:[{ro:'pom haa thang-ok mai jer',tr:'cikisi bulamiyorum',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Yasak tabelasini oku',th:'ตรงนี้ห้ามสูบบุหรี่ครับ',ro:'trong-nii haam suup bu-rii khrap',tr:'Burada sigara yasak.',bd:[{ro:'trong-nii haam suup bu-rii',tr:'burada sigara yasak',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Acil cikis yolunu sor',th:'ทางหนีไฟอยู่ไหนครับ',ro:'thang-nii-fai yuu nai khrap',tr:'Acil cikis yolu nerede?',bd:[{ro:'thang-nii-fai yuu nai',tr:'acil cikis yolu nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Tuvaleti sor',th:'ห้องน้ำอยู่ไหนครับ',ro:'hong-naam yuu nai khrap',tr:'Tuvalet nerede?',bd:[{ro:'hong-naam yuu nai',tr:'tuvalet nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Nakitle odeyecegini belirt',th:'ผมจ่ายเงินสดครับ',ro:'pom jaai ngoen-sot khrap',tr:'Nakit odeyecegim.',bd:[{ro:'pom jaai ngoen-sot',tr:'nakit odeyecegim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Indirim sor',th:'มีลดราคาไหมครับ',ro:'mii lot-raa-khaa mai khrap',tr:'Indirim var mi?',bd:[{ro:'mii lot-raa-khaa mai',tr:'indirim var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Tehlike uyarisini aktar',th:'เขตนี้อันตรายครับ',ro:'khet-nii an-ta-raai khrap',tr:'Bu bolge tehlikeli.',bd:[{ro:'khet-nii an-ta-raai',tr:'bu bolge tehlikeli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🚪 AVM Giris Cikis',
     lines:[
       {s:'Ali',th:'ผมหาทางเข้าหลักไม่เจอครับ',ro:'pom haa thang-khao lak mai jer khrap',tr:'Ana girisi bulamiyorum.',bd:[{ro:'pom haa thang-khao lak mai jer',tr:'ana girisi bulamiyorum',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ทางเข้าอยู่ชั้นหนึ่งค่ะ',ro:'thang-khao yuu chan nueng kha',tr:'Giris birinci katta.',bd:[{ro:'thang-khao yuu chan nueng',tr:'giris birinci katta',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'แล้วทางออกอยู่ไหนครับ',ro:'laeo thang-ok yuu nai khrap',tr:'Peki cikis nerede?',bd:[{ro:'laeo thang-ok yuu nai',tr:'peki cikis nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ตรงไปแล้วเลี้ยวขวาค่ะ',ro:'trong bpai laeo liaw khwaa kha',tr:'Duz gidip saga donun.',bd:[{ro:'trong bpai laeo liaw khwaa',tr:'duz git saga don',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'⚠️ Phuket Plaj Uyarisi',
     lines:[
       {s:'Ali',th:'ป้ายนี้เขียนว่าอะไรครับ',ro:'paai nii khian waa a-rai khrap',tr:'Bu tabelada ne yaziyor?',bd:[{ro:'paai nii khian waa a-rai',tr:'bu tabelada ne yaziyor',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'เขียนว่าอันตราย ห้ามลงน้ำค่ะ',ro:'khian waa an-ta-raai haam long-naam kha',tr:'Tehlike, denize girmek yasak yaziyor.',bd:[{ro:'khian waa an-ta-raai haam long-naam',tr:'tehlike denize girmek yasak',role:'Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'โอเคครับ ผมจะไม่ลงน้ำ',ro:'o-kee khrap pom ja mai long-naam',tr:'Tamam, denize girmeyecegim.',bd:[{ro:'pom ja mai long-naam',tr:'denize girmeyecegim',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ดีมากค่ะ ปลอดภัยไว้ก่อน',ro:'dii maak kha bplod-phai wai kon',tr:'Cok iyi, once guvenlik.',bd:[{ro:'dii maak',tr:'cok iyi',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'💵 Nakit Menu',
     lines:[
       {s:'Ali',th:'ร้านนี้รับบัตรไหมครับ',ro:'raan-nii rap bat mai khrap',tr:'Burasi kart aliyor mu?',bd:[{ro:'raan-nii rap bat mai',tr:'kart aliyor mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ไม่ค่ะ รับเงินสดเท่านั้น',ro:'mai kha rap ngoen-sot thao-nan',tr:'Hayir, sadece nakit.',bd:[{ro:'mai rap ngoen-sot thao-nan',tr:'sadece nakit',role:'Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'งั้นผมจ่ายเงินสดครับ',ro:'ngan pom jaai ngoen-sot khrap',tr:'O zaman nakit odeyeyim.',bd:[{ro:'ngan pom jaai ngoen-sot',tr:'o zaman nakit odeyeyim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ขอบคุณค่ะ',ro:'khaawp-khun kha',tr:'Tesekkurler.',bd:[{ro:'khaawp-khun',tr:'tesekkurler',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🏷️ Gece Pazari Indirim',
     lines:[
       {s:'Ali',th:'มีลดราคาไหมครับ',ro:'mii lot-raa-khaa mai khrap',tr:'Indirim var mi?',bd:[{ro:'mii lot-raa-khaa mai',tr:'indirim var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'มีค่ะ ลดสิบเปอร์เซ็นต์',ro:'mii kha lot sip per-sen',tr:'Var, yuzde 10 indirim.',bd:[{ro:'lot sip per-sen',tr:'yuzde 10 indirim',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ถ้าผมซื้อสองชิ้น ลดเพิ่มได้ไหมครับ',ro:'thaa pom sue song chin lot phoem dai mai khrap',tr:'Iki tane alirsam daha cok indirim olur mu?',bd:[{ro:'thaa pom sue song chin',tr:'iki tane alirsam',role:'Kelime'},{ro:'lot phoem dai mai',tr:'daha cok indirim olur mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ได้ค่ะ ผมให้สิบห้าเปอร์เซ็นต์',ro:'dai kha pom hai sip-haa per-sen',tr:'Olur, yuzde 15 vereyim.',bd:[{ro:'dai pom hai sip-haa per-sen',tr:'olur yuzde 15',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'ทางเข้าอยู่ทางซ้ายครับ',q:'Neresi solda?',opts:['Cikis','Giris','Tuvalet'],c:1},
    {diff:'easy',th:'ห้องน้ำอยู่ไหนครับ',q:'Ne soruluyor?',opts:['Tuvalet nerede','Menu nerede','Plaj nerede'],c:0},
    {diff:'easy',th:'ร้านนี้ปิดครับ',q:'Dukkan durumu ne?',opts:['Acik','Kapali','Indirimde'],c:1},
    {diff:'medium',th:'ตรงนี้ห้ามถ่ายรูปครับ',q:'Ne yasak?',opts:['Yemek yemek','Fotograf cekmek','Yuruyus'],c:1},
    {diff:'medium',th:'ร้านนี้รับเงินสดเท่านั้นครับ',q:'Odeme sekli ne?',opts:['Sadece kart','Sadece nakit','Havale'],c:1},
    {diff:'medium',th:'มีลดราคายี่สิบเปอร์เซ็นต์ครับ',q:'Ne kadar indirim var?',opts:['%10','%20','%30'],c:1},
    {diff:'medium',th:'ทางหนีไฟอยู่ข้างบันไดครับ',q:'Acil cikis nerede?',opts:['Asansor yani','Merdiven yani','Disarida'],c:1},
    {diff:'hard',th:'ผมหาทางออกไม่เจอครับ',q:'Konusan ne diyor?',opts:['Cikisi buldu','Cikisi bulamadi','Giris kapali'],c:1},
    {diff:'hard',th:'เขียนว่าอันตราย ห้ามลงน้ำค่ะ',q:'Mesaj ne?',opts:['Denize girilebilir','Denize girmek yasak','Plaj kapandi'],c:1},
    {diff:'hard',th:'ถ้าซื้อสองชิ้น ลดเพิ่มได้ไหมครับ',q:'Ne isteniyor?',opts:['Iki urun iadesi','Ek indirim','Kartla odeme'],c:1},
  ],
  quiz:[
    {q:'"thang-khao" ne demek?',opts:['Cikis','Giris','Asansor','Kapi'],c:1},
    {q:'"thang-ok" ne demek?',opts:['Koridor','Cikis','Menu','Yol'],c:1},
    {q:'"haam" ne demek?',opts:['Izin','Yasak','Acil','Tehlike'],c:1},
    {q:'"poet" ne demek?',opts:['Acik','Kapali','Ucuz','Pahali'],c:0},
    {q:'"pit" ne demek?',opts:['Acik','Erken','Kapali','Yavas'],c:2},
    {q:'"hong-naam" ne demek?',opts:['Mutfak','Tuvalet','Depo','Oda'],c:1},
    {q:'"thang-nii-fai" ne demek?',opts:['Otopark','Acil cikis yolu','Servis girisi','Deniz yolu'],c:1},
    {q:'"an-ta-raai" ne demek?',opts:['Guvenli','Tehlike','Temiz','Sessiz'],c:1},
    {q:'"rap ngoen-sot thao-nan" ne demek?',opts:['Sadece kart','Sadece nakit','Indirim yok','Servis ucreti'],c:1},
    {q:'"lot-raa-khaa" ne demek?',opts:['Fiyat artisi','Iade','Indirim','Pazarlik'],c:2},
  ],
};

LESSONS[17] = L17;
