// Ders 13 verisi — tayca-v3
// =================== VERİ: DERS 13 — Ev Yasami ve Internet ===================
const L13 = {
  tones:[],
  words:[
    {id:'w1',th:'บ้าน',ro:'baan',tr:'Ev',
     tip:'Gundelik hayatta en temel kelimelerden biri.',
     ctx:'Phuket te ev ararken surekli kullanilir.',
     examples:[
      {th:'ผมหาบ้านเช่าอยู่ครับ',ro:'pom haa baan chao yuu khrap',tr:'Kiralik ev ariyorum.',bd:[{ro:'pom haa baan chao yuu',tr:'ev ariyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'บ้านนี้เงียบดีครับ',ro:'baan nii ngiap dii khrap',tr:'Bu ev sakin ve iyi.',bd:[{ro:'baan nii ngiap dii',tr:'bu ev sakin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'บ้านอยู่ใกล้ทะเลไหมครับ',ro:'baan yuu glai tha-lee mai khrap',tr:'Ev denize yakin mi?',bd:[{ro:'baan yuu glai tha-lee mai',tr:'ev denize yakin mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'ค่าเช่า',ro:'khaa-chao',tr:'Kira',
     tip:'Aylik odeme icin kullanilir.',
     ctx:'Ev veya oda gorusmelerinde gerekli kelime.',
     examples:[
      {th:'ค่าเช่าเดือนละเท่าไรครับ',ro:'khaa-chao deuan-la thao-rai khrap',tr:'Aylik kira ne kadar?',bd:[{ro:'khaa-chao deuan-la thao-rai',tr:'aylik kira ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ค่าเช่ารวมค่าน้ำไหมครับ',ro:'khaa-chao ruam khaa naam mai khrap',tr:'Kiraya su dahil mi?',bd:[{ro:'khaa-chao ruam khaa naam mai',tr:'kiraya su dahil mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'อินเทอร์เน็ต',ro:'in-thoe-net',tr:'Internet',
     tip:'Apartman ilanlarinda sikca yazar.',
     ctx:'Uzaktan calisanlar icin kritik konu.',
     examples:[
      {th:'มีอินเทอร์เน็ตไหมครับ',ro:'mii in-thoe-net mai khrap',tr:'Internet var mi?',bd:[{ro:'mii in-thoe-net mai',tr:'internet var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'อินเทอร์เน็ตเร็วไหมครับ',ro:'in-thoe-net reo mai khrap',tr:'Internet hizli mi?',bd:[{ro:'in-thoe-net reo mai',tr:'internet hizli mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'รหัสไวไฟ',ro:'ra-hat wai-fai',tr:'Wifi sifresi',
     tip:'Kafe ve apartmanlarda en cok sorulan soru.',
     ctx:'Check in sonrasinda ilk gereken bilgi.',
     examples:[
      {th:'ขอรหัสไวไฟหน่อยครับ',ro:'khor ra-hat wai-fai noi khrap',tr:'Wifi sifresini alabilir miyim?',bd:[{ro:'khor ra-hat wai-fai noi',tr:'wifi sifresini iste',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'รหัสไวไฟเปลี่ยนหรือยังครับ',ro:'ra-hat wai-fai plian rue-yang khrap',tr:'Wifi sifresi degisti mi?',bd:[{ro:'ra-hat wai-fai plian rue-yang',tr:'wifi sifresi degisti mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'ไฟฟ้า',ro:'fai-faa',tr:'Elektrik',
     tip:'Faturada ayri yazilir.',
     ctx:'Klima kullaniminda elektrik maliyeti artar.',
     examples:[
      {th:'ค่าไฟฟ้าเดือนนี้แพงครับ',ro:'khaa fai-faa deuan nii phaeng khrap',tr:'Bu ay elektrik pahali.',bd:[{ro:'khaa fai-faa deuan nii phaeng',tr:'bu ay elektrik pahali',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ไฟฟ้าดับอีกแล้วครับ',ro:'fai-faa dap iik-laeo khrap',tr:'Elektrik yine kesildi.',bd:[{ro:'fai-faa dap iik-laeo',tr:'elektrik yine kesildi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'น้ำประปา',ro:'naam pra-paa',tr:'Su',
     tip:'Evdeki musluk suyu icin kullanilir.',
     ctx:'Fatura ve tesisat konularinda gerekli.',
     examples:[
      {th:'ค่าน้ำประปาเท่าไรครับ',ro:'khaa naam pra-paa thao-rai khrap',tr:'Su faturasi ne kadar?',bd:[{ro:'khaa naam pra-paa thao-rai',tr:'su faturasi ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'น้ำประปาไม่ไหลครับ',ro:'naam pra-paa mai lai khrap',tr:'Su akmiyor.',bd:[{ro:'naam pra-paa mai lai',tr:'su akmiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'ช่าง',ro:'chang',tr:'Tamirci',
     tip:'Elektrikci, tesisatci gibi ustalar icin genel kelime.',
     ctx:'Evde sorun oldugunda ilk aranacak kisi.',
     examples:[
      {th:'เรียกช่างได้ไหมครับ',ro:'riak chang dai mai khrap',tr:'Tamirci cagirabilir miyiz?',bd:[{ro:'riak chang dai mai',tr:'tamirci cagirabilir miyiz',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ช่างจะมาบ่ายนี้ครับ',ro:'chang ja maa baai nii khrap',tr:'Tamirci bu ogleden sonra gelecek.',bd:[{ro:'chang ja maa baai nii',tr:'tamirci ogleden sonra gelecek',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'เพื่อนบ้าน',ro:'phuean-baan',tr:'Komsu',
     tip:'Ayni bina veya sokakta yasayan kisi.',
     ctx:'Kisa selamlasmalarda kullanilir.',
     examples:[
      {th:'เพื่อนบ้านใจดีมากครับ',ro:'phuean-baan jai dii maak khrap',tr:'Komsum cok iyi biri.',bd:[{ro:'phuean-baan jai dii maak',tr:'komsu cok iyi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมคุยกับเพื่อนบ้านแล้วครับ',ro:'pom khui gap phuean-baan laeo khrap',tr:'Komsumla konustum.',bd:[{ro:'pom khui gap phuean-baan laeo',tr:'komsu ile konustum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'กุญแจ',ro:'gun-jae',tr:'Anahtar',
     tip:'Ev, oda ve motosiklet anahtari icin ayni kelime.',
     ctx:'Check in veya kayip durumunda gerekli.',
     examples:[
      {th:'ผมลืมกุญแจไว้ในห้องครับ',ro:'pom luem gun-jae wai nai hong khrap',tr:'Anahtari odada unuttum.',bd:[{ro:'pom luem gun-jae wai nai hong',tr:'anahtari odada unuttum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'มีกุญแจสำรองไหมครับ',ro:'mii gun-jae sam-rong mai khrap',tr:'Yedek anahtar var mi?',bd:[{ro:'mii gun-jae sam-rong mai',tr:'yedek anahtar var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'ความสะอาด',ro:'khwaam-sa-at',tr:'Temizlik',
     tip:'Ev kurallari ve bina yonetiminde sik gecer.',
     ctx:'Ev tesliminde temizlik kontrol edilir.',
     examples:[
      {th:'ห้องนี้ความสะอาดดีครับ',ro:'hong nii khwaam-sa-at dii khrap',tr:'Bu odanin temizligi iyi.',bd:[{ro:'hong nii khwaam-sa-at dii',tr:'oda temizligi iyi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมต้องการบริการทำความสะอาดครับ',ro:'pom tong-gaan bo-ri-gaan tham-khwaam-sa-at khrap',tr:'Temizlik hizmeti istiyorum.',bd:[{ro:'pom tong-gaan bo-ri-gaan tham-khwaam-sa-at',tr:'temizlik hizmeti istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. Ev Kiralama Sorulari',
      formula:'MII + [SEY] + MAI KHRAP = ... var mi',
      explain:'Ev bakarken internet, su ve elektrik dahil mi sorulari bu kalipla kurulur.',
      tips:['mii = var','mai = soru eki','ruam = dahil','deuan-la = aylik','phaeng = pahali','thuuk = ucuz'],
      examples:[
        {th:'มีอินเทอร์เน็ตไหมครับ',ro:'mii in-thoe-net mai khrap',tr:'Internet var mi?',bd:[{ro:'mii in-thoe-net mai',tr:'internet var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ค่าเช่ารวมค่าไฟไหมครับ',ro:'khaa-chao ruam khaa fai mai khrap',tr:'Kiraya elektrik dahil mi?',bd:[{ro:'khaa-chao ruam khaa fai mai',tr:'kiraya elektrik dahil mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'มีกุญแจสำรองไหมครับ',ro:'mii gun-jae sam-rong mai khrap',tr:'Yedek anahtar var mi?',bd:[{ro:'mii gun-jae sam-rong mai',tr:'yedek anahtar var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ช่างมาวันนี้ไหมครับ',ro:'chang maa wan-nii mai khrap',tr:'Tamirci bugun gelecek mi?',bd:[{ro:'chang maa wan-nii mai',tr:'tamirci bugun gelecek mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. Evde Sorun Bildirme',
      formula:'[SEY] + MAI + [FIIL] = ... olmuyor',
      explain:'Evde teknik sorunlari kisa ve net sekilde bildirmek icin kullanilir.',
      tips:['mai = olumsuz','lai = akmak','dap = kesilmek','riak = cagir','duay = lutfen','diao-nii = hemen'],
      examples:[
        {th:'น้ำประปาไม่ไหลครับ',ro:'naam pra-paa mai lai khrap',tr:'Su akmiyor.',bd:[{ro:'naam pra-paa mai lai',tr:'su akmiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ไฟฟ้าไม่ติดครับ',ro:'fai-faa mai tit khrap',tr:'Elektrik calismiyor.',bd:[{ro:'fai-faa mai tit',tr:'elektrik calismiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ช่วยเรียกช่างให้หน่อยครับ',ro:'chuay riak chang hai noi khrap',tr:'Lutfen tamirci cagirir misiniz?',bd:[{ro:'chuay riak chang hai noi',tr:'lutfen tamirci cagir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมต้องการแก้ไขด่วนครับ',ro:'pom tong-gaan gae-khai duan khrap',tr:'Acil cozum istiyorum.',bd:[{ro:'pom tong-gaan gae-khai duan',tr:'acil cozum istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Kiralik ev sor',th:'ผมหาบ้านเช่าอยู่ครับ',ro:'pom haa baan chao yuu khrap',tr:'Kiralik ev ariyorum.',bd:[{ro:'pom haa baan chao yuu',tr:'ev ariyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Aylik kira sor',th:'ค่าเช่าเดือนละเท่าไรครับ',ro:'khaa-chao deuan-la thao-rai khrap',tr:'Aylik kira ne kadar?',bd:[{ro:'khaa-chao deuan-la thao-rai',tr:'aylik kira ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Internet var mi sor',th:'มีอินเทอร์เน็ตไหมครับ',ro:'mii in-thoe-net mai khrap',tr:'Internet var mi?',bd:[{ro:'mii in-thoe-net mai',tr:'internet var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Wifi sifresi iste',th:'ขอรหัสไวไฟหน่อยครับ',ro:'khor ra-hat wai-fai noi khrap',tr:'Wifi sifresini alabilir miyim?',bd:[{ro:'khor ra-hat wai-fai noi',tr:'wifi sifresi iste',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Elektrik sorunu bildir',th:'ไฟฟ้าดับครับ',ro:'fai-faa dap khrap',tr:'Elektrik kesildi.',bd:[{ro:'fai-faa dap',tr:'elektrik kesildi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Su sorunu bildir',th:'น้ำประปาไม่ไหลครับ',ro:'naam pra-paa mai lai khrap',tr:'Su akmiyor.',bd:[{ro:'naam pra-paa mai lai',tr:'su akmiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Tamirci cagir',th:'ช่วยเรียกช่างให้หน่อยครับ',ro:'chuay riak chang hai noi khrap',tr:'Lutfen tamirci cagirir misiniz?',bd:[{ro:'chuay riak chang hai noi',tr:'tamirci cagir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Yedek anahtar sor',th:'มีกุญแจสำรองไหมครับ',ro:'mii gun-jae sam-rong mai khrap',tr:'Yedek anahtar var mi?',bd:[{ro:'mii gun-jae sam-rong mai',tr:'yedek anahtar var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🏠 Ev Gorusmesi',
     lines:[
      {s:'Ali',th:'สวัสดีครับ ผมหาบ้านเช่าอยู่ครับ',ro:'sa-wat-dii khrap pom haa baan chao yuu khrap',tr:'Merhaba, kiralik ev ariyorum.',bd:[{ro:'pom haa baan chao yuu',tr:'ev ariyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ได้ค่ะ ค่าเช่าเดือนละแปดพันบาทค่ะ',ro:'dai kha khaa-chao deuan-la paet-phan baht kha',tr:'Olur, aylik kira 8000 Baht.',bd:[{ro:'khaa-chao deuan-la paet-phan baht',tr:'aylik kira 8000',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'รวมค่าไฟฟ้าและน้ำไหมครับ',ro:'ruam khaa fai-faa lae naam mai khrap',tr:'Elektrik ve su dahil mi?',bd:[{ro:'ruam khaa fai-faa lae naam mai',tr:'elektrik su dahil mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ไม่รวมค่ะ แต่มีอินเทอร์เน็ตค่ะ',ro:'mai ruam kha tae mii in-thoe-net kha',tr:'Dahil degil ama internet var.',bd:[{ro:'mai ruam',tr:'dahil degil',role:'Olumsuz'},{ro:'mii in-thoe-net',tr:'internet var',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'📶 Wifi Sifresi',
     lines:[
      {s:'Ali',th:'ขอรหัสไวไฟหน่อยครับ',ro:'khor ra-hat wai-fai noi khrap',tr:'Wifi sifresini alabilir miyim?',bd:[{ro:'khor ra-hat wai-fai noi',tr:'wifi sifresi iste',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ได้ค่ะ รหัสคือ phuket2026 ค่ะ',ro:'dai kha ra-hat khue phuket2026 kha',tr:'Tabii, sifre phuket2026.',bd:[{ro:'ra-hat khue phuket2026',tr:'sifre phuket2026',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ขอบคุณครับ อินเทอร์เน็ตเร็วมากครับ',ro:'khop-khun khrap in-thoe-net reo maak khrap',tr:'Tesekkurler, internet cok hizli.',bd:[{ro:'in-thoe-net reo maak',tr:'internet cok hizli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ยินดีค่ะ',ro:'yin-dii kha',tr:'Rica ederim.',bd:[{ro:'yin-dii',tr:'rica ederim',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🔧 Evde Ariza',
     lines:[
      {s:'Ali',th:'ไฟฟ้าดับครับ แล้วน้ำก็ไม่ไหลครับ',ro:'fai-faa dap khrap laeo naam go mai lai khrap',tr:'Elektrik kesildi ve su akmiyor.',bd:[{ro:'fai-faa dap',tr:'elektrik kesildi',role:'V - Yuklem'},{ro:'naam go mai lai',tr:'su da akmiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ขอโทษค่ะ เดี๋ยวเรียกช่างให้นะคะ',ro:'khor-thot kha diao riak chang hai na kha',tr:'Ozur dilerim, hemen tamirci cagiriyorum.',bd:[{ro:'diao riak chang hai',tr:'hemen tamirci cagir',role:'V - Yuklem'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
      {s:'Ali',th:'ช่างจะมากี่โมงครับ',ro:'chang ja maa gii-moong khrap',tr:'Tamirci saat kacta gelir?',bd:[{ro:'chang ja maa gii-moong',tr:'tamirci kacta gelir',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ประมาณบ่ายสามค่ะ',ro:'pra-maan baai saam kha',tr:'Yaklasik ucte gelir.',bd:[{ro:'pra-maan baai saam',tr:'yaklasik ucte',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🧹 Temizlik Gunu',
     lines:[
      {s:'Ali',th:'พรุ่งนี้มีทำความสะอาดไหมครับ',ro:'phrung-nii mii tham-khwaam-sa-at mai khrap',tr:'Yarin temizlik var mi?',bd:[{ro:'mii tham-khwaam-sa-at mai',tr:'temizlik var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'มีค่ะ ตอนเช้าเก้าโมงค่ะ',ro:'mii kha ton-chao kao-moong kha',tr:'Var, sabah dokuzda.',bd:[{ro:'ton-chao kao-moong',tr:'sabah dokuz',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'โอเคครับ ผมจะอยู่บ้านครับ',ro:'o-kee khrap pom ja yuu baan khrap',tr:'Tamam, evde olacagim.',bd:[{ro:'pom ja yuu baan',tr:'evde olacagim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ขอบคุณค่ะ',ro:'khop-khun kha',tr:'Tesekkurler.',bd:[{ro:'khop-khun',tr:'tesekkurler',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'มีอินเทอร์เน็ตไหมครับ',q:'Ne soruluyor?',opts:['Internet var mi','Kira ne kadar','Komsu kim'],c:0},
    {diff:'easy',th:'ขอรหัสไวไฟหน่อยครับ',q:'Ne isteniyor?',opts:['Su faturasi','Wifi sifresi','Tamirci numarasi'],c:1},
    {diff:'easy',th:'ไฟฟ้าดับครับ',q:'Ne oldu?',opts:['Su kesildi','Internet gitti','Elektrik kesildi'],c:2},
    {diff:'medium',th:'น้ำประปาไม่ไหลครับ',q:'Sorun ne?',opts:['Su akmiyor','Kapi acilmiyor','Kira yuksek'],c:0},
    {diff:'medium',th:'ช่วยเรียกช่างให้หน่อยครับ',q:'Ne talep ediliyor?',opts:['Fatura odeme','Tamirci cagirma','Yeni anahtar'],c:1},
    {diff:'medium',th:'ค่าเช่าเดือนละเท่าไรครับ',q:'Ne soruluyor?',opts:['Gunluk fiyat','Aylik kira','Depozito'],c:1},
    {diff:'medium',th:'มีกุญแจสำรองไหมครับ',q:'Ne araniyor?',opts:['Yedek anahtar','Internet paketi','Temizlik gunu'],c:0},
    {diff:'hard',th:'ค่าเช่ารวมค่าไฟไหมครับ',q:'Ne soruluyor?',opts:['Elektrik dahil mi','Su ne kadar','Komsu nerede'],c:0},
    {diff:'hard',th:'ผมต้องการบริการทำความสะอาดครับ',q:'Ne istiyor?',opts:['Tasima hizmeti','Temizlik hizmeti','Tamir hizmeti'],c:1},
    {diff:'hard',th:'ผมหาบ้านเช่าอยู่ครับ',q:'Konusmaci ne yapiyor?',opts:['Ev satiyor','Ev ariyor','Otelde kaliyor'],c:1},
  ],
  quiz:[
    {q:'"baan" ne demek?',opts:['Komsu','Ev','Anahtar','Tamirci'],c:1},
    {q:'"khaa-chao" ne demek?',opts:['Elektrik','Kira','Depozito','Temizlik'],c:1},
    {q:'"in-thoe-net" ne demek?',opts:['Internet','Telefon','Televizyon','Router'],c:0},
    {q:'"ra-hat wai-fai" ne demek?',opts:['Wifi sifresi','Kapici kodu','Ehliyet no','Daire numarasi'],c:0},
    {q:'"fai-faa dap" ne demek?',opts:['Su geldi','Elektrik kesildi','Wifi baglandi','Kapi acildi'],c:1},
    {q:'"naam pra-paa mai lai" ne demek?',opts:['Su akiyor','Su akmiyor','Su temiz','Su pahali'],c:1},
    {q:'"chang" ne demek?',opts:['Komsu','Tamirci','Ev sahibi','Guvenlik'],c:1},
    {q:'"gun-jae" ne demek?',opts:['Anahtar','Kilidi','Kapi','Pencere'],c:0},
    {q:'"khwaam-sa-at" ne demek?',opts:['Temizlik','Kirli','Gurultu','Sessizlik'],c:0},
    {q:'Erkek nezaket eki hangisi?',opts:['kha','khrap','na','mai'],c:1},
  ],
};

LESSONS[13] = L13;
