// Ders 10 verisi — tayca-v3
// =================== VERI: DERS 10 — Plaj ve Deniz ===================
const L10 = {
  tones:[],
  words:[
    {id:'w1',th:'ชายหาด',ro:'chaai-haat',tr:'Plaj',
     tip:'Phukette Patong ve Karon en bilinen plajlar.',
     ctx:'Sabah erken saatlerde plaj daha sakin olur.',
     examples:[
       {th:'ผมอยู่ที่ชายหาดป่าตองครับ',ro:'pom yuu thii chaai-haat Pa-tong khrap',tr:'Patong plajindayim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu thii chaai-haat Pa-tong',tr:'Patong plajinda',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ชายหาดกะรนสวยมากครับ',ro:'chaai-haat Ka-ron suay maak khrap',tr:'Karon plaji cok guzel.',bd:[{ro:'chaai-haat Ka-ron',tr:'Karon plaji',role:'S - Ozne'},{ro:'suay maak',tr:'cok guzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไปชายหาดตอนเย็นกันครับ',ro:'bpai chaai-haat ton yen gan khrap',tr:'Aksam plaja gidelim.',bd:[{ro:'bpai chaai-haat',tr:'plaja gitmek',role:'V - Yuklem'},{ro:'ton yen',tr:'aksam',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ชายหาดนี้คนเยอะไหมครับ',ro:'chaai-haat nii khon yoe mai khrap',tr:'Bu plaj kalabalik mi?',bd:[{ro:'chaai-haat nii',tr:'bu plaj',role:'S - Ozne'},{ro:'khon yoe mai',tr:'kalabalik mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'ทะเล',ro:'tha-lay',tr:'Deniz',
     tip:'Talay sesi Phuket gunluk konusmada cok duyulur.',
     ctx:'Deniz durumu icin dalga ve ruzgar sorulur.',
     examples:[
       {th:'วันนี้ทะเลสวยครับ',ro:'wan-nii tha-lay suay khrap',tr:'Bugun deniz guzel.',bd:[{ro:'wan-nii',tr:'bugun',role:'Zaman'},{ro:'tha-lay suay',tr:'deniz guzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ทะเลแรงไหมครับ',ro:'tha-lay raeng mai khrap',tr:'Deniz sert mi?',bd:[{ro:'tha-lay',tr:'deniz',role:'S - Ozne'},{ro:'raeng mai',tr:'sert mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมชอบทะเลภูเก็ตครับ',ro:'pom chop tha-lay Phu-ket khrap',tr:'Phuket denizini seviyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'chop tha-lay Phu-ket',tr:'Phuket denizini severim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'ว่ายน้ำ',ro:'waai-naam',tr:'Yuzmek',
     tip:'Waai naam temel fiildir ve plajda cok kullanilir.',
     ctx:'Cankurtaran uyarilarinda yuzmek yasak denebilir.',
     examples:[
       {th:'ผมว่ายน้ำได้ครับ',ro:'pom waai-naam dai khrap',tr:'Yuzebiliyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'waai-naam dai',tr:'yuzebilirim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ตรงนี้ว่ายน้ำได้ไหมครับ',ro:'trong-nii waai-naam dai mai khrap',tr:'Burada yuzebilir miyim?',bd:[{ro:'trong-nii',tr:'burada',role:'Yer'},{ro:'waai-naam dai mai',tr:'yuzebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'วันนี้คลื่นแรง ไม่ว่ายน้ำครับ',ro:'wan-nii khluen raeng mai waai-naam khrap',tr:'Bugun dalga guclu, yuzmuyorum.',bd:[{ro:'wan-nii khluen raeng',tr:'bugun dalga guclu',role:'Durum'},{ro:'mai waai-naam',tr:'yuzmuyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมว่ายน้ำกับเพื่อนครับ',ro:'pom waai-naam gap phuean khrap',tr:'Arkadasimla yuzuyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'waai-naam gap phuean',tr:'arkadasla yuzmek',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'ครีมกันแดด',ro:'khriim gan-daet',tr:'Gunes kremi',
     tip:'Tayland gunesinde her gun gunes kremi onemlidir.',
     ctx:'Eczane ve markette SPF sorarak alirsin.',
     examples:[
       {th:'มีครีมกันแดดไหมครับ',ro:'mii khriim gan-daet mai khrap',tr:'Gunes kremi var mi?',bd:[{ro:'mii khriim gan-daet mai',tr:'gunes kremi var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมใช้ครีมกันแดด SPF 50 ครับ',ro:'pom chai khriim gan-daet SPF haa-sip khrap',tr:'SPF 50 gunes kremi kullaniyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'chai khriim gan-daet SPF haa-sip',tr:'SPF 50 kullanmak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ทาครีมกันแดดก่อนลงทะเลครับ',ro:'thaa khriim gan-daet gon long tha-lay khrap',tr:'Denize girmeden once gunes kremi sur.',bd:[{ro:'thaa khriim gan-daet',tr:'gunes kremi surmek',role:'V - Yuklem'},{ro:'gon long tha-lay',tr:'denize inmeden once',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'สน็อกเกิล',ro:'sa-nok-goen',tr:'Snorkel',
     tip:'Ingilizce snorkel kelimesinden gelir.',
     ctx:'Phi Phi ve Karon yakininda snorkel turlari var.',
     examples:[
       {th:'ผมอยากเล่นสน็อกเกิลครับ',ro:'pom yaak len sa-nok-goen khrap',tr:'Snorkel yapmak istiyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yaak len sa-nok-goen',tr:'snorkel yapmak istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'มีหน้ากากสน็อกเกิลให้เช่าไหมครับ',ro:'mii naa-gaak sa-nok-goen hai chao mai khrap',tr:'Snorkel maskesi kiralik var mi?',bd:[{ro:'mii naa-gaak sa-nok-goen',tr:'snorkel maskesi var mi',role:'Soru/Olumsuz'},{ro:'hai chao mai',tr:'kiralik olur mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'จุดสน็อกเกิลอยู่ตรงไหนครับ',ro:'jut sa-nok-goen yuu trong-nai khrap',tr:'Snorkel noktasi nerede?',bd:[{ro:'jut sa-nok-goen',tr:'snorkel noktasi',role:'S - Ozne'},{ro:'yuu trong-nai',tr:'nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'วันนี้น้ำขุ่น เล่นสน็อกเกิลยากครับ',ro:'wan-nii naam khun len sa-nok-goen yaak khrap',tr:'Bugun su bulanik, snorkel zor.',bd:[{ro:'wan-nii naam khun',tr:'bugun su bulanik',role:'Durum'},{ro:'len sa-nok-goen yaak',tr:'snorkel zor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'คลื่น',ro:'khluen',tr:'Dalga',
     tip:'Dalga gucu yuzme guvenligi icin kritik bir bilgi.',
     ctx:'Kirmizi bayrak varsa dalga tehlikeli olabilir.',
     examples:[
       {th:'วันนี้คลื่นแรงครับ',ro:'wan-nii khluen raeng khrap',tr:'Bugun dalga guclu.',bd:[{ro:'wan-nii',tr:'bugun',role:'Zaman'},{ro:'khluen raeng',tr:'dalga guclu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'คลื่นสูงมากครับ ระวังนะครับ',ro:'khluen suung maak khrap ra-wang na khrap',tr:'Dalga cok yuksek, dikkat edin.',bd:[{ro:'khluen suung maak',tr:'dalga cok yuksek',role:'Durum'},{ro:'ra-wang na',tr:'dikkat et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ตอนเช้าคลื่นเบากว่าครับ',ro:'ton-chao khluen bao-gwaa khrap',tr:'Sabah dalga daha hafif.',bd:[{ro:'ton-chao',tr:'sabah',role:'Zaman'},{ro:'khluen bao-gwaa',tr:'dalga daha hafif',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'หาดทราย',ro:'haat-saai',tr:'Kumsal',
     tip:'Haat saai kelimesi kumlu sahil icin kullanilir.',
     ctx:'Karon kumsali uzun yuruyus icin uygundur.',
     examples:[
       {th:'หาดทรายที่กะรนยาวมากครับ',ro:'haat-saai thii Ka-ron yaao maak khrap',tr:'Karon kumsali cok uzun.',bd:[{ro:'haat-saai thii Ka-ron',tr:'Karon kumsali',role:'S - Ozne'},{ro:'yaao maak',tr:'cok uzun',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมนั่งที่หาดทรายครับ',ro:'pom nang thii haat-saai khrap',tr:'Kumsalda oturuyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'nang thii haat-saai',tr:'kumsalda oturmak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'หาดทรายร้อนมากตอนเที่ยงครับ',ro:'haat-saai ron maak ton-thiang khrap',tr:'Oglen kumsal cok sicak.',bd:[{ro:'haat-saai',tr:'kumsal',role:'S - Ozne'},{ro:'ron maak ton-thiang',tr:'oglen cok sicak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'ใส่ชุดว่ายน้ำ',ro:'sai chut waai-naam',tr:'Mayolu olmak',
     tip:'Sahile giderken kiyafet kodu icin kullanilir.',
     ctx:'Plaj restoraninda bazen ustluk istenir.',
     examples:[
       {th:'ผมใส่ชุดว่ายน้ำแล้วครับ',ro:'pom sai chut waai-naam laeo khrap',tr:'Mayomu giydim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'sai chut waai-naam laeo',tr:'mayoyu giymis',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ใส่ชุดว่ายน้ำลงทะเลได้ครับ',ro:'sai chut waai-naam long tha-lay dai khrap',tr:'Mayoyla denize girebilirsin.',bd:[{ro:'sai chut waai-naam',tr:'mayo giymek',role:'V - Yuklem'},{ro:'long tha-lay dai',tr:'denize girebilir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ร้านนี้ขอให้ใส่เสื้อทับครับ',ro:'raan nii khor hai sai seua thap khrap',tr:'Bu mekan ustune tisort istiyor.',bd:[{ro:'raan nii',tr:'bu mekan',role:'S - Ozne'},{ro:'khor hai sai seua thap',tr:'ustluk giyin diyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'ร่มชายหาด',ro:'rom chaai-haat',tr:'Semsiye',
     tip:'Gunesin sert oldugu saatlerde semsiye kiralamak yaygin.',
     ctx:'Patongda saatlik veya gunluk semsiye kiralanir.',
     examples:[
       {th:'เช่าร่มชายหาดหนึ่งอันครับ',ro:'chao rom chaai-haat nueng an khrap',tr:'Bir plaj semsiyesi kiraliyorum.',bd:[{ro:'chao rom chaai-haat',tr:'plaj semsiyesi kiralamak',role:'V - Yuklem'},{ro:'nueng an',tr:'bir adet',role:'Miktar'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ร่มชายหาดวันละเท่าไรครับ',ro:'rom chaai-haat wan-la thao-rai khrap',tr:'Semsiye gunluk ne kadar?',bd:[{ro:'rom chaai-haat',tr:'plaj semsiyesi',role:'S - Ozne'},{ro:'wan-la thao-rai',tr:'gunluk ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ขอร่มใกล้น้ำหน่อยครับ',ro:'khor rom glai naam noi khrap',tr:'Suya yakin bir semsiye istiyorum.',bd:[{ro:'khor rom',tr:'semsiye istiyorum',role:'V - Yuklem'},{ro:'glai naam noi',tr:'suya yakin biraz',role:'Yer'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ร่มนี้พับได้ไหมครับ',ro:'rom nii phap dai mai khrap',tr:'Bu semsiye kapanir mi?',bd:[{ro:'rom nii',tr:'bu semsiye',role:'S - Ozne'},{ro:'phap dai mai',tr:'kapanir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'แมงกะพรุน',ro:'maeng-ga-phrun',tr:'Denizanasi',
     tip:'Yagmur sezonunda denizanasi uyarilari artar.',
     ctx:'Plaj gorevlisi uyarilarina dikkat etmek gerekir.',
     examples:[
       {th:'วันนี้มีแมงกะพรุนครับ',ro:'wan-nii mii maeng-ga-phrun khrap',tr:'Bugun denizanasi var.',bd:[{ro:'wan-nii',tr:'bugun',role:'Zaman'},{ro:'mii maeng-ga-phrun',tr:'denizanasi var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โดนแมงกะพรุนต่อยครับ',ro:'pom don maeng-ga-phrun toi khrap',tr:'Denizanasi carpti.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'don maeng-ga-phrun toi',tr:'denizanasi soktu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'มีน้ำส้มสายชูไหมครับ',ro:'mii naam-som-saai-chuu mai khrap',tr:'Sirke var mi?',bd:[{ro:'mii naam-som-saai-chuu mai',tr:'sirke var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ช่วยพาไปคลินิกหน่อยครับ',ro:'chuay phaa bpai khli-nik noi khrap',tr:'Lutfen klinige goturun.',bd:[{ro:'chuay phaa bpai khli-nik',tr:'klinige gotur yardim et',role:'V - Yuklem'},{ro:'noi',tr:'lutfen',role:'Kibar'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. Plajda Yer ve Durum Sorma',
      formula:'[YER] + YUU THII-NAI + MAI = ... nerede mi',
      explain:'Plajda semsiye, snorkel noktasi veya guvenli yuzme alanini sormak icin temel kalip.',
      tips:['yuu thii-nai = nerede','mai = soru eki','trong-nii = burada','dai = olabilir yapabilir','khrap = erkek kibar eki'],
      examples:[
        {th:'จุดว่ายน้ำปลอดภัยอยู่ที่ไหนครับ',ro:'jut waai-naam bplod-phai yuu thii-nai khrap',tr:'Guvenli yuzme alani nerede?',bd:[{ro:'jut waai-naam bplod-phai',tr:'guvenli yuzme noktasi',role:'S - Ozne'},{ro:'yuu thii-nai',tr:'nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ร่มชายหาดอยู่ตรงนี้ไหมครับ',ro:'rom chaai-haat yuu trong-nii mai khrap',tr:'Plaj semsiyesi burada mi?',bd:[{ro:'rom chaai-haat',tr:'plaj semsiyesi',role:'S - Ozne'},{ro:'yuu trong-nii mai',tr:'burada mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'สน็อกเกิลเล่นได้ที่นี่ไหมครับ',ro:'sa-nok-goen len dai thii-nii mai khrap',tr:'Burada snorkel yapilir mi?',bd:[{ro:'sa-nok-goen len dai',tr:'snorkel yapilabilir',role:'V - Yuklem'},{ro:'thii-nii mai',tr:'burada mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ห้องอาบน้ำอยู่ที่ไหนครับ',ro:'hong-aap-naam yuu thii-nai khrap',tr:'Dus yeri nerede?',bd:[{ro:'hong-aap-naam',tr:'dus yeri',role:'S - Ozne'},{ro:'yuu thii-nai',tr:'nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. Uyari ve Yasak Ifadeleri',
      formula:'MAI + [FIIL] = yapma yok | RA-WANG = dikkat et',
      explain:'Dalga ve denizanasi gibi riskli durumlarda kisa ve net uyari cumleleri kullanilir.',
      tips:['mai waai-naam = yuzme','ra-wang = dikkat','khluen raeng = guclu dalga','maeng-ga-phrun = denizanasi','chuay duay = yardim edin'],
      examples:[
        {th:'วันนี้คลื่นแรง ไม่ว่ายน้ำนะครับ',ro:'wan-nii khluen raeng mai waai-naam na khrap',tr:'Bugun dalga guclu, yuzme lutfen.',bd:[{ro:'wan-nii khluen raeng',tr:'bugun dalga guclu',role:'Durum'},{ro:'mai waai-naam',tr:'yuzme yok',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ระวังแมงกะพรุนครับ',ro:'ra-wang maeng-ga-phrun khrap',tr:'Denizanasina dikkat.',bd:[{ro:'ra-wang',tr:'dikkat',role:'V - Yuklem'},{ro:'maeng-ga-phrun',tr:'denizanasi',role:'Nesne'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ห้ามลงทะเลตอนนี้ครับ',ro:'haam long tha-lay ton-nii khrap',tr:'Simdi denize girmek yasak.',bd:[{ro:'haam long tha-lay',tr:'denize girmek yasak',role:'V - Yuklem'},{ro:'ton-nii',tr:'simdi',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ช่วยเรียกไลฟ์การ์ดหน่อยครับ',ro:'chuay riak lai-gaad noi khrap',tr:'Lutfen cankurtarani cagirin.',bd:[{ro:'chuay riak lai-gaad',tr:'cankurtaran cagir',role:'V - Yuklem'},{ro:'noi',tr:'lutfen',role:'Kibar'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Patong plajinda oldugunu soyle',th:'ผมอยู่ที่หาดป่าตองครับ',ro:'pom yuu thii haat Pa-tong khrap',tr:'Patong plajindayim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu thii haat Pa-tong',tr:'Patong plajinda',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Yuzme icin guvenli yer sor',th:'ว่ายน้ำตรงไหนปลอดภัยครับ',ro:'waai-naam trong-nai bplod-phai khrap',tr:'Nerede guvenli yuzebilirim?',bd:[{ro:'waai-naam trong-nai',tr:'nerede yuzmek',role:'Soru/Olumsuz'},{ro:'bplod-phai',tr:'guvenli',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Gunes kremi iste',th:'ขอครีมกันแดดหน่อยครับ',ro:'khor khriim gan-daet noi khrap',tr:'Lutfen gunes kremi istiyorum.',bd:[{ro:'khor khriim gan-daet',tr:'gunes kremi istiyorum',role:'V - Yuklem'},{ro:'noi',tr:'lutfen',role:'Kibar'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Snorkel ekipmani sor',th:'มีชุดสน็อกเกิลให้เช่าไหมครับ',ro:'mii chut sa-nok-goen hai chao mai khrap',tr:'Snorkel seti kiralik var mi?',bd:[{ro:'mii chut sa-nok-goen',tr:'snorkel seti var mi',role:'Soru/Olumsuz'},{ro:'hai chao mai',tr:'kiralik olur mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Dalga guclu de',th:'วันนี้คลื่นแรงครับ',ro:'wan-nii khluen raeng khrap',tr:'Bugun dalga guclu.',bd:[{ro:'wan-nii',tr:'bugun',role:'Zaman'},{ro:'khluen raeng',tr:'dalga guclu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Semsiye fiyati sor',th:'ร่มชายหาดวันละเท่าไรครับ',ro:'rom chaai-haat wan-la thao-rai khrap',tr:'Plaj semsiyesi gunluk ne kadar?',bd:[{ro:'rom chaai-haat',tr:'plaj semsiyesi',role:'S - Ozne'},{ro:'wan-la thao-rai',tr:'gunluk ne kadar',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Denizanasi uyarisi ver',th:'ระวังแมงกะพรุนครับ',ro:'ra-wang maeng-ga-phrun khrap',tr:'Denizanasina dikkat.',bd:[{ro:'ra-wang maeng-ga-phrun',tr:'denizanasina dikkat',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Yardim iste',th:'ช่วยพาผมไปคลินิกหน่อยครับ',ro:'chuay phaa pom bpai khli-nik noi khrap',tr:'Lutfen beni klinige goturun.',bd:[{ro:'chuay phaa pom bpai khli-nik',tr:'beni klinige gotur',role:'V - Yuklem'},{ro:'noi',tr:'lutfen',role:'Kibar'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🏖️ Patong Plaj Plani',
     lines:[
       {s:'Ali',th:'วันนี้ไปหาดป่าตองกันไหมครับ',ro:'wan-nii bpai haat Pa-tong gan mai khrap',tr:'Bugun Patong plajina gidelim mi?',bd:[{ro:'wan-nii bpai haat Pa-tong',tr:'bugun Patonga gitmek',role:'V - Yuklem'},{ro:'gan mai',tr:'birlikte mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ได้ค่ะ แต่แดดแรงมากนะคะ',ro:'dai kha tae daet raeng maak na kha',tr:'Olur ama gunes cok guclu.',bd:[{ro:'dai',tr:'olur',role:'V - Yuklem'},{ro:'daet raeng maak',tr:'gunes cok guclu',role:'Durum'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ผมมีครีมกันแดดครับ',ro:'pom mii khriim gan-daet khrap',tr:'Bende gunes kremi var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'mii khriim gan-daet',tr:'gunes kremi var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ดีเลยค่ะ แล้วเช่าร่มด้วยนะคะ',ro:'dii loey kha laeo chao rom duay na kha',tr:'Harika, bir de semsiye kiralayalim.',bd:[{ro:'dii loey',tr:'harika',role:'Durum'},{ro:'chao rom duay',tr:'semsiye de kirala',role:'V - Yuklem'},{ro:'na kha',tr:'rica eki',role:'Kibar'}]},
     ]},
    {title:'🤿 Karon Snorkel Noktasi',
     lines:[
       {s:'Ali',th:'ที่หาดกะรนเล่นสน็อกเกิลตรงไหนครับ',ro:'thii haat Ka-ron len sa-nok-goen trong-nai khrap',tr:'Karonda nerede snorkel yapilir?',bd:[{ro:'thii haat Ka-ron',tr:'Karon plajinda',role:'Yer'},{ro:'len sa-nok-goen trong-nai',tr:'nerede snorkel',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ไปด้านซ้ายของหาดค่ะ น้ำใสมาก',ro:'bpai daan saai khong haat kha naam sai maak',tr:'Plajin sol tarafina gidin, su cok berrak.',bd:[{ro:'bpai daan saai khong haat',tr:'plajin soluna git',role:'V - Yuklem'},{ro:'naam sai maak',tr:'su cok berrak',role:'Durum'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'มีหน้ากากให้เช่าไหมครับ',ro:'mii naa-gaak hai chao mai khrap',tr:'Maske kiralik var mi?',bd:[{ro:'mii naa-gaak',tr:'maske var mi',role:'Soru/Olumsuz'},{ro:'hai chao mai',tr:'kiralik olur mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'มีค่ะ ชุดละหนึ่งร้อยบาทค่ะ',ro:'mii kha chut la nueng-roi baht kha',tr:'Var, seti 100 Baht.',bd:[{ro:'chut la nueng-roi baht',tr:'set basina 100 Baht',role:'Miktar'},{ro:'mii',tr:'var',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'โอเคครับ ผมเอาหนึ่งชุดครับ',ro:'o-khee khrap pom ao nueng chut khrap',tr:'Tamam bir set aliyorum.',bd:[{ro:'pom ao nueng chut',tr:'bir set aliyorum',role:'V - Yuklem'},{ro:'o-khee',tr:'tamam',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🌊 Dalga Uyarisi',
     lines:[
       {s:'Ali',th:'วันนี้คลื่นสูงมากครับ',ro:'wan-nii khluen suung maak khrap',tr:'Bugun dalga cok yuksek.',bd:[{ro:'wan-nii',tr:'bugun',role:'Zaman'},{ro:'khluen suung maak',tr:'dalga cok yuksek',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ใช่ค่ะ ตอนนี้ไม่ควรว่ายน้ำค่ะ',ro:'chai kha ton-nii mai khuan waai-naam kha',tr:'Evet simdi yuzmek uygun degil.',bd:[{ro:'ton-nii',tr:'simdi',role:'Zaman'},{ro:'mai khuan waai-naam',tr:'yuzmek uygun degil',role:'Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'งั้นผมนั่งใต้ร่มครับ',ro:'ngan pom nang dtai rom khrap',tr:'O zaman semsiye altinda oturuyorum.',bd:[{ro:'pom nang dtai rom',tr:'semsiye altinda otururum',role:'V - Yuklem'},{ro:'ngan',tr:'o zaman',role:'Baglac'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ดีค่ะ ปลอดภัยที่สุดค่ะ',ro:'dii kha bplod-phai thii-sut kha',tr:'Iyi, en guvenlisi bu.',bd:[{ro:'dii',tr:'iyi',role:'Durum'},{ro:'bplod-phai thii-sut',tr:'en guvenli',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🪼 Denizanasi Sonrasi',
     lines:[
       {s:'Ali',th:'ผมโดนแมงกะพรุนต่อยครับ',ro:'pom don maeng-ga-phrun toi khrap',tr:'Denizanasi carpti.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'don maeng-ga-phrun toi',tr:'denizanasi soktu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'เจ็บมากไหมคะ',ro:'jep maak mai kha',tr:'Cok aciyor mu?',bd:[{ro:'jep maak mai',tr:'cok aciyor mu',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'เจ็บครับ ช่วยด้วยครับ',ro:'jep khrap chuay duay khrap',tr:'Aciyor, yardim edin.',bd:[{ro:'jep',tr:'aciyor',role:'V - Yuklem'},{ro:'chuay duay',tr:'yardim edin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'เดี๋ยวพาไปคลินิกใกล้หาดค่ะ',ro:'diao phaa bpai khli-nik glai haat kha',tr:'Seni plaja yakin klinige goturecegim.',bd:[{ro:'phaa bpai khli-nik',tr:'klinige goturmek',role:'V - Yuklem'},{ro:'glai haat',tr:'plaja yakin',role:'Yer'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'ผมอยู่ที่ชายหาดป่าตองครับ',q:'Ali nerede?',opts:['Hastanede','Patong plajinda','Eczanede'],c:1},
    {diff:'easy',th:'มีครีมกันแดดไหมครับ',q:'Ne soruyor?',opts:['Semsiye var mi','Gunes kremi var mi','Snorkel turu var mi'],c:1},
    {diff:'easy',th:'วันนี้คลื่นแรงครับ',q:'Durum ne?',opts:['Hava soguk','Dalga guclu','Deniz sakin'],c:1},
    {diff:'medium',th:'ร่มชายหาดวันละเท่าไรครับ',q:'Ne soruluyor?',opts:['Gunluk semsiye fiyati','Deniz suyu sicakligi','Plaj giris ucreti'],c:0},
    {diff:'medium',th:'สน็อกเกิลเล่นได้ที่นี่ไหมครับ',q:'Ali ne istiyor?',opts:['Burada snorkel yapmak','Yuzme dersi almak','Tekne kiralamak'],c:0},
    {diff:'medium',th:'วันนี้น้ำขุ่น เล่นสน็อกเกิลยากครับ',q:'Neden zor?',opts:['Ekipman yok','Su bulanik','Dalga yok'],c:1},
    {diff:'medium',th:'ระวังแมงกะพรุนครับ',q:'Uyari ne ile ilgili?',opts:['Yagmur','Denizanasi','Gunes kremi'],c:1},
    {diff:'hard',th:'ห้ามลงทะเลตอนนี้ครับ',q:'Ne ifade ediliyor?',opts:['Simdi denize giris serbest','Simdi denize girmek yasak','Sadece cocuklar girebilir'],c:1},
    {diff:'hard',th:'ผมเอาหนึ่งชุดครับ',q:'Ali ne yapiyor?',opts:['Bir set ekipman aliyor','Bir semsiye iade ediyor','Bir tekne satiyor'],c:0},
    {diff:'hard',th:'ช่วยพาผมไปคลินิกหน่อยครับ',q:'Ali ne istiyor?',opts:['Klinige goturulmek','Otele donmek','Polisi aramak'],c:0},
  ],
  quiz:[
    {q:'"chaai-haat" ne demek?',opts:['Kumsal yol','Plaj','Liman','Dalgakiran'],c:1},
    {q:'"tha-lay" ne demek?',opts:['Nehir','Göl','Deniz','Yagmur'],c:2},
    {q:'"waai-naam" ne demek?',opts:['Kosmak','Yuzmek','Yurumek','Beklemek'],c:1},
    {q:'"khriim gan-daet" ne demek?',opts:['Nemlendirici','Gunes kremi','Sabun','Sampuan'],c:1},
    {q:'"sa-nok-goen" ne demek?',opts:['Jetski','Snorkel','Sorf','Kano'],c:1},
    {q:'"khluen raeng" ne anlama gelir?',opts:['Dalga guclu','Ruzgar hafif','Deniz sicak','Plaj bos'],c:0},
    {q:'"rom chaai-haat" ne demek?',opts:['Plaj semsiyesi','Plaj havlusu','Plaj sandalyesi','Plaj cantasi'],c:0},
    {q:'Denizanasi kelimesi hangisi?',opts:['maeng-ga-phrun','haat-saai','daet','naam'],c:0},
    {q:'Phukette snorkel icin populer plaj?',opts:['Karon','Kata Noi','Mai Khao','Hepsi'],c:3},
    {q:'"khrap" neyi gosterir?',opts:['Soru eki','Erkek kibar eki','Olumsuzluk','Cogul eki'],c:1},
  ],
};

LESSONS[10] = L10;
