// Ders 15 verisi — tayca-v3
// =================== VERİ: DERS 15 — Immigration ve Resmi Isler ===================
const L15 = {
  tones:[],
  words:[
    {id:'w1',th:'หนังสือเดินทาง',ro:'nang-sue dern-thaang',tr:'Pasaport',
     tip:'Immigration islemlerinde temel belge.',
     ctx:'Phuket immigration girisinde once pasaport kontrol edilir.',
     examples:[
      {th:'นี่คือหนังสือเดินทางของผมครับ',ro:'nii khue nang-sue dern-thaang khong pom khrap',tr:'Bu benim pasaportum.',bd:[{ro:'nii khue nang-sue dern-thaang khong pom',tr:'bu benim pasaportum',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมลืมหนังสือเดินทางที่บ้านครับ',ro:'pom luem nang-sue dern-thaang thii baan khrap',tr:'Pasaportumu evde unuttum.',bd:[{ro:'pom luem nang-sue dern-thaang',tr:'pasaportumu unuttum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'วีซ่า',ro:'wii-saa',tr:'Vize',
     tip:'Tayland kalis izni ile ilgilidir.',
     ctx:'Turist vizelerinde sure takibi cok onemlidir.',
     examples:[
      {th:'วีซ่าของผมจะหมดอายุครับ',ro:'wii-saa khong pom ja mot aa-yu khrap',tr:'Vizemin suresi bitecek.',bd:[{ro:'wii-saa khong pom ja mot aa-yu',tr:'vizemin suresi bitecek',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมต้องการตรวจวีซ่าครับ',ro:'pom tong-gaan truat wii-saa khrap',tr:'Vizemi kontrol ettirmek istiyorum.',bd:[{ro:'pom tong-gaan truat wii-saa',tr:'vizemi kontrol ettirmek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'ต่ออายุ',ro:'tor-aa-yu',tr:'Uzatma',
     tip:'Vize suresini uzatma anlamina gelir.',
     ctx:'Phuket te cok kisinin yaptigi bir islem.',
     examples:[
      {th:'ผมมาต่ออายุวีซ่าครับ',ro:'pom maa tor-aa-yu wii-saa khrap',tr:'Vize uzatma icin geldim.',bd:[{ro:'pom maa tor-aa-yu wii-saa',tr:'vize uzatma icin geldim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ต่ออายุได้กี่วันครับ',ro:'tor-aa-yu dai gii wan khrap',tr:'Kac gun uzatma alabilirim?',bd:[{ro:'tor-aa-yu dai gii wan',tr:'kac gun uzatma alabilirim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'ตม',ro:'to-mor',tr:'Immigration',
     tip:'Gunluk dilde immigration kisaltmasi olarak kullanilir.',
     ctx:'Ofis konumu sorarken gerekli kelime.',
     examples:[
      {th:'ตมอยู่ที่ไหนครับ',ro:'to-mor yuu thii-nai khrap',tr:'Immigration nerede?',bd:[{ro:'to-mor yuu thii-nai',tr:'immigration nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'วันนี้ตมคนเยอะครับ',ro:'wan-nii to-mor khon yoe khrap',tr:'Bugun immigration kalabalik.',bd:[{ro:'wan-nii to-mor khon yoe',tr:'bugun immigration kalabalik',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'แบบฟอร์ม',ro:'baep-form',tr:'Form',
     tip:'Basvuru kagidi anlamina gelir.',
     ctx:'Immigration bankosunda form doldurulur.',
     examples:[
      {th:'แบบฟอร์มอยู่ที่ไหนครับ',ro:'baep-form yuu thii-nai khrap',tr:'Form nereden alinir?',bd:[{ro:'baep-form yuu thii-nai',tr:'form nereden alinir',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมต้องกรอกแบบฟอร์มนี้ครับ',ro:'pom tong grok baep-form nii khrap',tr:'Bu formu doldurmam gerekiyor.',bd:[{ro:'pom tong grok baep-form nii',tr:'formu doldurmam gerekiyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'รูปถ่าย',ro:'ruup-thaai',tr:'Fotograf',
     tip:'Pasaport tipi fotograf icin kullanilir.',
     ctx:'Belge tesliminde adet sayisi sorulur.',
     examples:[
      {th:'ต้องใช้รูปถ่ายกี่ใบครับ',ro:'tong chai ruup-thaai gii bai khrap',tr:'Kac adet fotograf lazim?',bd:[{ro:'tong chai ruup-thaai gii bai',tr:'kac fotograf lazim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'รูปถ่ายพื้นหลังขาวครับ',ro:'ruup-thaai pheun-lang khao khrap',tr:'Fotograf arka plani beyaz.',bd:[{ro:'ruup-thaai pheun-lang khao',tr:'arka plani beyaz fotograf',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'ตราประทับ',ro:'tra pra-thap',tr:'Damga',
     tip:'Pasaporta basilan resmi damga.',
     ctx:'Giris cikis tarihlerinde cok onemli.',
     examples:[
      {th:'นี่ตราประทับใหม่ครับ',ro:'nii tra pra-thap mai khrap',tr:'Bu yeni damga.',bd:[{ro:'nii tra pra-thap mai',tr:'bu yeni damga',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมต้องการตราประทับวันนี้ครับ',ro:'pom tong-gaan tra pra-thap wan-nii khrap',tr:'Bugun damga istiyorum.',bd:[{ro:'pom tong-gaan tra pra-thap wan-nii',tr:'bugun damga istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'ระยะเวลา',ro:'ra-ya we-laa',tr:'Sure',
     tip:'Kalis veya bekleme suresini anlatir.',
     ctx:'Sira beklerken gorevli sure bilgisi verir.',
     examples:[
      {th:'ระยะเวลารอคิวประมาณหนึ่งชั่วโมงครับ',ro:'ra-ya we-laa ro-khiu pra-maan nueng chua-moong khrap',tr:'Bekleme suresi yaklasik bir saat.',bd:[{ro:'ra-ya we-laa ro-khiu pra-maan nueng chua-moong',tr:'bekleme suresi bir saat',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ระยะเวลาพำนักสามสิบวันครับ',ro:'ra-ya we-laa pham-nak saam-sip wan khrap',tr:'Kalis suresi otuz gun.',bd:[{ro:'ra-ya we-laa pham-nak saam-sip wan',tr:'kalis suresi otuz gun',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'เอกสาร',ro:'eek-ga-saan',tr:'Belge',
     tip:'Resmi kagitlar icin genel kelime.',
     ctx:'Eksik belge oldugunda islem durur.',
     examples:[
      {th:'เอกสารของผมครบไหมครับ',ro:'eek-ga-saan khong pom khrop mai khrap',tr:'Belgelerim tam mi?',bd:[{ro:'eek-ga-saan khong pom khrop mai',tr:'belgelerim tam mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมขาดเอกสารหนึ่งใบครับ',ro:'pom khaat eek-ga-saan nueng bai khrap',tr:'Bir belgem eksik.',bd:[{ro:'pom khaat eek-ga-saan nueng bai',tr:'bir belgem eksik',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'นัดหมาย',ro:'nat-maai',tr:'Randevu',
     tip:'Online veya telefonda alinabilir.',
     ctx:'Yogun gunlerde randevu cok gerekli.',
     examples:[
      {th:'ผมมีนัดหมายพรุ่งนี้ครับ',ro:'pom mii nat-maai phrung-nii khrap',tr:'Yarin randevum var.',bd:[{ro:'pom mii nat-maai phrung-nii',tr:'yarin randevum var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ขอเปลี่ยนนัดหมายได้ไหมครับ',ro:'khor plian nat-maai dai mai khrap',tr:'Randevuyu degistirebilir miyim?',bd:[{ro:'khor plian nat-maai dai mai',tr:'randevuyu degistirebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. Islem Baslatma Cumlesi',
      formula:'POM MAA + [ISLEM] + KHRAP = ... icin geldim',
      explain:'Immigration bankosunda nedeni aciklamak icin en pratik kalip.',
      tips:['pom maa = geldim','tor-aa-yu = uzatma','truat = kontrol','khor = talep etmek','wii-saa = vize','to-mor = immigration'],
      examples:[
        {th:'ผมมาต่ออายุวีซ่าครับ',ro:'pom maa tor-aa-yu wii-saa khrap',tr:'Vize uzatma icin geldim.',bd:[{ro:'pom maa tor-aa-yu wii-saa',tr:'vize uzatma icin geldim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมมาตรวจวีซ่าครับ',ro:'pom maa truat wii-saa khrap',tr:'Vize kontrolu icin geldim.',bd:[{ro:'pom maa truat wii-saa',tr:'vize kontrolu icin geldim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมมาขอตราประทับครับ',ro:'pom maa khor tra pra-thap khrap',tr:'Damga almak icin geldim.',bd:[{ro:'pom maa khor tra pra-thap',tr:'damga almak icin geldim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมมีนัดหมายสิบโมงครับ',ro:'pom mii nat-maai sip-moong khrap',tr:'Saat onda randevum var.',bd:[{ro:'pom mii nat-maai sip-moong',tr:'saat onda randevum var',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. Belge ve Sure Sorma',
      formula:'[SEY] + KHROP MAI KHRAP = ... tam mi',
      explain:'Evrak durumu ve kalis suresi ogrenmek icin kullanilir.',
      tips:['khrop = tam','khaat = eksik','dai mai = mumkun mu','gii wan = kac gun','ra-ya we-laa = sure','ro-khiu = sira bekleme'],
      examples:[
        {th:'เอกสารของผมครบไหมครับ',ro:'eek-ga-saan khong pom khrop mai khrap',tr:'Belgelerim tam mi?',bd:[{ro:'eek-ga-saan khong pom khrop mai',tr:'belgelerim tam mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมขาดเอกสารอะไรครับ',ro:'pom khaat eek-ga-saan a-rai khrap',tr:'Hangi belgem eksik?',bd:[{ro:'pom khaat eek-ga-saan a-rai',tr:'hangi belgem eksik',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ต่ออายุได้กี่วันครับ',ro:'tor-aa-yu dai gii wan khrap',tr:'Kac gun uzatma olur?',bd:[{ro:'tor-aa-yu dai gii wan',tr:'kac gun uzatma olur',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ระยะเวลารอคิวนานไหมครับ',ro:'ra-ya we-laa ro-khiu naan mai khrap',tr:'Bekleme suresi uzun mu?',bd:[{ro:'ra-ya we-laa ro-khiu naan mai',tr:'bekleme suresi uzun mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Pasaport goster',th:'นี่คือหนังสือเดินทางของผมครับ',ro:'nii khue nang-sue dern-thaang khong pom khrap',tr:'Bu benim pasaportum.',bd:[{ro:'nii khue nang-sue dern-thaang khong pom',tr:'bu benim pasaportum',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Vize durumu soyle',th:'วีซ่าของผมจะหมดอายุครับ',ro:'wii-saa khong pom ja mot aa-yu khrap',tr:'Vizemin suresi bitecek.',bd:[{ro:'wii-saa khong pom ja mot aa-yu',tr:'vizemin suresi bitecek',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Uzatma iste',th:'ผมมาต่ออายุวีซ่าครับ',ro:'pom maa tor-aa-yu wii-saa khrap',tr:'Vize uzatma icin geldim.',bd:[{ro:'pom maa tor-aa-yu wii-saa',tr:'vize uzatma icin geldim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Immigration adresi sor',th:'ตมอยู่ที่ไหนครับ',ro:'to-mor yuu thii-nai khrap',tr:'Immigration nerede?',bd:[{ro:'to-mor yuu thii-nai',tr:'immigration nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Form sor',th:'แบบฟอร์มอยู่ที่ไหนครับ',ro:'baep-form yuu thii-nai khrap',tr:'Form nereden alinir?',bd:[{ro:'baep-form yuu thii-nai',tr:'form nereden alinir',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Fotograf adedi sor',th:'ต้องใช้รูปถ่ายกี่ใบครับ',ro:'tong chai ruup-thaai gii bai khrap',tr:'Kac fotograf gerekli?',bd:[{ro:'tong chai ruup-thaai gii bai',tr:'kac fotograf gerekli',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Belge tamligini sor',th:'เอกสารของผมครบไหมครับ',ro:'eek-ga-saan khong pom khrop mai khrap',tr:'Belgelerim tam mi?',bd:[{ro:'eek-ga-saan khong pom khrop mai',tr:'belgelerim tam mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Randevu degistir',th:'ขอเปลี่ยนนัดหมายได้ไหมครับ',ro:'khor plian nat-maai dai mai khrap',tr:'Randevuyu degistirebilir miyim?',bd:[{ro:'khor plian nat-maai dai mai',tr:'randevu degistirebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🛂 Immigration Bankosu',
     lines:[
      {s:'Ali',th:'สวัสดีครับ ผมมาต่ออายุวีซ่าครับ',ro:'sa-wat-dii khrap pom maa tor-aa-yu wii-saa khrap',tr:'Merhaba vize uzatma icin geldim.',bd:[{ro:'pom maa tor-aa-yu wii-saa',tr:'vize uzatma icin geldim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Officer',th:'ขอหนังสือเดินทางกับแบบฟอร์มค่ะ',ro:'khor nang-sue dern-thaang gap baep-form kha',tr:'Pasaport ve formu lutfen.',bd:[{ro:'khor nang-sue dern-thaang gap baep-form',tr:'pasaport ve form lutfen',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'นี่ครับ เอกสารครบไหมครับ',ro:'nii khrap eek-ga-saan khrop mai khrap',tr:'Buyrun belgeler tam mi?',bd:[{ro:'eek-ga-saan khrop mai',tr:'belgeler tam mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Officer',th:'ครบค่ะ รอสักครู่นะคะ',ro:'khrop kha ro sak-khru na kha',tr:'Tamam biraz bekleyin lutfen.',bd:[{ro:'khrop',tr:'tam',role:'Kelime'},{ro:'ro sak-khru',tr:'biraz bekle',role:'V - Yuklem'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
    ]},
    {title:'📷 Eksik Fotograf',
     lines:[
      {s:'Officer',th:'คุณขาดรูปถ่ายหนึ่งใบค่ะ',ro:'khun khaat ruup-thaai nueng bai kha',tr:'Bir fotograf eksik.',bd:[{ro:'khun khaat ruup-thaai nueng bai',tr:'bir fotograf eksik',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ถ่ายรูปใกล้ๆ ได้ไหมครับ',ro:'thaai ruup glai-glai dai mai khrap',tr:'Yakinlarda fotograf cektirebilir miyim?',bd:[{ro:'thaai ruup glai-glai dai mai',tr:'yakinda fotograf cektirebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Officer',th:'ได้ค่ะ ร้านอยู่หน้าตึก',ro:'dai kha raan yuu naa tuek',tr:'Evet dukkan bina onunde.',bd:[{ro:'raan yuu naa tuek',tr:'dukkan bina onunde',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ขอบคุณครับ เดี๋ยวผมกลับมาครับ',ro:'khop-khun khrap diao pom glap-maa khrap',tr:'Tesekkurler hemen donecegim.',bd:[{ro:'diao pom glap-maa',tr:'hemen donecegim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    ]},
    {title:'📆 Randevu Sorusu',
     lines:[
      {s:'Ali',th:'ผมมีนัดหมายพรุ่งนี้ครับ',ro:'pom mii nat-maai phrung-nii khrap',tr:'Yarin randevum var.',bd:[{ro:'pom mii nat-maai phrung-nii',tr:'yarin randevum var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Officer',th:'พรุ่งนี้คิวยาวมากค่ะ',ro:'phrung-nii khiu yaao maak kha',tr:'Yarin sira cok uzun.',bd:[{ro:'phrung-nii khiu yaao maak',tr:'yarin sira cok uzun',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ขอเปลี่ยนนัดหมายได้ไหมครับ',ro:'khor plian nat-maai dai mai khrap',tr:'Randevuyu degistirebilir miyim?',bd:[{ro:'khor plian nat-maai dai mai',tr:'randevu degistirebilir miyim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Officer',th:'ได้ค่ะ วันศุกร์สิบโมงนะคะ',ro:'dai kha wan-suk sip-moong na kha',tr:'Olur cuma saat onda.',bd:[{ro:'wan-suk sip-moong',tr:'cuma saat onda',role:'Kelime'},{ro:'na kha',tr:'onay eki',role:'Kibar'}]},
    ]},
    {title:'✅ Damga Teslimi',
     lines:[
      {s:'Officer',th:'เรียบร้อยค่ะ นี่ตราประทับใหม่',ro:'riap-roi kha nii tra pra-thap mai',tr:'Tamamlandi bu yeni damga.',bd:[{ro:'riap-roi',tr:'tamamlandi',role:'Kelime'},{ro:'nii tra pra-thap mai',tr:'yeni damga',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'อยู่ได้อีกกี่วันครับ',ro:'yuu dai iik gii wan khrap',tr:'Kac gun daha kalabilirim?',bd:[{ro:'yuu dai iik gii wan',tr:'kac gun daha kalirim',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Officer',th:'อยู่ได้อีกสามสิบวันค่ะ',ro:'yuu dai iik saam-sip wan kha',tr:'Otuz gun daha kalabilirsiniz.',bd:[{ro:'yuu dai iik saam-sip wan',tr:'otuz gun daha kalabilirsiniz',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ขอบคุณมากครับ',ro:'khop-khun maak khrap',tr:'Cok tesekkur ederim.',bd:[{ro:'khop-khun maak',tr:'cok tesekkurler',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    ]},
  ],
  listening:[
    {diff:'easy',th:'ผมมาต่ออายุวีซ่าครับ',q:'Konusmaci ne icin gelmis?',opts:['Vize uzatma','Pasaport kaybi','Bilet alma'],c:0},
    {diff:'easy',th:'ตมอยู่ที่ไหนครับ',q:'Ne soruluyor?',opts:['Immigration adresi','Hastane adresi','Postane adresi'],c:0},
    {diff:'easy',th:'แบบฟอร์มอยู่ที่ไหนครับ',q:'Ne araniyor?',opts:['Form','Pasaport','Damga'],c:0},
    {diff:'medium',th:'ต้องใช้รูปถ่ายกี่ใบครับ',q:'Ne soruluyor?',opts:['Kac fotograf','Kac form','Kac damga'],c:0},
    {diff:'medium',th:'เอกสารของผมครบไหมครับ',q:'Ne kontrol edilmek isteniyor?',opts:['Belge tamligi','Sira no','Odeme tutari'],c:0},
    {diff:'medium',th:'ขอเปลี่ยนนัดหมายได้ไหมครับ',q:'Ne isteniyor?',opts:['Randevu degisikligi','Yeni pasaport','Fotograf'],c:0},
    {diff:'medium',th:'วีซ่าของผมจะหมดอายุครับ',q:'Durum nedir?',opts:['Vize yeni alindi','Vize suresi bitecek','Vize iptal edildi'],c:1},
    {diff:'hard',th:'คุณขาดรูปถ่ายหนึ่งใบค่ะ',q:'Sorun ne?',opts:['Form eksik','Fotograf eksik','Pasaport eksik'],c:1},
    {diff:'hard',th:'นี่ตราประทับใหม่',q:'Ne verildi?',opts:['Damga','Randevu','Kimlik'],c:0},
    {diff:'hard',th:'อยู่ได้อีกสามสิบวันค่ะ',q:'Ne bilgi verildi?',opts:['30 gun daha kalis','30 gun ceza','30 gun bekleme'],c:0},
  ],
  quiz:[
    {q:'nang-sue dern-thaang ne demek?',opts:['Pasaport','Kimlik','Bilet','Form'],c:0},
    {q:'wii-saa ne demek?',opts:['Damga','Vize','Belge','Randevu'],c:1},
    {q:'tor-aa-yu ne demek?',opts:['Iptal','Uzatma','Odeme','Sira'],c:1},
    {q:'to-mor neyi ifade eder?',opts:['Immigration','Hastane','Otogar','Konsolosluk'],c:0},
    {q:'baep-form ne demek?',opts:['Belge','Form','Kart','Kimlik'],c:1},
    {q:'ruup-thaai ne demek?',opts:['Fotograf','Vize','Damga','Sira'],c:0},
    {q:'tra pra-thap ne demek?',opts:['Damga','Pul','Kimlik','Adres'],c:0},
    {q:'eek-ga-saan ne demek?',opts:['Belge','Randevu','Konsolosluk','Ucret'],c:0},
    {q:'nat-maai ne demek?',opts:['Randevu','Uzatma','Kontrol','Onay'],c:0},
    {q:'Erkek konusmaci kibar eki?',opts:['kha','khrap','mai','na'],c:1},
  ],
};

LESSONS[15] = L15;
