// Ders 12 verisi — tayca-v3
// =================== VERI: DERS 12 — Acil Durumlar ===================
const L12 = {
  tones:[],
  words:[
    {id:'w1',th:'ช่วยด้วย',ro:'chuay duay',tr:'Yardim',
     tip:'Acil anda en hizli cagri cumlesidir.',
     ctx:'Yuksek sesle tekrar etmek dikkat ceker.',
     examples:[
       {th:'ช่วยด้วยครับ',ro:'chuay duay khrap',tr:'Yardim edin lutfen.',bd:[{ro:'chuay duay',tr:'yardim edin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ช่วยผมด้วยครับ',ro:'chuay pom duay khrap',tr:'Bana yardim edin lutfen.',bd:[{ro:'chuay pom duay',tr:'bana yardim et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ช่วยเรียกตำรวจด้วยครับ',ro:'chuay riak tam-ruat duay khrap',tr:'Lutfen polisi cagir.',bd:[{ro:'chuay riak tam-ruat duay',tr:'polisi cagir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'ไฟไหม้',ro:'fai-mai',tr:'Yangin',
     tip:'Yangin durumunda 199 hemen aranir.',
     ctx:'Otel veya ev yangininda konum verilir.',
     examples:[
       {th:'ไฟไหม้ครับ',ro:'fai-mai khrap',tr:'Yangin var.',bd:[{ro:'fai-mai',tr:'yangin var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'มีไฟไหม้ที่โรงแรมครับ',ro:'mii fai-mai thii rong-raem khrap',tr:'Otelde yangin var.',bd:[{ro:'mii fai-mai',tr:'yangin var',role:'V - Yuklem'},{ro:'thii rong-raem',tr:'otelde',role:'Yer'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โทร 199 ด่วนครับ',ro:'tho 199 duan khrap',tr:'Acil 199u ara.',bd:[{ro:'tho 199',tr:'199 ara',role:'V - Yuklem'},{ro:'duan',tr:'acil',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ควันเยอะมากครับ',ro:'khwan yoe maak khrap',tr:'Cok fazla duman var.',bd:[{ro:'khwan yoe maak',tr:'cok duman var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'ตำรวจ',ro:'tam-ruat',tr:'Polis',
     tip:'Polis acil numarasi Taylandda 191 dir.',
     ctx:'Hirsizlik veya tehditte polis aranir.',
     examples:[
       {th:'เรียกตำรวจครับ',ro:'riak tam-ruat khrap',tr:'Polisi cagir.',bd:[{ro:'riak tam-ruat',tr:'polisi cagir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โทร 191 ตอนนี้ครับ',ro:'tho 191 ton-nii khrap',tr:'Simdi 191i ara.',bd:[{ro:'tho 191',tr:'191 ara',role:'V - Yuklem'},{ro:'ton-nii',tr:'simdi',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมต้องการคุยกับตำรวจครับ',ro:'pom tong-gaan khui gap tam-ruat khrap',tr:'Polisle konusmak istiyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'tong-gaan khui gap tam-ruat',tr:'polisle konusmak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'ผมหลงทาง',ro:'pom long-thaang',tr:'Kayboldum',
     tip:'Turistik bolgede yol kaybindan sonra kullanilir.',
     ctx:'Patong ve Phuket Town arasinda sik kullanilir.',
     examples:[
       {th:'ผมหลงทางครับ',ro:'pom long-thaang khrap',tr:'Kayboldum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'long-thaang',tr:'kayboldum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมหลงทางที่ป่าตองครับ',ro:'pom long-thaang thii Pa-tong khrap',tr:'Patongda kayboldum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'long-thaang thii Pa-tong',tr:'Patongda kayip',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ช่วยบอกทางไปสถานีตำรวจครับ',ro:'chuay bok thaang bpai sa-thaa-nii tam-ruat khrap',tr:'Polis merkezine yolu tarif edin.',bd:[{ro:'chuay bok thaang bpai sa-thaa-nii tam-ruat',tr:'polis merkezine yol tarif et',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมอยู่ใกล้หาดกะรนครับ',ro:'pom yuu glai haat Ka-ron khrap',tr:'Karon plajina yakinim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu glai haat Ka-ron',tr:'Karon yakininda',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'โดนขโมย',ro:'don kha-mooi',tr:'Calindi',
     tip:'Calinma durumunda hemen polise bildirilir.',
     ctx:'Pasaport ve telefon hirsizligi icin kritik kelime.',
     examples:[
       {th:'กระเป๋าผมโดนขโมยครับ',ro:'gra-bpao pom don kha-mooi khrap',tr:'Cantam calindi.',bd:[{ro:'gra-bpao pom',tr:'cantam',role:'S - Ozne'},{ro:'don kha-mooi',tr:'calindi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โทรศัพท์ผมโดนขโมยครับ',ro:'tho-ra-sap pom don kha-mooi khrap',tr:'Telefonum calindi.',bd:[{ro:'tho-ra-sap pom',tr:'telefonum',role:'S - Ozne'},{ro:'don kha-mooi',tr:'calindi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โดนขโมยที่หาดกะตะครับ',ro:'don kha-mooi thii haat Ka-ta khrap',tr:'Kata plajinda hirsizliga ugradim.',bd:[{ro:'don kha-mooi',tr:'hirsizliga ugradi',role:'V - Yuklem'},{ro:'thii haat Ka-ta',tr:'Kata plajinda',role:'Yer'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ช่วยพาผมไปแจ้งความครับ',ro:'chuay phaa pom bpai jaeng-khwaam khrap',tr:'Lutfen beni sikayet icin goturun.',bd:[{ro:'chuay phaa pom bpai jaeng-khwaam',tr:'sikayete gotur',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'ฉุกเฉิน',ro:'chuk-chaoen',tr:'Acil',
     tip:'Acil servis ve acil durum icin ortak kelimedir.',
     ctx:'1669 ararken cumleye bu kelime ile basla.',
     examples:[
       {th:'นี่เป็นเหตุฉุกเฉินครับ',ro:'nii bpen het chuk-chaoen khrap',tr:'Bu acil bir durum.',bd:[{ro:'nii bpen het chuk-chaoen',tr:'bu acil durum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมต้องการความช่วยเหลือฉุกเฉินครับ',ro:'pom tong-gaan khwaam chuay-luea chuk-chaoen khrap',tr:'Acil yardim gerekiyor.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'tong-gaan khwaam chuay-luea chuk-chaoen',tr:'acil yardim gerek',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไปห้องฉุกเฉินครับ',ro:'bpai hong chuk-chaoen khrap',tr:'Acil servise gidin.',bd:[{ro:'bpai hong chuk-chaoen',tr:'acil servise git',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'อันตราย',ro:'an-ta-raai',tr:'Tehlike',
     tip:'Riskli bolgelerde net uyari verir.',
     ctx:'Plaj dalgasi veya karanlik sokak icin uygundur.',
     examples:[
       {th:'ตรงนี้อันตรายครับ',ro:'trong-nii an-ta-raai khrap',tr:'Burasi tehlikeli.',bd:[{ro:'trong-nii',tr:'burasi',role:'S - Ozne'},{ro:'an-ta-raai',tr:'tehlikeli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'อย่าเข้าไป อันตรายครับ',ro:'yaa khao-bpai an-ta-raai khrap',tr:'Iceriye girme tehlikeli.',bd:[{ro:'yaa khao-bpai',tr:'iceri girme',role:'Olumsuz'},{ro:'an-ta-raai',tr:'tehlikeli',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ตอนกลางคืนตรงนี้อันตรายครับ',ro:'ton-glaang-khuen trong-nii an-ta-raai khrap',tr:'Gece burada tehlike var.',bd:[{ro:'ton-glaang-khuen',tr:'gece',role:'Zaman'},{ro:'trong-nii an-ta-raai',tr:'burasi tehlikeli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'ปลอดภัย',ro:'bplod-phai',tr:'Guvenli',
     tip:'Acil durumdan sonra guvenli alani belirtir.',
     ctx:'Guvenli nokta sorarken sik kullanilir.',
     examples:[
       {th:'ที่นี่ปลอดภัยไหมครับ',ro:'thii-nii bplod-phai mai khrap',tr:'Burasi guvenli mi?',bd:[{ro:'thii-nii',tr:'burasi',role:'S - Ozne'},{ro:'bplod-phai mai',tr:'guvenli mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมอยู่ในที่ปลอดภัยแล้วครับ',ro:'pom yuu nai thii bplod-phai laeo khrap',tr:'Artik guvenli yerdeyim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu nai thii bplod-phai laeo',tr:'artik guvenli yerde',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'พาไปที่ปลอดภัยหน่อยครับ',ro:'phaa bpai thii bplod-phai noi khrap',tr:'Lutfen guvenli yere gotur.',bd:[{ro:'phaa bpai thii bplod-phai',tr:'guvenli yere gotur',role:'V - Yuklem'},{ro:'noi',tr:'lutfen',role:'Kibar'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ตรงนั้นปลอดภัยกว่าครับ',ro:'trong-nan bplod-phai gwaa khrap',tr:'Orasi daha guvenli.',bd:[{ro:'trong-nan',tr:'orasi',role:'S - Ozne'},{ro:'bplod-phai gwaa',tr:'daha guvenli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'ที่อยู่',ro:'thii-yuu',tr:'Adres',
     tip:'Acil aramada tam adres hayati onemlidir.',
     ctx:'Sokak adini yavas ve net okumak gerekir.',
     examples:[
       {th:'ที่อยู่ของผมคือโรงแรมนี้ครับ',ro:'thii-yuu khong pom khue rong-raem nii khrap',tr:'Adresim bu otel.',bd:[{ro:'thii-yuu khong pom',tr:'adresim',role:'S - Ozne'},{ro:'khue rong-raem nii',tr:'bu oteldir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'บอกที่อยู่ให้ 191 ครับ',ro:'bok thii-yuu hai 191 khrap',tr:'191e adres ver.',bd:[{ro:'bok thii-yuu',tr:'adresi soyle',role:'V - Yuklem'},{ro:'hai 191',tr:'191e',role:'Nesne'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'บอกที่อยู่ให้ 1669 ครับ',ro:'bok thii-yuu hai 1669 khrap',tr:'1669a adres ver.',bd:[{ro:'bok thii-yuu',tr:'adresi soyle',role:'V - Yuklem'},{ro:'hai 1669',tr:'1669a',role:'Nesne'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'โทรศัพท์',ro:'tho-ra-sap',tr:'Telefon',
     tip:'Acil numaralar icin telefon hep dolu sarj olmali.',
     ctx:'Telefonla konum paylasmak yardimi hizlandirir.',
     examples:[
       {th:'โทรศัพท์ผมหายครับ',ro:'tho-ra-sap pom haai khrap',tr:'Telefonum kayip.',bd:[{ro:'tho-ra-sap pom',tr:'telefonum',role:'S - Ozne'},{ro:'haai',tr:'kayip',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมใช้โทรศัพท์โทร 191 ครับ',ro:'pom chai tho-ra-sap tho 191 khrap',tr:'Telefonla 191i ariyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'chai tho-ra-sap tho 191',tr:'telefonla 191 ara',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'แบตโทรศัพท์ใกล้หมดครับ',ro:'baet tho-ra-sap glai mot khrap',tr:'Telefon sarji bitmek uzere.',bd:[{ro:'baet tho-ra-sap',tr:'telefon sarji',role:'S - Ozne'},{ro:'glai mot',tr:'bitmek uzere',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ขอยืมโทรศัพท์โทรฉุกเฉินครับ',ro:'khor yuem tho-ra-sap tho chuk-chaoen khrap',tr:'Acil arama icin telefon odunc alabilir miyim?',bd:[{ro:'khor yuem tho-ra-sap',tr:'telefon odunc isterim',role:'V - Yuklem'},{ro:'tho chuk-chaoen',tr:'acil arama',role:'Nesne'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. Acil Cagri Kalibi',
      formula:'CHUAY + [FIIL] + DUAY + KHRAP',
      explain:'Acilde kisa net fiil kullan ve sonuna kibar erkek eki ekle.',
      tips:['chuay = yardim et','riak = cagir','duay = lutfen de','khrap = erkek kibar','duan = acil'],
      examples:[
        {th:'ช่วยเรียกตำรวจด้วยครับ',ro:'chuay riak tam-ruat duay khrap',tr:'Lutfen polisi cagir.',bd:[{ro:'chuay riak tam-ruat duay',tr:'polisi cagir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ช่วยเรียกรถพยาบาลด่วนครับ',ro:'chuay riak rot-pha-yaa-baan duan khrap',tr:'Lutfen acil ambulans cagir.',bd:[{ro:'chuay riak rot-pha-yaa-baan',tr:'ambulans cagir',role:'V - Yuklem'},{ro:'duan',tr:'acil',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ช่วยโทร 191 ให้หน่อยครับ',ro:'chuay tho 191 hai noi khrap',tr:'Lutfen 191i ara.',bd:[{ro:'chuay tho 191 hai',tr:'191 ara',role:'V - Yuklem'},{ro:'noi',tr:'lutfen',role:'Kibar'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ช่วยโทร 199 ตอนนี้ครับ',ro:'chuay tho 199 ton-nii khrap',tr:'Lutfen simdi 199u ara.',bd:[{ro:'chuay tho 199',tr:'199 ara',role:'V - Yuklem'},{ro:'ton-nii',tr:'simdi',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. Konum ve Guvenlik Bildirme',
      formula:'POM YUU THII + [YER] | THII-NII BplOD-PHAI MAI',
      explain:'Acil yardim ekiplerine konum vermek ve guvenli alan sormak icin kullanilir.',
      tips:['pom yuu thii = ben ... deyim','thii-yuu = adres','bplod-phai = guvenli','an-ta-raai = tehlikeli','mai = soru eki'],
      examples:[
        {th:'ผมอยู่ที่หาดป่าตองครับ',ro:'pom yuu thii haat Pa-tong khrap',tr:'Patong plajindayim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu thii haat Pa-tong',tr:'Patong plajinda',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ที่นี่ปลอดภัยไหมครับ',ro:'thii-nii bplod-phai mai khrap',tr:'Burasi guvenli mi?',bd:[{ro:'thii-nii',tr:'burasi',role:'S - Ozne'},{ro:'bplod-phai mai',tr:'guvenli mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ตรงนี้อันตรายมากครับ',ro:'trong-nii an-ta-raai maak khrap',tr:'Burasi cok tehlikeli.',bd:[{ro:'trong-nii',tr:'burasi',role:'S - Ozne'},{ro:'an-ta-raai maak',tr:'cok tehlikeli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'บอกที่อยู่ให้ 1669 แล้วครับ',ro:'bok thii-yuu hai 1669 laeo khrap',tr:'1669a adresi verdim.',bd:[{ro:'bok thii-yuu hai 1669 laeo',tr:'1669a adres verildi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Yardim cagrisi yap',th:'ช่วยด้วยครับ',ro:'chuay duay khrap',tr:'Yardim edin lutfen.',bd:[{ro:'chuay duay',tr:'yardim edin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Polisi ara',th:'โทร 191 ตอนนี้ครับ',ro:'tho 191 ton-nii khrap',tr:'Simdi 191i ara.',bd:[{ro:'tho 191',tr:'191 ara',role:'V - Yuklem'},{ro:'ton-nii',tr:'simdi',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Ambulans iste',th:'โทร 1669 เรียกรถพยาบาลครับ',ro:'tho 1669 riak rot-pha-yaa-baan khrap',tr:'1669u ara ambulans iste.',bd:[{ro:'tho 1669',tr:'1669 ara',role:'V - Yuklem'},{ro:'riak rot-pha-yaa-baan',tr:'ambulans cagir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Itfaiye cagri',th:'โทร 199 มีไฟไหม้ครับ',ro:'tho 199 mii fai-mai khrap',tr:'199u ara yangin var de.',bd:[{ro:'tho 199',tr:'199 ara',role:'V - Yuklem'},{ro:'mii fai-mai',tr:'yangin var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Kayboldugunu soyle',th:'ผมหลงทางครับ',ro:'pom long-thaang khrap',tr:'Kayboldum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'long-thaang',tr:'kayboldum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Hirsizlik bildir',th:'กระเป๋าผมโดนขโมยครับ',ro:'gra-bpao pom don kha-mooi khrap',tr:'Cantam calindi.',bd:[{ro:'gra-bpao pom',tr:'cantam',role:'S - Ozne'},{ro:'don kha-mooi',tr:'calindi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Guvenli yer sor',th:'ที่นี่ปลอดภัยไหมครับ',ro:'thii-nii bplod-phai mai khrap',tr:'Burasi guvenli mi?',bd:[{ro:'thii-nii',tr:'burasi',role:'S - Ozne'},{ro:'bplod-phai mai',tr:'guvenli mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Konum bildir',th:'ผมอยู่ที่หาดกะรนครับ',ro:'pom yuu thii haat Ka-ron khrap',tr:'Karon plajindayim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu thii haat Ka-ron',tr:'Karon plajinda',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🚨 Patongda Kaybolma',
     lines:[
       {s:'Ali',th:'ผมหลงทางครับ อยู่ป่าตองครับ',ro:'pom long-thaang khrap yuu Pa-tong khrap',tr:'Kayboldum Patongdayim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'long-thaang yuu Pa-tong',tr:'Patongda kayboldu',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ไม่ต้องตกใจค่ะ อยู่ตรงไหนคะ',ro:'mai tong dtok-jai kha yuu trong-nai kha',tr:'Panik yapmayin neredesiniz?',bd:[{ro:'mai tong dtok-jai',tr:'panik yapma',role:'Olumsuz'},{ro:'yuu trong-nai',tr:'neredesin',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ผมอยู่หน้าเซเว่นครับ',ro:'pom yuu naa seven khrap',tr:'Seven Eleven onundeyim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu naa seven',tr:'Seven onunde',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'โอเคค่ะ เดี๋ยวส่งโลเคชันให้ค่ะ',ro:'o-khee kha diao song lo-kay-shan hai kha',tr:'Tamam konum gonderiyorum.',bd:[{ro:'o-khee',tr:'tamam',role:'Durum'},{ro:'song lo-kay-shan hai',tr:'konum gonder',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'👮 Hirsizlik Bildirimi',
     lines:[
       {s:'Ali',th:'กระเป๋าผมโดนขโมยครับ',ro:'gra-bpao pom don kha-mooi khrap',tr:'Cantam calindi.',bd:[{ro:'gra-bpao pom',tr:'cantam',role:'S - Ozne'},{ro:'don kha-mooi',tr:'calindi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ของหายที่ไหนคะ',ro:'khong haai thii-nai kha',tr:'Nerede kayboldu?',bd:[{ro:'khong haai thii-nai',tr:'esya nerede kayip',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ที่หาดกะตะครับ',ro:'thii haat Ka-ta khrap',tr:'Kata plajinda.',bd:[{ro:'thii haat Ka-ta',tr:'Kata plajinda',role:'Yer'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'โทร 191 แล้วไปแจ้งความนะคะ',ro:'tho 191 laeo bpai jaeng-khwaam na kha',tr:'191i ara sonra sikayet et.',bd:[{ro:'tho 191',tr:'191 ara',role:'V - Yuklem'},{ro:'bpai jaeng-khwaam',tr:'sikayet et',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ครับ ผมจะโทรเลยครับ',ro:'khrap pom ja tho loey khrap',tr:'Tamam hemen arayacagim.',bd:[{ro:'pom ja tho loey',tr:'hemen arayacagim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🔥 Otelde Yangin',
     lines:[
       {s:'Ali',th:'ไฟไหม้ครับ ที่ชั้นสามครับ',ro:'fai-mai khrap thii chan saam khrap',tr:'Yangin var ucuncu katta.',bd:[{ro:'fai-mai',tr:'yangin var',role:'V - Yuklem'},{ro:'thii chan saam',tr:'ucuncu katta',role:'Yer'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'โทร 199 แล้วหรือยังคะ',ro:'tho 199 laeo rue-yang kha',tr:'199 arandi mi?',bd:[{ro:'tho 199 laeo rue-yang',tr:'199 arandi mi',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'โทรแล้วครับ คนกำลังออกจากตึกครับ',ro:'tho laeo khrap khon gam-lang ok jaak tuek khrap',tr:'Aradim insanlar cikiyor.',bd:[{ro:'tho laeo',tr:'aradi',role:'V - Yuklem'},{ro:'khon gam-lang ok jaak tuek',tr:'insanlar binadan cikiyor',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ดีมากค่ะ ไปที่ปลอดภัยนะคะ',ro:'dii maak kha bpai thii bplod-phai na kha',tr:'Cok iyi guvenli yere gecin.',bd:[{ro:'dii maak',tr:'cok iyi',role:'Durum'},{ro:'bpai thii bplod-phai',tr:'guvenli yere git',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🚑 Acil Saglik Cagrisi',
     lines:[
       {s:'Ali',th:'ช่วยด้วยครับ เพื่อนผมหมดสติครับ',ro:'chuay duay khrap phuean pom mot-sa-dti khrap',tr:'Yardim edin arkadasim bilincsiz.',bd:[{ro:'chuay duay',tr:'yardim edin',role:'V - Yuklem'},{ro:'phuean pom mot-sa-dti',tr:'arkadasim bilincsiz',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'โทร 1669 ทันทีค่ะ',ro:'tho 1669 than-thii kha',tr:'Hemen 1669u arayin.',bd:[{ro:'tho 1669 than-thii',tr:'hemen 1669 ara',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ผมอยู่ที่หาดกะรนครับ',ro:'pom yuu thii haat Ka-ron khrap',tr:'Karon plajindayim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu thii haat Ka-ron',tr:'Karon plajinda',role:'Yer'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'รับทราบค่ะ รถพยาบาลกำลังไปค่ะ',ro:'rap-saap kha rot-pha-yaa-baan gam-lang bpai kha',tr:'Anlasildi ambulans yolda.',bd:[{ro:'rap-saap',tr:'anlasildi',role:'V - Yuklem'},{ro:'rot-pha-yaa-baan gam-lang bpai',tr:'ambulans geliyor',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'ช่วยด้วยครับ',q:'Ali ne istiyor?',opts:['Yemek','Yardim','Ulasim'],c:1},
    {diff:'easy',th:'โทร 191 ตอนนี้ครับ',q:'Hangi kurum aranacak?',opts:['Itfaiye','Polis','Ambulans'],c:1},
    {diff:'easy',th:'ไฟไหม้ครับ',q:'Durum nedir?',opts:['Yangin','Trafik','Yagmur'],c:0},
    {diff:'medium',th:'ผมหลงทางที่ป่าตองครับ',q:'Ali ne sorunu yasiyor?',opts:['Kayboldu','Telefonu calindi','Yaralandi'],c:0},
    {diff:'medium',th:'กระเป๋าผมโดนขโมยครับ',q:'Ne calindi?',opts:['Pasaport','Canta','Araba'],c:1},
    {diff:'medium',th:'ที่นี่ปลอดภัยไหมครับ',q:'Ne soruyor?',opts:['Fiyat','Guvenlik','Yol tarifi'],c:1},
    {diff:'medium',th:'บอกที่อยู่ให้ 1669 ครับ',q:'Neden adres veriyor?',opts:['Ambulans yonlendirmek','Otel rezervasyonu','Taksi cagrisi'],c:0},
    {diff:'hard',th:'ตรงนี้อันตรายมากครับ',q:'En iyi tepki nedir?',opts:['Orada kalmak','Guvenli bolgeye gecmek','Fotograf cekmek'],c:1},
    {diff:'hard',th:'โทร 199 ด่วนครับ',q:'Hangi olay muhtemel?',opts:['Yangin','Hirsizlik','Kaybolma'],c:0},
    {diff:'hard',th:'เพื่อนผมหมดสติครับ',q:'Hangi numara en dogru?',opts:['191','1669','199'],c:1},
  ],
  quiz:[
    {q:'"chuay duay" ne demek?',opts:['Bekle','Yardim et','Git','Ara'],c:1},
    {q:'Yangin acil numarasi hangisi?',opts:['191','1669','199','1155'],c:2},
    {q:'Polis acil numarasi hangisi?',opts:['199','1669','191','1555'],c:2},
    {q:'Ambulans acil numarasi hangisi?',opts:['1669','191','199','1111'],c:0},
    {q:'"pom long-thaang" ne demek?',opts:['Yoruldum','Kayboldum','Aciktim','Uykuluyum'],c:1},
    {q:'"don kha-mooi" ne demek?',opts:['Bulundu','Calindi','Satisa cikti','Tamir edildi'],c:1},
    {q:'"an-ta-raai" ne demek?',opts:['Tehlike','Guvenli','Sakin','Yardim'],c:0},
    {q:'"bplod-phai" ne demek?',opts:['Kalabalik','Guvenli','Yasak','Acil'],c:1},
    {q:'Acil aramada hangi bilgi kritik?',opts:['Fiyat','Adres','Hava durumu','Menu'],c:1},
    {q:'Hirsizlikte ilk adim nedir?',opts:['191 aramak','199 aramak','1669 aramak','Eve donmek'],c:0},
  ],
};

LESSONS[12] = L12;
