// Ders 11 verisi — tayca-v3
// =================== VERI: DERS 11 — Hastane ve Eczane ===================
const L11 = {
  tones:[],
  words:[
    {id:'w1',th:'โรงพยาบาล',ro:'rong-pha-yaa-baan',tr:'Hastane',
     tip:'Buyuk hastaneler Phuket Townda yogundur.',
     ctx:'Acil durumda en hizli rota ile hastaneye git.',
     examples:[
       {th:'ผมต้องไปโรงพยาบาลครับ',ro:'pom tong bpai rong-pha-yaa-baan khrap',tr:'Hastaneye gitmem gerekiyor.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'tong bpai rong-pha-yaa-baan',tr:'hastaneye gitmeli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โรงพยาบาลใกล้ที่สุดอยู่ที่ไหนครับ',ro:'rong-pha-yaa-baan glai thii-sut yuu thii-nai khrap',tr:'En yakin hastane nerede?',bd:[{ro:'rong-pha-yaa-baan glai thii-sut',tr:'en yakin hastane',role:'S - Ozne'},{ro:'yuu thii-nai',tr:'nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'พาไปโรงพยาบาลด่วนครับ',ro:'phaa bpai rong-pha-yaa-baan duan khrap',tr:'Acil hastaneye goturun.',bd:[{ro:'phaa bpai rong-pha-yaa-baan',tr:'hastaneye gotur',role:'V - Yuklem'},{ro:'duan',tr:'acil',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมอยู่โรงพยาบาลป่าตองครับ',ro:'pom yuu rong-pha-yaa-baan Pa-tong khrap',tr:'Patong hastanesindeyim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu rong-pha-yaa-baan Pa-tong',tr:'Patong hastanesinde',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'ร้านขายยา',ro:'raan-khaai-yaa',tr:'Eczane',
     tip:'Raan khaai yaa sozlukte ilac satan dukkan demektir.',
     ctx:'Kucuk sikayetlerde once eczane tercih edilir.',
     examples:[
       {th:'มีร้านขายยาใกล้ๆ ไหมครับ',ro:'mii raan-khaai-yaa glai-glai mai khrap',tr:'Yakinda eczane var mi?',bd:[{ro:'mii raan-khaai-yaa glai-glai mai',tr:'yakinda eczane var mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมจะไปซื้อยาที่ร้านขายยาครับ',ro:'pom ja bpai sue yaa thii raan-khaai-yaa khrap',tr:'Eczaneden ilac alacagim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'ja bpai sue yaa thii raan-khaai-yaa',tr:'eczaneden ilac alacak',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ร้านขายยาเปิด 24 ชั่วโมงไหมครับ',ro:'raan-khaai-yaa bpoet yi-sip-sii chua-mong mai khrap',tr:'Eczane 24 saat acik mi?',bd:[{ro:'raan-khaai-yaa',tr:'eczane',role:'S - Ozne'},{ro:'bpoet yi-sip-sii chua-mong mai',tr:'24 saat acik mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'ปวด',ro:'bpuat',tr:'Agri',
     tip:'Bpuat vucudun farkli bolgeleri ile kullanilir.',
     ctx:'Bas agri, karin agri gibi sikayetleri anlatir.',
     examples:[
       {th:'ผมปวดหัวครับ',ro:'pom bpuat hua khrap',tr:'Basim agriyor.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'bpuat hua',tr:'bas agrisi var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมปวดท้องมากครับ',ro:'pom bpuat thong maak khrap',tr:'Karnim cok agriyor.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'bpuat thong maak',tr:'karin cok agriyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ปวดตรงนี้ครับ',ro:'bpuat trong-nii khrap',tr:'Burasi agriyor.',bd:[{ro:'bpuat trong-nii',tr:'burasi agriyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'เมื่อคืนปวดมากจนหลับไม่ได้ครับ',ro:'muea-khuen bpuat maak jon lap mai dai khrap',tr:'Dun gece cok agri oldugu icin uyuyamadim.',bd:[{ro:'muea-khuen',tr:'dun gece',role:'Zaman'},{ro:'bpuat maak jon lap mai dai',tr:'cok agri yuzunden uyuyamadi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'ไข้',ro:'khai',tr:'Ates',
     tip:'Khai hem ates hem hastalik hissi icin kullanilir.',
     ctx:'Ates olcumu icin termometre istenebilir.',
     examples:[
       {th:'ผมมีไข้ครับ',ro:'pom mii khai khrap',tr:'Atesim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'mii khai',tr:'ates var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ไข้สูงไหมครับ',ro:'khai suung mai khrap',tr:'Ates yuksek mi?',bd:[{ro:'khai',tr:'ates',role:'S - Ozne'},{ro:'suung mai',tr:'yuksek mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'วัดไข้ให้หน่อยครับ',ro:'wat khai hai noi khrap',tr:'Atesimi olcer misiniz?',bd:[{ro:'wat khai hai',tr:'ates olc',role:'V - Yuklem'},{ro:'noi',tr:'lutfen',role:'Kibar'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'ยา',ro:'yaa',tr:'Ilac',
     tip:'Yaa genel ilac kelimesidir.',
     ctx:'Doz ve kullanim suresi mutlaka sorulmali.',
     examples:[
       {th:'ขอยาแก้ปวดครับ',ro:'khor yaa gae-bpuat khrap',tr:'Agri kesici istiyorum.',bd:[{ro:'khor yaa gae-bpuat',tr:'agri kesici istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ยานี้กินวันละกี่ครั้งครับ',ro:'yaa nii gin wan-la gii khrang khrap',tr:'Bu ilac gunde kac kez alinir?',bd:[{ro:'yaa nii',tr:'bu ilac',role:'S - Ozne'},{ro:'gin wan-la gii khrang',tr:'gunde kac kez kullan',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'กินยาหลังอาหารครับ',ro:'gin yaa lang aa-haan khrap',tr:'Ilaci yemekten sonra al.',bd:[{ro:'gin yaa',tr:'ilac almak',role:'V - Yuklem'},{ro:'lang aa-haan',tr:'yemekten sonra',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมแพ้ยานี้ครับ',ro:'pom phae yaa nii khrap',tr:'Bu ilaca alerjim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'phae yaa nii',tr:'bu ilaca alerjim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'หมอ',ro:'mor',tr:'Doktor',
     tip:'Mor gunluk konusmada doktor icin en yaygin kelime.',
     ctx:'Hastanede kayit yaparken doktor istemek gerekir.',
     examples:[
       {th:'ขอพบหมอครับ',ro:'khor phop mor khrap',tr:'Doktorla gorusmek istiyorum.',bd:[{ro:'khor phop mor',tr:'doktoru gormek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'หมออยู่ไหมครับ',ro:'mor yuu mai khrap',tr:'Doktor burada mi?',bd:[{ro:'mor',tr:'doktor',role:'S - Ozne'},{ro:'yuu mai',tr:'burada mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'หมอพูดอังกฤษได้ไหมครับ',ro:'mor phuut ang-grit dai mai khrap',tr:'Doktor Ingilizce konusabiliyor mu?',bd:[{ro:'mor',tr:'doktor',role:'S - Ozne'},{ro:'phuut ang-grit dai mai',tr:'Ingilizce konusabilir mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'ใบสั่งยา',ro:'bai-sang-yaa',tr:'Recete',
     tip:'Hastane sonrasi ilac almak icin recete gerekir.',
     ctx:'Receteyi eczanede gostererek ilac alirsin.',
     examples:[
       {th:'นี่ใบสั่งยาครับ',ro:'nii bai-sang-yaa khrap',tr:'Bu benim recetem.',bd:[{ro:'nii',tr:'bu',role:'S - Ozne'},{ro:'bai-sang-yaa',tr:'recete',role:'Nesne'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ขอใบสั่งยาด้วยครับ',ro:'khor bai-sang-yaa duay khrap',tr:'Lutfen recete de verin.',bd:[{ro:'khor bai-sang-yaa duay',tr:'recete de istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ร้านขายยารับใบสั่งยานี้ไหมครับ',ro:'raan-khaai-yaa rap bai-sang-yaa nii mai khrap',tr:'Bu recete eczanede gecerli mi?',bd:[{ro:'raan-khaai-yaa rap bai-sang-yaa nii mai',tr:'eczane bu receteyi kabul eder mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ใบสั่งยานี้ใช้ได้สามวันครับ',ro:'bai-sang-yaa nii chai dai saam wan khrap',tr:'Bu recete uc gun gecerli.',bd:[{ro:'bai-sang-yaa nii',tr:'bu recete',role:'S - Ozne'},{ro:'chai dai saam wan',tr:'uc gun gecerli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'แพ้',ro:'phae',tr:'Alerji',
     tip:'Phae kelimesi hem alerji hem tepki anlaminda kullanilir.',
     ctx:'Ilac veya gida alerjisi mutlaka belirtilmeli.',
     examples:[
       {th:'ผมแพ้อาหารทะเลครับ',ro:'pom phae aa-haan tha-lay khrap',tr:'Deniz urunlerine alerjim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'phae aa-haan tha-lay',tr:'deniz urunlerine alerjim var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมแพ้เพนิซิลลินครับ',ro:'pom phae pe-ni-sin khrap',tr:'Penisiline alerjim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'phae pe-ni-sin',tr:'penisilin alerjisi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'มีผื่นเพราะแพ้ครับ',ro:'mii phuen phro phae khrap',tr:'Alerjiden dolayi dokuntu var.',bd:[{ro:'mii phuen',tr:'dokuntu var',role:'V - Yuklem'},{ro:'phro phae',tr:'alerjiden dolayi',role:'Neden'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'ประกัน',ro:'pra-gan',tr:'Sigorta',
     tip:'Saglik sigortasi hastane islemlerini hizlandirir.',
     ctx:'Kabul masasi once sigorta evragini isteyebilir.',
     examples:[
       {th:'ผมมีประกันสุขภาพครับ',ro:'pom mii pra-gan suk-kha-phap khrap',tr:'Saglik sigortam var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'mii pra-gan suk-kha-phap',tr:'saglik sigortasi var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ประกันนี้ใช้ที่นี่ได้ไหมครับ',ro:'pra-gan nii chai thii-nii dai mai khrap',tr:'Bu sigorta burada gecerli mi?',bd:[{ro:'pra-gan nii',tr:'bu sigorta',role:'S - Ozne'},{ro:'chai thii-nii dai mai',tr:'burada gecerli mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ช่วยติดต่อประกันให้หน่อยครับ',ro:'chuay dtit-dtor pra-gan hai noi khrap',tr:'Lutfen sigortamla iletisime gecin.',bd:[{ro:'chuay dtit-dtor pra-gan hai',tr:'sigortayla iletisime gec',role:'V - Yuklem'},{ro:'noi',tr:'lutfen',role:'Kibar'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'รถพยาบาล',ro:'rot-pha-yaa-baan',tr:'Ambulans',
     tip:'Acil ambulans numarasi Tayland genelinde 1669 dur.',
     ctx:'Bilinc kaybi veya ciddi yaralanmada hemen 1669 ara.',
     examples:[
       {th:'เรียกรถพยาบาลด่วนครับ',ro:'riak rot-pha-yaa-baan duan khrap',tr:'Acil ambulans cagir.',bd:[{ro:'riak rot-pha-yaa-baan',tr:'ambulans cagir',role:'V - Yuklem'},{ro:'duan',tr:'acil',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'โทร 1669 ได้เลยครับ',ro:'tho nueng-hok-hok-kao dai loey khrap',tr:'Hemen 1669u arayabilirsiniz.',bd:[{ro:'tho 1669',tr:'1669 ara',role:'V - Yuklem'},{ro:'dai loey',tr:'hemen yapabilir',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'รถพยาบาลกำลังมาครับ',ro:'rot-pha-yaa-baan gam-lang maa khrap',tr:'Ambulans geliyor.',bd:[{ro:'rot-pha-yaa-baan',tr:'ambulans',role:'S - Ozne'},{ro:'gam-lang maa',tr:'geliyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {th:'ผมอยู่ที่ป่าตอง ช่วยส่งรถพยาบาลครับ',ro:'pom yuu thii Pa-tong chuay song rot-pha-yaa-baan khrap',tr:'Patongdayim, ambulans gonderin lutfen.',bd:[{ro:'pom yuu thii Pa-tong',tr:'Patongdayim',role:'S - Ozne'},{ro:'chuay song rot-pha-yaa-baan',tr:'ambulans gonderin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. Hastalik Belirtisi Anlatma',
      formula:'POM + [BELIRTI] + KHRAP = benim ... var',
      explain:'Doktora veya eczaciya net belirti anlatmak icin kisaltma kalibi.',
      tips:['pom = ben erkek','bpuat = agri','mii khai = ates var','muea-khuen = dun gece','maak = cok'],
      examples:[
        {th:'ผมปวดหัวมากครับ',ro:'pom bpuat hua maak khrap',tr:'Basim cok agriyor.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'bpuat hua maak',tr:'basim cok agriyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมมีไข้ตั้งแต่เมื่อคืนครับ',ro:'pom mii khai dtang-tae muea-khuen khrap',tr:'Dun geceden beri atesim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'mii khai dtang-tae muea-khuen',tr:'dun geceden beri ates var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมปวดท้องและเวียนหัวครับ',ro:'pom bpuat thong lae wian-hua khrap',tr:'Karin agrisi ve bas donmesi var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'bpuat thong lae wian-hua',tr:'karin agri ve bas donmesi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมหายใจไม่ค่อยออกครับ',ro:'pom haai-jai mai khoi ok khrap',tr:'Rahat nefes alamiyorum.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'haai-jai mai khoi ok',tr:'iyi nefes alamiyor',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. Acil Yardim ve Numara Kullanimi',
      formula:'CHUAY + [FIIL] + DUAN = lutfen acil ...',
      explain:'Acil durumda ambulans cagirirken konum ve numarayi birlikte soylemek gerekir.',
      tips:['chuay duay = yardim edin','duan = acil','tho 1669 = ambulans','bawk thii-yuu = adresi soyle','rot-pha-yaa-baan = ambulans'],
      examples:[
        {th:'ช่วยเรียกรถพยาบาลด่วนครับ',ro:'chuay riak rot-pha-yaa-baan duan khrap',tr:'Lutfen acil ambulans cagir.',bd:[{ro:'chuay riak rot-pha-yaa-baan',tr:'ambulans cagir yardim et',role:'V - Yuklem'},{ro:'duan',tr:'acil',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'โทร 1669 ตอนนี้เลยครับ',ro:'tho 1669 ton-nii loey khrap',tr:'Simdi hemen 1669u ara.',bd:[{ro:'tho 1669',tr:'1669 ara',role:'V - Yuklem'},{ro:'ton-nii loey',tr:'simdi hemen',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมอยู่กะรน ส่งรถพยาบาลครับ',ro:'pom yuu Ka-ron song rot-pha-yaa-baan khrap',tr:'Karondayim ambulans gonderin.',bd:[{ro:'pom yuu Ka-ron',tr:'Karondayim',role:'S - Ozne'},{ro:'song rot-pha-yaa-baan',tr:'ambulans gonderin',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'คนไข้หมดสติครับ เร็วๆ ครับ',ro:'khon-khai mot-sa-dti khrap reo-reo khrap',tr:'Hasta bilincsiz, cabuk lutfen.',bd:[{ro:'khon-khai mot-sa-dti',tr:'hasta bilincsiz',role:'Durum'},{ro:'reo-reo',tr:'cabuk',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'En yakin hastaneyi sor',th:'โรงพยาบาลใกล้ที่สุดอยู่ที่ไหนครับ',ro:'rong-pha-yaa-baan glai thii-sut yuu thii-nai khrap',tr:'En yakin hastane nerede?',bd:[{ro:'rong-pha-yaa-baan glai thii-sut',tr:'en yakin hastane',role:'S - Ozne'},{ro:'yuu thii-nai',tr:'nerede',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Bas agrisini soyle',th:'ผมปวดหัวมากครับ',ro:'pom bpuat hua maak khrap',tr:'Basim cok agriyor.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'bpuat hua maak',tr:'bas agrisi cok',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Ates oldugunu soyle',th:'ผมมีไข้ครับ',ro:'pom mii khai khrap',tr:'Atesim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'mii khai',tr:'ates var',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Agri kesici iste',th:'ขอยาแก้ปวดครับ',ro:'khor yaa gae-bpuat khrap',tr:'Agri kesici istiyorum.',bd:[{ro:'khor yaa gae-bpuat',tr:'agri kesici istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Doktorla gorusme iste',th:'ขอพบหมอครับ',ro:'khor phop mor khrap',tr:'Doktorla gorusmek istiyorum.',bd:[{ro:'khor phop mor',tr:'doktoru gormek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Alerjini belirt',th:'ผมแพ้เพนิซิลลินครับ',ro:'pom phae pe-ni-sin khrap',tr:'Penisiline alerjim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'phae pe-ni-sin',tr:'penisilin alerjisi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Sigorta gecerliligini sor',th:'ประกันนี้ใช้ที่นี่ได้ไหมครับ',ro:'pra-gan nii chai thii-nii dai mai khrap',tr:'Bu sigorta burada gecerli mi?',bd:[{ro:'pra-gan nii',tr:'bu sigorta',role:'S - Ozne'},{ro:'chai thii-nii dai mai',tr:'burada gecerli mi',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'1669 ile ambulans iste',th:'โทร 1669 เรียกรถพยาบาลด่วนครับ',ro:'tho 1669 riak rot-pha-yaa-baan duan khrap',tr:'1669u ara ve acil ambulans cagir.',bd:[{ro:'tho 1669',tr:'1669 ara',role:'V - Yuklem'},{ro:'riak rot-pha-yaa-baan duan',tr:'acil ambulans cagir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🏥 Patong Hastane Kaydi',
     lines:[
       {s:'Ali',th:'สวัสดีครับ ผมปวดท้องมากครับ',ro:'sa-wat-dii khrap pom bpuat thong maak khrap',tr:'Merhaba karnim cok agriyor.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'bpuat thong maak',tr:'karin cok agriyor',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'มีไข้ไหมคะ',ro:'mii khai mai kha',tr:'Atesiniz var mi?',bd:[{ro:'mii khai mai',tr:'ates var mi',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'มีครับ เมื่อคืนเริ่มมีไข้ครับ',ro:'mii khrap muea-khuen roem mii khai khrap',tr:'Var, dun gece basladi.',bd:[{ro:'mii',tr:'var',role:'V - Yuklem'},{ro:'muea-khuen roem mii khai',tr:'dun gece ates basladi',role:'Zaman'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'กรุณารอสักครู่ เดี๋ยวพาไปพบหมอค่ะ',ro:'ga-ru-naa ro sak-khruu diao phaa bpai phop mor kha',tr:'Lutfen biraz bekleyin doktora goturecegim.',bd:[{ro:'ga-ru-naa ro sak-khruu',tr:'lutfen biraz bekleyin',role:'V - Yuklem'},{ro:'phaa bpai phop mor',tr:'doktora goturmek',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'💊 Karon Eczane',
     lines:[
       {s:'Ali',th:'ขอยาแก้ปวดกับยาแก้ไข้ครับ',ro:'khor yaa gae-bpuat gap yaa gae-khai khrap',tr:'Agri kesici ve ates ilaci istiyorum.',bd:[{ro:'khor yaa gae-bpuat gap yaa gae-khai',tr:'agri ve ates ilaci istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'แพ้ยาอะไรไหมคะ',ro:'phae yaa a-rai mai kha',tr:'Herhangi bir ilaca alerjiniz var mi?',bd:[{ro:'phae yaa a-rai mai',tr:'hangi ilaca alerji var mi',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ผมแพ้เพนิซิลลินครับ',ro:'pom phae pe-ni-sin khrap',tr:'Penisiline alerjim var.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'phae pe-ni-sin',tr:'penisilin alerjisi',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'เข้าใจค่ะ งั้นเอายาตัวนี้แทนค่ะ',ro:'khao-jai kha ngan ao yaa tua-nii thaen kha',tr:'Anladim o zaman bu ilaci veriyorum.',bd:[{ro:'khao-jai',tr:'anladim',role:'V - Yuklem'},{ro:'ao yaa tua-nii thaen',tr:'bu ilaci yerine ver',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ขอบคุณครับ',ro:'khop-khun khrap',tr:'Tesekkur ederim.',bd:[{ro:'khop-khun',tr:'tesekkur',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'📄 Sigorta ve Recete',
     lines:[
       {s:'Ali',th:'นี่ใบสั่งยาครับ',ro:'nii bai-sang-yaa khrap',tr:'Bu benim recetem.',bd:[{ro:'nii bai-sang-yaa',tr:'bu recete',role:'S - Ozne'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'มีประกันไหมคะ',ro:'mii pra-gan mai kha',tr:'Sigortaniz var mi?',bd:[{ro:'mii pra-gan mai',tr:'sigorta var mi',role:'Soru/Olumsuz'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'มีครับ นี่บัตรประกันครับ',ro:'mii khrap nii bat pra-gan khrap',tr:'Var, bu sigorta kartim.',bd:[{ro:'mii',tr:'var',role:'V - Yuklem'},{ro:'nii bat pra-gan',tr:'bu sigorta karti',role:'Nesne'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'ใช้ได้ค่ะ ค่ายาจะลดลงค่ะ',ro:'chai dai kha khaa yaa ja lot long kha',tr:'Gecerli ilac ucreti dusuyor.',bd:[{ro:'chai dai',tr:'gecerli',role:'V - Yuklem'},{ro:'khaa yaa ja lot long',tr:'ilac ucreti dusecek',role:'Durum'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {title:'🚑 1669 Acil Cagri',
     lines:[
       {s:'Ali',th:'ช่วยด้วยครับ คนหมดสติครับ',ro:'chuay duay khrap khon mot-sa-dti khrap',tr:'Yardim edin birisi bilincsiz.',bd:[{ro:'chuay duay',tr:'yardim edin',role:'V - Yuklem'},{ro:'khon mot-sa-dti',tr:'birisi bilincsiz',role:'Durum'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'โทร 1669 เลยค่ะ',ro:'tho 1669 loey kha',tr:'Hemen 1669u arayin.',bd:[{ro:'tho 1669 loey',tr:'hemen 1669 ara',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
       {s:'Ali',th:'ผมอยู่ที่หาดกะรนครับ',ro:'pom yuu thii haat Ka-ron khrap',tr:'Karon plajindayim.',bd:[{ro:'pom',tr:'ben',role:'S - Ozne'},{ro:'yuu thii haat Ka-ron',tr:'Karon plajinda',role:'Yer'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
       {s:'Nada',th:'รถพยาบาลกำลังไปค่ะ รอที่เดิมนะคะ',ro:'rot-pha-yaa-baan gam-lang bpai kha ro thii doem na kha',tr:'Ambulans yola cikti, ayni yerde bekleyin.',bd:[{ro:'rot-pha-yaa-baan gam-lang bpai',tr:'ambulans yolda',role:'V - Yuklem'},{ro:'ro thii doem',tr:'ayni yerde bekle',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  listening:[
    {diff:'easy',th:'ผมปวดหัวมากครับ',q:'Ali ne soyluyor?',opts:['Basi agriyor','Susadi','Uykusu var'],c:0},
    {diff:'easy',th:'มีร้านขายยาใกล้ๆ ไหมครับ',q:'Ne ariyor?',opts:['Otel','Eczane','Market'],c:1},
    {diff:'easy',th:'ผมมีไข้ครับ',q:'Durum nedir?',opts:['Atesi var','Bel agrisi var','Alerjisi var'],c:0},
    {diff:'medium',th:'ยานี้กินวันละกี่ครั้งครับ',q:'Ne soruyor?',opts:['Ilacin fiyati','Gunde kac kez kullanilacagi','Ilacin markasi'],c:1},
    {diff:'medium',th:'ผมแพ้เพนิซิลลินครับ',q:'Hangi bilgi veriliyor?',opts:['Sigortasi yok','Penisilin alerjisi var','Recetesi kayip'],c:1},
    {diff:'medium',th:'ประกันนี้ใช้ที่นี่ได้ไหมครับ',q:'Ne kontrol ediliyor?',opts:['Sigorta gecerliligi','Doktor uygunlugu','Randevu saati'],c:0},
    {diff:'medium',th:'ขอพบหมอครับ',q:'Ali ne istiyor?',opts:['Hemsire','Doktor','Eczaci'],c:1},
    {diff:'hard',th:'ช่วยเรียกรถพยาบาลด่วนครับ',q:'En dogru eylem ne?',opts:['Eczaneye gitmek','1669 ambulans cagirmak','Otele donmek'],c:1},
    {diff:'hard',th:'ผมอยู่ที่ป่าตอง ช่วยส่งรถพยาบาลครับ',q:'Neden konum veriyor?',opts:['Taksi cagirmak icin','Ambulans yonlendirmek icin','Arkadas bulmak icin'],c:1},
    {diff:'hard',th:'คนไข้หมดสติครับ เร็วๆ ครับ',q:'Durumun siddeti nedir?',opts:['Hafif','Orta','Cok acil'],c:2},
  ],
  quiz:[
    {q:'"rong-pha-yaa-baan" ne demek?',opts:['Eczane','Hastane','Klinik','Laboratuvar'],c:1},
    {q:'"raan-khaai-yaa" ne demek?',opts:['Eczane','Sigorta','Recete','Doktor'],c:0},
    {q:'"bpuat" ne demek?',opts:['Ates','Agri','Bulanti','Yorgunluk'],c:1},
    {q:'"khai" ne demek?',opts:['Ates','Alerji','Sigorta','Randevu'],c:0},
    {q:'"mor" ne demek?',opts:['Hemsire','Doktor','Eczaci','Hasta'],c:1},
    {q:'"bai-sang-yaa" ne demek?',opts:['Fatura','Recete','Kimlik','Rapor'],c:1},
    {q:'"phae" ne ifade eder?',opts:['Yorgunluk','Alerji','Bas donmesi','Enfeksiyon'],c:1},
    {q:'Tayland ambulans acil numarasi hangisi?',opts:['191','199','1669','1155'],c:2},
    {q:'"pra-gan" ne demek?',opts:['Sigorta','Ilac','Muayene','Acil servis'],c:0},
    {q:'Ciddi acil durumda once ne yapilir?',opts:['Ilac beklemek','1669 arayip konum vermek','Yuruyus yapmak','Ertesi gun gitmek'],c:1},
  ],
};

LESSONS[11] = L11;
