// Ders 16 verisi — tayca-v3
// =================== VERİ: DERS 16 — Thai Kulturu ===================
const L16 = {
  tones:[],
  words:[
    {id:'w1',th:'ไหว้',ro:'wai',tr:'Wai',
     tip:'Tayland selamlasma ve saygi jestidir.',
     ctx:'Phuket te yerel insanlarla ilk selamda kullanilir.',
     examples:[
      {th:'ผมไหว้ถูกไหมครับ',ro:'pom wai thuuk mai khrap',tr:'Wai hareketini dogru yaptim mi?',bd:[{ro:'pom wai thuuk mai',tr:'wai dogru mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ขอบคุณครับ ผมจะไหว้ก่อน',ro:'khop-khun khrap pom ja wai gon',tr:'Tesekkurler once wai yapacagim.',bd:[{ro:'pom ja wai gon',tr:'once wai yapacagim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w2',th:'วัด',ro:'wat',tr:'Tapinak',
     tip:'Budist tapinaklari icin temel kelime.',
     ctx:'Phuket old town cevresinde bircok wat bulunur.',
     examples:[
      {th:'วัดนี้สวยมากครับ',ro:'wat nii suai maak khrap',tr:'Bu tapinak cok guzel.',bd:[{ro:'wat nii suai maak',tr:'bu tapinak cok guzel',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'เราไปวัดตอนเช้าครับ',ro:'rao pai wat ton-chao khrap',tr:'Sabah tapinaga gidiyoruz.',bd:[{ro:'rao pai wat ton-chao',tr:'sabah tapinaga gidiyoruz',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w3',th:'พระพุทธรูป',ro:'phra-phut-tha-ruup',tr:'Buddha',
     tip:'Buddha heykeli icin kullanilir.',
     ctx:'Tapinak icinde saygili davranis gerekir.',
     examples:[
      {th:'อย่าชี้พระพุทธรูปนะครับ',ro:'yaa chii phra-phut-tha-ruup na khrap',tr:'Buddha heykelini isaret etmeyin lutfen.',bd:[{ro:'yaa chii phra-phut-tha-ruup',tr:'isaret etme',role:'Olumsuz'},{ro:'na khrap',tr:'onay eki',role:'Kibar'}]},
      {th:'พระพุทธรูปศักดิ์สิทธิ์ครับ',ro:'phra-phut-tha-ruup sak-sit khrap',tr:'Buddha heykeli kutsaldir.',bd:[{ro:'phra-phut-tha-ruup sak-sit',tr:'buddha heykeli kutsal',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w4',th:'ถอดรองเท้า',ro:'thot rong-thao',tr:'Ayakkabi cikarmak',
     tip:'Tapinaga girmeden once yapilir.',
     ctx:'Kulturel sayginin en temel kurali.',
     examples:[
      {th:'ก่อนเข้าวัดต้องถอดรองเท้าครับ',ro:'gon khao wat tong thot rong-thao khrap',tr:'Tapinaga girmeden once ayakkabi cikarilmali.',bd:[{ro:'gon khao wat tong thot rong-thao',tr:'tapinaga giris oncesi ayakkabi cikar',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมถอดรองเท้าแล้วครับ',ro:'pom thot rong-thao laeo khrap',tr:'Ayakkabilari cikardim.',bd:[{ro:'pom thot rong-thao laeo',tr:'ayakkabilari cikardim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w5',th:'ความเคารพทางวัฒนธรรม',ro:'khwaam-khao-rop thaang wat-tha-na-tham',tr:'Kulturel saygi',
     tip:'Yerel geleneklere uygun davranis demektir.',
     ctx:'Turist olarak cok onemli bir konu.',
     examples:[
      {th:'ผมอยากเรียนรู้ความเคารพทางวัฒนธรรมครับ',ro:'pom yaak rian-ruu khwaam-khao-rop thaang wat-tha-na-tham khrap',tr:'Kulturel saygiyi ogrenmek istiyorum.',bd:[{ro:'pom yaak rian-ruu khwaam-khao-rop thaang wat-tha-na-tham',tr:'kulturel saygiyi ogrenmek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ความเคารพทางวัฒนธรรมสำคัญมากครับ',ro:'khwaam-khao-rop thaang wat-tha-na-tham sam-khan maak khrap',tr:'Kulturel saygi cok onemli.',bd:[{ro:'khwaam-khao-rop thaang wat-tha-na-tham sam-khan maak',tr:'kulturel saygi cok onemli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w6',th:'เทศกาล',ro:'thet-sa-gaan',tr:'Festival',
     tip:'Yerel kutlama ve etkinlikler icin kullanilir.',
     ctx:'Phuket te yil boyu farkli festivaller olur.',
     examples:[
      {th:'เดือนนี้มีเทศกาลอะไรครับ',ro:'deuan nii mii thet-sa-gaan a-rai khrap',tr:'Bu ay hangi festival var?',bd:[{ro:'deuan nii mii thet-sa-gaan a-rai',tr:'bu ay hangi festival var',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมชอบเทศกาลท้องถิ่นครับ',ro:'pom chop thet-sa-gaan thong-thin khrap',tr:'Yerel festivalleri seviyorum.',bd:[{ro:'pom chop thet-sa-gaan thong-thin',tr:'yerel festivalleri seviyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w7',th:'สงกรานต์',ro:'song-kran',tr:'Songkran',
     tip:'Tay yeni yil su festivalidir.',
     ctx:'Nisan ayinda Phuket te cok coskulu kutlanir.',
     examples:[
      {th:'สงกรานต์สนุกมากครับ',ro:'song-kran sa-nuk maak khrap',tr:'Songkran cok eglenceli.',bd:[{ro:'song-kran sa-nuk maak',tr:'songkran cok eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'สงกรานต์คนเยอะมากครับ',ro:'song-kran khon yoe maak khrap',tr:'Songkran cok kalabalik.',bd:[{ro:'song-kran khon yoe maak',tr:'songkran cok kalabalik',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w8',th:'เสื้อผ้า',ro:'seua-phaa',tr:'Kiyafet',
     tip:'Tapinak ziyaretinde uygun kiyafet gerekir.',
     ctx:'Omuz ve diz kapali olmali.',
     examples:[
      {th:'เสื้อผ้าของผมสุภาพไหมครับ',ro:'seua-phaa khong pom su-phaap mai khrap',tr:'Kiyafetim uygun mu?',bd:[{ro:'seua-phaa khong pom su-phaap mai',tr:'kiyafetim uygun mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมใส่เสื้อผ้ายาวครับ',ro:'pom sai seua-phaa yaao khrap',tr:'Uzun kiyafet giydim.',bd:[{ro:'pom sai seua-phaa yaao',tr:'uzun kiyafet giydim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w9',th:'หัว',ro:'hua',tr:'Bas',
     tip:'Tay kulturunde basin dokunulmazligi onemlidir.',
     ctx:'Baska kisinin basina dokunmak saygisizlik sayilir.',
     examples:[
      {th:'อย่าแตะหัวคนอื่นนะครับ',ro:'yaa tae hua khon uen na khrap',tr:'Baskasinin basina dokunmayin.',bd:[{ro:'yaa tae hua khon uen',tr:'baskasinin basina dokunma',role:'Olumsuz'},{ro:'na khrap',tr:'onay eki',role:'Kibar'}]},
      {th:'หัวเป็นส่วนที่สำคัญครับ',ro:'hua pen suan thii sam-khan khrap',tr:'Bas onemli bir bolgedir.',bd:[{ro:'hua pen suan thii sam-khan',tr:'bas onemli bolgedir',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
    {id:'w10',th:'ความสุภาพ',ro:'khwaam-su-phaap',tr:'Kibarlik',
     tip:'Nazik konusma ve davranisi anlatir.',
     ctx:'Turist icin en guvenli davranis her zaman kibarliktir.',
     examples:[
      {th:'ความสุภาพสำคัญมากในไทยครับ',ro:'khwaam-su-phaap sam-khan maak nai thai khrap',tr:'Taylandda kibarlik cok onemli.',bd:[{ro:'khwaam-su-phaap sam-khan maak nai thai',tr:'taylandda kibarlik cok onemli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {th:'ผมพูดช้าๆ อย่างสุภาพครับ',ro:'pom phuut chaa-chaa yaang su-phaap khrap',tr:'Nazikce ve yavas konusuyorum.',bd:[{ro:'pom phuut chaa-chaa yaang su-phaap',tr:'nazikce yavas konusuyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
     ]},
  ],
  grammar:[
    {
      title:'1. Tapinak Nezaketi',
      formula:'GON + [FIIL] + TONG + [KURAL] = once ... gerekir',
      explain:'Tapinak ziyaretinde kurallari anlatmak icin kullanilir.',
      tips:['gon = once','tong = gerekir','thot rong-thao = ayakkabi cikar','yaa = yapma','su-phaap = kibar','wai = selamla'],
      examples:[
        {th:'ก่อนเข้าวัดต้องถอดรองเท้าครับ',ro:'gon khao wat tong thot rong-thao khrap',tr:'Tapinaga girmeden once ayakkabi cikarmak gerekir.',bd:[{ro:'gon khao wat tong thot rong-thao',tr:'tapinaga girmeden ayakkabi cikar',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ควรไหว้ก่อนพูดครับ',ro:'khuan wai gon phuut khrap',tr:'Konusmadan once wai yapmak iyi olur.',bd:[{ro:'khuan wai gon phuut',tr:'konusmadan once wai',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'อย่าใส่เสื้อผ้าสั้นเข้าวัดครับ',ro:'yaa sai seua-phaa san khao wat khrap',tr:'Kisa kiyafetle tapinaga girmeyin.',bd:[{ro:'yaa sai seua-phaa san khao wat',tr:'kisa kiyafetle tapinaga girme',role:'Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'พูดอย่างสุภาพกับพระครับ',ro:'phuut yaang su-phaap gap phra khrap',tr:'Rahiplerle kibar konusun.',bd:[{ro:'phuut yaang su-phaap gap phra',tr:'rahiple kibar konus',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
    {
      title:'2. Kulturel Saygi Ifadeleri',
      formula:'POM YAAK + [FIIL] + PHUEA + [AMAC] = ... icin istiyorum',
      explain:'Yerel kulturu ogrenme niyetini kibarca gostermeye yarar.',
      tips:['pom yaak = istiyorum','rian-ruu = ogrenmek','khao-rop = saygi','wat-tha-na-tham = kultur','sam-khan = onemli','sa-nuk = eglenceli'],
      examples:[
        {th:'ผมอยากเรียนรู้วัฒนธรรมไทยครับ',ro:'pom yaak rian-ruu wat-tha-na-tham thai khrap',tr:'Tay kulturunu ogrenmek istiyorum.',bd:[{ro:'pom yaak rian-ruu wat-tha-na-tham thai',tr:'tay kulturunu ogrenmek istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมอยากเคารพประเพณีท้องถิ่นครับ',ro:'pom yaak khao-rop pra-phee-nii thong-thin khrap',tr:'Yerel geleneklere saygi gostermek istiyorum.',bd:[{ro:'pom yaak khao-rop pra-phee-nii thong-thin',tr:'yerel geleneklere saygi gostermek',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ความสุภาพสำคัญมากครับ',ro:'khwaam-su-phaap sam-khan maak khrap',tr:'Kibarlik cok onemli.',bd:[{ro:'khwaam-su-phaap sam-khan maak',tr:'kibarlik cok onemli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
        {th:'ผมชอบเทศกาลสงกรานต์ครับ',ro:'pom chop thet-sa-gaan song-kran khrap',tr:'Songkran festivalini seviyorum.',bd:[{ro:'pom chop thet-sa-gaan song-kran',tr:'songkran festivalini seviyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      ]
    },
  ],
  speaking:[
    {task:'Wai selami ver',th:'สวัสดีครับ ผมขอไหว้ครับ',ro:'sa-wat-dii khrap pom khor wai khrap',tr:'Merhaba wai ile selamliyorum.',bd:[{ro:'pom khor wai',tr:'wai ile selam',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Tapinak sor',th:'วัดนี้เปิดกี่โมงครับ',ro:'wat nii poet gii-moong khrap',tr:'Bu tapinak kacta aciliyor?',bd:[{ro:'wat nii poet gii-moong',tr:'tapinak kacta aciliyor',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Ayakkabi cikar',th:'ผมถอดรองเท้าแล้วครับ',ro:'pom thot rong-thao laeo khrap',tr:'Ayakkabilari cikardim.',bd:[{ro:'pom thot rong-thao laeo',tr:'ayakkabilari cikardim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Kulturel saygi soyle',th:'ผมเคารพวัฒนธรรมไทยครับ',ro:'pom khao-rop wat-tha-na-tham thai khrap',tr:'Tay kulturune saygi duyuyorum.',bd:[{ro:'pom khao-rop wat-tha-na-tham thai',tr:'tay kulturune saygi duyuyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Festival sor',th:'เดือนนี้มีเทศกาลอะไรครับ',ro:'deuan nii mii thet-sa-gaan a-rai khrap',tr:'Bu ay hangi festival var?',bd:[{ro:'deuan nii mii thet-sa-gaan a-rai',tr:'bu ay hangi festival var',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Songkran yorumu yap',th:'สงกรานต์สนุกมากครับ',ro:'song-kran sa-nuk maak khrap',tr:'Songkran cok eglenceli.',bd:[{ro:'song-kran sa-nuk maak',tr:'songkran cok eglenceli',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Kiyafet uygun mu sor',th:'เสื้อผ้านี้สุภาพไหมครับ',ro:'seua-phaa nii su-phaap mai khrap',tr:'Bu kiyafet uygun mu?',bd:[{ro:'seua-phaa nii su-phaap mai',tr:'kiyafet uygun mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
    {task:'Kibarlik belirt',th:'ผมพยายามพูดอย่างสุภาพครับ',ro:'pom pha-yaa-yaam phuut yaang su-phaap khrap',tr:'Kibar konusmaya calisiyorum.',bd:[{ro:'pom pha-yaa-yaam phuut yaang su-phaap',tr:'kibar konusmaya calisiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
  ],
  dialogues:[
    {title:'🙏 Wai ve Selamlama',
     lines:[
      {s:'Ali',th:'สวัสดีครับ ผมชื่ออาลีครับ',ro:'sa-wat-dii khrap pom chue ali khrap',tr:'Merhaba ben Ali.',bd:[{ro:'pom chue ali',tr:'ben ali',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'สวัสดีค่ะ ยินดีต้อนรับสู่ภูเก็ต',ro:'sa-wat-dii kha yin-dii ton-rap suu phu-ket',tr:'Merhaba Phukete hos geldiniz.',bd:[{ro:'yin-dii ton-rap suu phu-ket',tr:'phukete hos geldiniz',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ผมไหว้ถูกไหมครับ',ro:'pom wai thuuk mai khrap',tr:'Wai hareketim dogru mu?',bd:[{ro:'pom wai thuuk mai',tr:'wai dogru mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ถูกค่ะ คุณสุภาพมาก',ro:'thuuk kha khun su-phaap maak',tr:'Dogru cok kibarsiniz.',bd:[{ro:'khun su-phaap maak',tr:'cok kibarsiniz',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
    ]},
    {title:'🛕 Tapinak Ziyareti',
     lines:[
      {s:'Ali',th:'ก่อนเข้าวัดต้องทำอะไรครับ',ro:'gon khao wat tong tham a-rai khrap',tr:'Tapinaga girmeden once ne yapmaliyim?',bd:[{ro:'gon khao wat tong tham a-rai',tr:'girmeden once ne yapmali',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ต้องถอดรองเท้าและแต่งตัวสุภาพค่ะ',ro:'tong thot rong-thao lae taeng-tua su-phaap kha',tr:'Ayakkabi cikarin ve uygun giyinin.',bd:[{ro:'tong thot rong-thao',tr:'ayakkabi cikar',role:'V - Yuklem'},{ro:'taeng-tua su-phaap',tr:'uygun giyin',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'เข้าใจครับ ขอบคุณครับ',ro:'khao-jai khrap khop-khun khrap',tr:'Anladim tesekkurler.',bd:[{ro:'khao-jai',tr:'anladim',role:'Kelime'},{ro:'khop-khun',tr:'tesekkurler',role:'Kelime'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ยินดีค่ะ',ro:'yin-dii kha',tr:'Rica ederim.',bd:[{ro:'yin-dii',tr:'rica ederim',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
    ]},
    {title:'💦 Songkran Sohbeti',
     lines:[
      {s:'Ali',th:'สงกรานต์เริ่มวันไหนครับ',ro:'song-kran roem wan-nai khrap',tr:'Songkran hangi gun basliyor?',bd:[{ro:'song-kran roem wan-nai',tr:'songkran hangi gun basliyor',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'เริ่มกลางเดือนเมษายนค่ะ',ro:'roem glaang deuan me-saa-yon kha',tr:'Nisan ortasinda baslar.',bd:[{ro:'roem glaang deuan me-saa-yon',tr:'nisan ortasi baslar',role:'Kelime'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'ผมอยากไปร่วมเทศกาลครับ',ro:'pom yaak pai ruam thet-sa-gaan khrap',tr:'Festivale katilmak istiyorum.',bd:[{ro:'pom yaak pai ruam thet-sa-gaan',tr:'festivale katilmak istiyorum',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ดีมากค่ะ สนุกแน่นอน',ro:'dii maak kha sa-nuk nae-non',tr:'Harika kesinlikle eglenceli olur.',bd:[{ro:'sa-nuk nae-non',tr:'kesinlikle eglenceli',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
    ]},
    {title:'👕 Kiyafet ve Saygi',
     lines:[
      {s:'Ali',th:'เสื้อผ้านี้สุภาพพอไหมครับ',ro:'seua-phaa nii su-phaap pho mai khrap',tr:'Bu kiyafet yeterince uygun mu?',bd:[{ro:'seua-phaa nii su-phaap pho mai',tr:'kiyafet yeterince uygun mu',role:'Soru/Olumsuz'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'สุภาพค่ะ แต่ควรใส่กางเกงยาว',ro:'su-phaap kha tae khuan sai gaang-geng yaao',tr:'Uygun ama uzun pantolon daha iyi.',bd:[{ro:'su-phaap',tr:'uygun',role:'Kelime'},{ro:'khuan sai gaang-geng yaao',tr:'uzun pantolon giy',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
      {s:'Ali',th:'รับทราบครับ ผมจะเปลี่ยนครับ',ro:'rap-saap khrap pom ja plian khrap',tr:'Anladim degistirecegim.',bd:[{ro:'pom ja plian',tr:'degistirecegim',role:'V - Yuklem'},{ro:'khrap',tr:'kibar eki',role:'Kibar'}]},
      {s:'Nada',th:'ขอบคุณที่ให้ความเคารพค่ะ',ro:'khop-khun thii hai khwaam-khao-rop kha',tr:'Saygi gosterdiginiz icin tesekkurler.',bd:[{ro:'khop-khun thii hai khwaam-khao-rop',tr:'saygi gosterme icin tesekkur',role:'V - Yuklem'},{ro:'kha',tr:'kibar eki',role:'Kibar'}]},
    ]},
  ],
  listening:[
    {diff:'easy',th:'ผมไหว้ถูกไหมครับ',q:'Ne soruluyor?',opts:['Wai dogru mu','Festival ne zaman','Kiyafet nerede'],c:0},
    {diff:'easy',th:'วัดนี้สวยมากครับ',q:'Ne anlatiliyor?',opts:['Tapinak guzel','Tapinak kapali','Tapinak uzak'],c:0},
    {diff:'easy',th:'ก่อนเข้าวัดต้องถอดรองเท้าครับ',q:'Kural ne?',opts:['Sapka cikar','Ayakkabi cikar','Sessiz kalma'],c:1},
    {diff:'medium',th:'เดือนนี้มีเทศกาลอะไรครับ',q:'Ne soruluyor?',opts:['Bu ay hangi festival','Bilet fiyati','Otobus saati'],c:0},
    {diff:'medium',th:'สงกรานต์สนุกมากครับ',q:'Yorum nedir?',opts:['Sikici','Eglenceli','Tehlikeli'],c:1},
    {diff:'medium',th:'เสื้อผ้านี้สุภาพไหมครับ',q:'Ne soruluyor?',opts:['Kiyafet uygun mu','Kiyafet pahali mi','Kiyafet yeni mi'],c:0},
    {diff:'medium',th:'ความสุภาพสำคัญมากในไทยครับ',q:'Ne vurgulaniyor?',opts:['Hiz','Kibarlik','Fiyat'],c:1},
    {diff:'hard',th:'อย่าแตะหัวคนอื่นนะครับ',q:'Ne yapilmamali?',opts:['Fotograf cekmek','Baskasinin basina dokunmak','Wai yapmak'],c:1},
    {diff:'hard',th:'ผมอยากเรียนรู้วัฒนธรรมไทยครับ',q:'Konusmaci ne istiyor?',opts:['Tay kulturu ogrenmek','Tayca unutmak','Sehir degistirmek'],c:0},
    {diff:'hard',th:'ขอบคุณที่ให้ความเคารพค่ะ',q:'Neden tesekkur ediyor?',opts:['Hediye icin','Saygi gosterildigi icin','Fotograf icin'],c:1},
  ],
  quiz:[
    {q:'wai ne demek?',opts:['Yemek','Selam jesti','Bilet','Adres'],c:1},
    {q:'wat ne demek?',opts:['Tapinak','Hastane','Muze','Pazar'],c:0},
    {q:'phra-phut-tha-ruup ne demek?',opts:['Rahip','Buddha heykeli','Festival','Kitap'],c:1},
    {q:'thot rong-thao ne demek?',opts:['Ayakkabi cikarmak','Kosmak','Dua etmek','Beklemek'],c:0},
    {q:'khwaam-khao-rop thaang wat-tha-na-tham ne demek?',opts:['Kulturel saygi','Kulturel gezi','Kulturel yemek','Kulturel oyun'],c:0},
    {q:'thet-sa-gaan ne demek?',opts:['Festival','Bilet','Konsolosluk','Taksi'],c:0},
    {q:'song-kran nedir?',opts:['Pazar gunu','Su festivali','Tapinak kapisi','Ulasim karti'],c:1},
    {q:'seua-phaa ne demek?',opts:['Kiyafet','Ayakkabi','Canta','Saat'],c:0},
    {q:'hua ne demek?',opts:['El','Bas','Ayak','Yuz'],c:1},
    {q:'khwaam-su-phaap ne demek?',opts:['Hiz','Kibarlik','Yorgunluk','Sessizlik'],c:1},
  ],
};

LESSONS[16] = L16;
